
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  categories: 'categories',
  contacts: 'contacts',
  conversations: 'conversations',
  demandes_accompagnement: 'demandes_accompagnement',
  devis: 'devis',
  formules_accompagnement: 'formules_accompagnement',
  logs_activite: 'logs_activite',
  messages: 'messages',
  notifications: 'notifications',
  parametres: 'parametres',
  password_resets: 'password_resets',
  pays: 'pays',
  produits: 'produits',
  produits_images: 'produits_images',
  reservations: 'reservations',
  sessions: 'sessions',
  tarifs_transport: 'tarifs_transport',
  transport_documents: 'transport_documents',
  transport_timeline: 'transport_timeline',
  transports: 'transports',
  users: 'users'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CategoriesScalarFieldEnum = {
  id: 'id',
  nom: 'nom',
  slug: 'slug',
  description: 'description',
  image_url: 'image_url',
  ordre: 'ordre',
  actif: 'actif',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type CategoriesScalarFieldEnum = (typeof CategoriesScalarFieldEnum)[keyof typeof CategoriesScalarFieldEnum]


export const ContactsScalarFieldEnum = {
  id: 'id',
  nom: 'nom',
  email: 'email',
  telephone: 'telephone',
  sujet: 'sujet',
  message: 'message',
  ip_address: 'ip_address',
  traite: 'traite',
  traite_par: 'traite_par',
  date_traitement: 'date_traitement',
  reponse: 'reponse',
  created_at: 'created_at'
} as const

export type ContactsScalarFieldEnum = (typeof ContactsScalarFieldEnum)[keyof typeof ContactsScalarFieldEnum]


export const ConversationsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  sujet: 'sujet',
  statut: 'statut',
  priorite: 'priorite',
  derniere_activite: 'derniere_activite',
  assigne_a: 'assigne_a',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type ConversationsScalarFieldEnum = (typeof ConversationsScalarFieldEnum)[keyof typeof ConversationsScalarFieldEnum]


export const Demandes_accompagnementScalarFieldEnum = {
  id: 'id',
  numero_demande: 'numero_demande',
  user_id: 'user_id',
  formule_id: 'formule_id',
  description_projet: 'description_projet',
  budget_estime: 'budget_estime',
  devise: 'devise',
  statut: 'statut',
  notes_admin: 'notes_admin',
  date_debut: 'date_debut',
  date_fin: 'date_fin',
  assigne_a: 'assigne_a',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Demandes_accompagnementScalarFieldEnum = (typeof Demandes_accompagnementScalarFieldEnum)[keyof typeof Demandes_accompagnementScalarFieldEnum]


export const DevisScalarFieldEnum = {
  id: 'id',
  numero_devis: 'numero_devis',
  user_id: 'user_id',
  type_service: 'type_service',
  nom: 'nom',
  email: 'email',
  telephone: 'telephone',
  pays: 'pays',
  details: 'details',
  statut: 'statut',
  reponse: 'reponse',
  montant: 'montant',
  devise: 'devise',
  delai: 'delai',
  valide_jusque: 'valide_jusque',
  date_reponse: 'date_reponse',
  traite_par: 'traite_par',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type DevisScalarFieldEnum = (typeof DevisScalarFieldEnum)[keyof typeof DevisScalarFieldEnum]


export const Formules_accompagnementScalarFieldEnum = {
  id: 'id',
  nom: 'nom',
  slug: 'slug',
  description: 'description',
  services_inclus: 'services_inclus',
  prix: 'prix',
  devise: 'devise',
  duree: 'duree',
  ordre: 'ordre',
  actif: 'actif',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Formules_accompagnementScalarFieldEnum = (typeof Formules_accompagnementScalarFieldEnum)[keyof typeof Formules_accompagnementScalarFieldEnum]


export const Logs_activiteScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  type_activite: 'type_activite',
  description: 'description',
  entite_type: 'entite_type',
  entite_id: 'entite_id',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  data: 'data',
  created_at: 'created_at'
} as const

export type Logs_activiteScalarFieldEnum = (typeof Logs_activiteScalarFieldEnum)[keyof typeof Logs_activiteScalarFieldEnum]


export const MessagesScalarFieldEnum = {
  id: 'id',
  conversation_id: 'conversation_id',
  expediteur_id: 'expediteur_id',
  contenu: 'contenu',
  est_admin: 'est_admin',
  lu: 'lu',
  date_lecture: 'date_lecture',
  fichiers_attaches: 'fichiers_attaches',
  created_at: 'created_at'
} as const

export type MessagesScalarFieldEnum = (typeof MessagesScalarFieldEnum)[keyof typeof MessagesScalarFieldEnum]


export const NotificationsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  type: 'type',
  titre: 'titre',
  message: 'message',
  lien: 'lien',
  lu: 'lu',
  date_lecture: 'date_lecture',
  data: 'data',
  created_at: 'created_at'
} as const

export type NotificationsScalarFieldEnum = (typeof NotificationsScalarFieldEnum)[keyof typeof NotificationsScalarFieldEnum]


export const ParametresScalarFieldEnum = {
  id: 'id',
  cle: 'cle',
  valeur: 'valeur',
  type: 'type',
  description: 'description',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type ParametresScalarFieldEnum = (typeof ParametresScalarFieldEnum)[keyof typeof ParametresScalarFieldEnum]


export const Password_resetsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  token: 'token',
  expires_at: 'expires_at',
  utilise: 'utilise',
  created_at: 'created_at'
} as const

export type Password_resetsScalarFieldEnum = (typeof Password_resetsScalarFieldEnum)[keyof typeof Password_resetsScalarFieldEnum]


export const PaysScalarFieldEnum = {
  id: 'id',
  nom: 'nom',
  code: 'code',
  region: 'region',
  actif: 'actif',
  created_at: 'created_at'
} as const

export type PaysScalarFieldEnum = (typeof PaysScalarFieldEnum)[keyof typeof PaysScalarFieldEnum]


export const ProduitsScalarFieldEnum = {
  id: 'id',
  categorie_id: 'categorie_id',
  nom: 'nom',
  slug: 'slug',
  description: 'description',
  description_courte: 'description_courte',
  prix: 'prix',
  devise: 'devise',
  pays_origine: 'pays_origine',
  quantite_minimum: 'quantite_minimum',
  delai_livraison: 'delai_livraison',
  poids: 'poids',
  dimensions: 'dimensions',
  caracteristiques: 'caracteristiques',
  disponible: 'disponible',
  stock: 'stock',
  nombre_vues: 'nombre_vues',
  nombre_reservations: 'nombre_reservations',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type ProduitsScalarFieldEnum = (typeof ProduitsScalarFieldEnum)[keyof typeof ProduitsScalarFieldEnum]


export const Produits_imagesScalarFieldEnum = {
  id: 'id',
  produit_id: 'produit_id',
  url: 'url',
  alt_text: 'alt_text',
  ordre: 'ordre',
  est_principale: 'est_principale',
  created_at: 'created_at'
} as const

export type Produits_imagesScalarFieldEnum = (typeof Produits_imagesScalarFieldEnum)[keyof typeof Produits_imagesScalarFieldEnum]


export const ReservationsScalarFieldEnum = {
  id: 'id',
  numero_reservation: 'numero_reservation',
  user_id: 'user_id',
  produit_id: 'produit_id',
  quantite: 'quantite',
  prix_unitaire: 'prix_unitaire',
  prix_total: 'prix_total',
  devise: 'devise',
  statut: 'statut',
  notes: 'notes',
  notes_admin: 'notes_admin',
  date_confirmation: 'date_confirmation',
  date_annulation: 'date_annulation',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type ReservationsScalarFieldEnum = (typeof ReservationsScalarFieldEnum)[keyof typeof ReservationsScalarFieldEnum]


export const SessionsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  token: 'token',
  refresh_token: 'refresh_token',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  expires_at: 'expires_at',
  created_at: 'created_at'
} as const

export type SessionsScalarFieldEnum = (typeof SessionsScalarFieldEnum)[keyof typeof SessionsScalarFieldEnum]


export const Tarifs_transportScalarFieldEnum = {
  id: 'id',
  pays_depart: 'pays_depart',
  pays_destination: 'pays_destination',
  mode_transport: 'mode_transport',
  poids_min: 'poids_min',
  poids_max: 'poids_max',
  prix_par_kg: 'prix_par_kg',
  prix_par_m3: 'prix_par_m3',
  delai_moyen: 'delai_moyen',
  devise: 'devise',
  actif: 'actif',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Tarifs_transportScalarFieldEnum = (typeof Tarifs_transportScalarFieldEnum)[keyof typeof Tarifs_transportScalarFieldEnum]


export const Transport_documentsScalarFieldEnum = {
  id: 'id',
  transport_id: 'transport_id',
  nom: 'nom',
  type: 'type',
  url: 'url',
  taille: 'taille',
  uploaded_par: 'uploaded_par',
  created_at: 'created_at'
} as const

export type Transport_documentsScalarFieldEnum = (typeof Transport_documentsScalarFieldEnum)[keyof typeof Transport_documentsScalarFieldEnum]


export const Transport_timelineScalarFieldEnum = {
  id: 'id',
  transport_id: 'transport_id',
  etape: 'etape',
  description: 'description',
  statut: 'statut',
  localisation: 'localisation',
  date_evenement: 'date_evenement',
  cree_par: 'cree_par',
  created_at: 'created_at'
} as const

export type Transport_timelineScalarFieldEnum = (typeof Transport_timelineScalarFieldEnum)[keyof typeof Transport_timelineScalarFieldEnum]


export const TransportsScalarFieldEnum = {
  id: 'id',
  numero_transport: 'numero_transport',
  user_id: 'user_id',
  pays_depart: 'pays_depart',
  pays_destination: 'pays_destination',
  ville_destination: 'ville_destination',
  type_marchandise: 'type_marchandise',
  description: 'description',
  poids: 'poids',
  volume: 'volume',
  mode_transport: 'mode_transport',
  prix_estime: 'prix_estime',
  prix_final: 'prix_final',
  devise: 'devise',
  delai_estime: 'delai_estime',
  statut: 'statut',
  date_depart: 'date_depart',
  date_arrivee_estimee: 'date_arrivee_estimee',
  date_arrivee_reelle: 'date_arrivee_reelle',
  numero_suivi: 'numero_suivi',
  compagnie_transport: 'compagnie_transport',
  notes_client: 'notes_client',
  notes_admin: 'notes_admin',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type TransportsScalarFieldEnum = (typeof TransportsScalarFieldEnum)[keyof typeof TransportsScalarFieldEnum]


export const UsersScalarFieldEnum = {
  id: 'id',
  nom: 'nom',
  prenom: 'prenom',
  email: 'email',
  telephone: 'telephone',
  pays: 'pays',
  adresse: 'adresse',
  mot_de_passe_hash: 'mot_de_passe_hash',
  role: 'role',
  statut: 'statut',
  date_inscription: 'date_inscription',
  date_derniere_connexion: 'date_derniere_connexion',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

