
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model categories
 * 
 */
export type categories = Prisma.categoriesModel
/**
 * Model contacts
 * 
 */
export type contacts = Prisma.contactsModel
/**
 * Model conversations
 * 
 */
export type conversations = Prisma.conversationsModel
/**
 * Model demandes_accompagnement
 * 
 */
export type demandes_accompagnement = Prisma.demandes_accompagnementModel
/**
 * Model devis
 * 
 */
export type devis = Prisma.devisModel
/**
 * Model formules_accompagnement
 * 
 */
export type formules_accompagnement = Prisma.formules_accompagnementModel
/**
 * Model logs_activite
 * 
 */
export type logs_activite = Prisma.logs_activiteModel
/**
 * Model messages
 * 
 */
export type messages = Prisma.messagesModel
/**
 * Model notifications
 * 
 */
export type notifications = Prisma.notificationsModel
/**
 * Model parametres
 * 
 */
export type parametres = Prisma.parametresModel
/**
 * Model password_resets
 * 
 */
export type password_resets = Prisma.password_resetsModel
/**
 * Model pays
 * 
 */
export type pays = Prisma.paysModel
/**
 * Model produits
 * 
 */
export type produits = Prisma.produitsModel
/**
 * Model produits_images
 * 
 */
export type produits_images = Prisma.produits_imagesModel
/**
 * Model reservations
 * 
 */
export type reservations = Prisma.reservationsModel
/**
 * Model sessions
 * 
 */
export type sessions = Prisma.sessionsModel
/**
 * Model tarifs_transport
 * 
 */
export type tarifs_transport = Prisma.tarifs_transportModel
/**
 * Model transport_documents
 * 
 */
export type transport_documents = Prisma.transport_documentsModel
/**
 * Model transport_timeline
 * 
 */
export type transport_timeline = Prisma.transport_timelineModel
/**
 * Model transports
 * 
 */
export type transports = Prisma.transportsModel
/**
 * Model users
 * 
 */
export type users = Prisma.usersModel
