
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Categories
 * const categories = await prisma.categories.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model categories
 * 
 */
export type categories = Prisma.categoriesModel
/**
 * Model contacts
 * 
 */
export type contacts = Prisma.contactsModel
/**
 * Model conversations
 * 
 */
export type conversations = Prisma.conversationsModel
/**
 * Model demandes_accompagnement
 * 
 */
export type demandes_accompagnement = Prisma.demandes_accompagnementModel
/**
 * Model devis
 * 
 */
export type devis = Prisma.devisModel
/**
 * Model formules_accompagnement
 * 
 */
export type formules_accompagnement = Prisma.formules_accompagnementModel
/**
 * Model logs_activite
 * 
 */
export type logs_activite = Prisma.logs_activiteModel
/**
 * Model messages
 * 
 */
export type messages = Prisma.messagesModel
/**
 * Model notifications
 * 
 */
export type notifications = Prisma.notificationsModel
/**
 * Model parametres
 * 
 */
export type parametres = Prisma.parametresModel
/**
 * Model password_resets
 * 
 */
export type password_resets = Prisma.password_resetsModel
/**
 * Model pays
 * 
 */
export type pays = Prisma.paysModel
/**
 * Model produits
 * 
 */
export type produits = Prisma.produitsModel
/**
 * Model produits_images
 * 
 */
export type produits_images = Prisma.produits_imagesModel
/**
 * Model reservations
 * 
 */
export type reservations = Prisma.reservationsModel
/**
 * Model sessions
 * 
 */
export type sessions = Prisma.sessionsModel
/**
 * Model tarifs_transport
 * 
 */
export type tarifs_transport = Prisma.tarifs_transportModel
/**
 * Model transport_documents
 * 
 */
export type transport_documents = Prisma.transport_documentsModel
/**
 * Model transport_timeline
 * 
 */
export type transport_timeline = Prisma.transport_timelineModel
/**
 * Model transports
 * 
 */
export type transports = Prisma.transportsModel
/**
 * Model users
 * 
 */
export type users = Prisma.usersModel
