
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const conversation_statut = {
  ouvert: 'ouvert',
  en_cours: 'en_cours',
  resolu: 'resolu',
  ferme: 'ferme'
} as const

export type conversation_statut = (typeof conversation_statut)[keyof typeof conversation_statut]


export const demande_accompagnement_statut = {
  en_attente: 'en_attente',
  en_cours: 'en_cours',
  acceptee: 'acceptee',
  refusee: 'refusee',
  terminee: 'terminee'
} as const

export type demande_accompagnement_statut = (typeof demande_accompagnement_statut)[keyof typeof demande_accompagnement_statut]


export const devis_statut = {
  en_attente: 'en_attente',
  en_cours: 'en_cours',
  envoye: 'envoye',
  accepte: 'accepte',
  refuse: 'refuse'
} as const

export type devis_statut = (typeof devis_statut)[keyof typeof devis_statut]


export const devis_type = {
  achat: 'achat',
  transport: 'transport',
  accompagnement: 'accompagnement'
} as const

export type devis_type = (typeof devis_type)[keyof typeof devis_type]


export const pays_enum = {
  Chine: 'Chine',
  Duba_: 'Dubaï'
} as const

export type pays_enum = (typeof pays_enum)[keyof typeof pays_enum]


export const priorite = {
  basse: 'basse',
  normale: 'normale',
  haute: 'haute',
  urgente: 'urgente'
} as const

export type priorite = (typeof priorite)[keyof typeof priorite]


export const reservation_statut = {
  en_attente: 'en_attente',
  confirmee: 'confirmee',
  traitee: 'traitee',
  annulee: 'annulee'
} as const

export type reservation_statut = (typeof reservation_statut)[keyof typeof reservation_statut]


export const transport_mode = {
  maritime: 'maritime',
  aerien: 'aerien'
} as const

export type transport_mode = (typeof transport_mode)[keyof typeof transport_mode]


export const transport_statut = {
  en_attente: 'en_attente',
  confirme: 'confirme',
  marchandise_recue: 'marchandise_recue',
  en_transit: 'en_transit',
  arrive: 'arrive',
  livre: 'livre',
  annule: 'annule'
} as const

export type transport_statut = (typeof transport_statut)[keyof typeof transport_statut]


export const user_role = {
  client: 'client',
  admin: 'admin'
} as const

export type user_role = (typeof user_role)[keyof typeof user_role]


export const user_statut = {
  actif: 'actif',
  inactif: 'inactif',
  suspendu: 'suspendu'
} as const

export type user_statut = (typeof user_statut)[keyof typeof user_statut]
