
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `devis` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model devis
 * 
 */
export type devisModel = runtime.Types.Result.DefaultSelection<Prisma.$devisPayload>

export type AggregateDevis = {
  _count: DevisCountAggregateOutputType | null
  _avg: DevisAvgAggregateOutputType | null
  _sum: DevisSumAggregateOutputType | null
  _min: DevisMinAggregateOutputType | null
  _max: DevisMaxAggregateOutputType | null
}

export type DevisAvgAggregateOutputType = {
  montant: runtime.Decimal | null
}

export type DevisSumAggregateOutputType = {
  montant: runtime.Decimal | null
}

export type DevisMinAggregateOutputType = {
  id: string | null
  numero_devis: string | null
  user_id: string | null
  type_service: $Enums.devis_type | null
  nom: string | null
  email: string | null
  telephone: string | null
  pays: string | null
  details: string | null
  statut: $Enums.devis_statut | null
  reponse: string | null
  montant: runtime.Decimal | null
  devise: string | null
  delai: string | null
  valide_jusque: Date | null
  date_reponse: Date | null
  traite_par: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type DevisMaxAggregateOutputType = {
  id: string | null
  numero_devis: string | null
  user_id: string | null
  type_service: $Enums.devis_type | null
  nom: string | null
  email: string | null
  telephone: string | null
  pays: string | null
  details: string | null
  statut: $Enums.devis_statut | null
  reponse: string | null
  montant: runtime.Decimal | null
  devise: string | null
  delai: string | null
  valide_jusque: Date | null
  date_reponse: Date | null
  traite_par: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type DevisCountAggregateOutputType = {
  id: number
  numero_devis: number
  user_id: number
  type_service: number
  nom: number
  email: number
  telephone: number
  pays: number
  details: number
  statut: number
  reponse: number
  montant: number
  devise: number
  delai: number
  valide_jusque: number
  date_reponse: number
  traite_par: number
  created_at: number
  updated_at: number
  _all: number
}


export type DevisAvgAggregateInputType = {
  montant?: true
}

export type DevisSumAggregateInputType = {
  montant?: true
}

export type DevisMinAggregateInputType = {
  id?: true
  numero_devis?: true
  user_id?: true
  type_service?: true
  nom?: true
  email?: true
  telephone?: true
  pays?: true
  details?: true
  statut?: true
  reponse?: true
  montant?: true
  devise?: true
  delai?: true
  valide_jusque?: true
  date_reponse?: true
  traite_par?: true
  created_at?: true
  updated_at?: true
}

export type DevisMaxAggregateInputType = {
  id?: true
  numero_devis?: true
  user_id?: true
  type_service?: true
  nom?: true
  email?: true
  telephone?: true
  pays?: true
  details?: true
  statut?: true
  reponse?: true
  montant?: true
  devise?: true
  delai?: true
  valide_jusque?: true
  date_reponse?: true
  traite_par?: true
  created_at?: true
  updated_at?: true
}

export type DevisCountAggregateInputType = {
  id?: true
  numero_devis?: true
  user_id?: true
  type_service?: true
  nom?: true
  email?: true
  telephone?: true
  pays?: true
  details?: true
  statut?: true
  reponse?: true
  montant?: true
  devise?: true
  delai?: true
  valide_jusque?: true
  date_reponse?: true
  traite_par?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type DevisAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which devis to aggregate.
   */
  where?: Prisma.devisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of devis to fetch.
   */
  orderBy?: Prisma.devisOrderByWithRelationInput | Prisma.devisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.devisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` devis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` devis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned devis
  **/
  _count?: true | DevisCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DevisAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DevisSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DevisMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DevisMaxAggregateInputType
}

export type GetDevisAggregateType<T extends DevisAggregateArgs> = {
      [P in keyof T & keyof AggregateDevis]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDevis[P]>
    : Prisma.GetScalarType<T[P], AggregateDevis[P]>
}




export type devisGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.devisWhereInput
  orderBy?: Prisma.devisOrderByWithAggregationInput | Prisma.devisOrderByWithAggregationInput[]
  by: Prisma.DevisScalarFieldEnum[] | Prisma.DevisScalarFieldEnum
  having?: Prisma.devisScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DevisCountAggregateInputType | true
  _avg?: DevisAvgAggregateInputType
  _sum?: DevisSumAggregateInputType
  _min?: DevisMinAggregateInputType
  _max?: DevisMaxAggregateInputType
}

export type DevisGroupByOutputType = {
  id: string
  numero_devis: string
  user_id: string | null
  type_service: $Enums.devis_type
  nom: string
  email: string
  telephone: string
  pays: string
  details: string
  statut: $Enums.devis_statut | null
  reponse: string | null
  montant: runtime.Decimal | null
  devise: string | null
  delai: string | null
  valide_jusque: Date | null
  date_reponse: Date | null
  traite_par: string | null
  created_at: Date | null
  updated_at: Date | null
  _count: DevisCountAggregateOutputType | null
  _avg: DevisAvgAggregateOutputType | null
  _sum: DevisSumAggregateOutputType | null
  _min: DevisMinAggregateOutputType | null
  _max: DevisMaxAggregateOutputType | null
}

type GetDevisGroupByPayload<T extends devisGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DevisGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DevisGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DevisGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DevisGroupByOutputType[P]>
      }
    >
  >



export type devisWhereInput = {
  AND?: Prisma.devisWhereInput | Prisma.devisWhereInput[]
  OR?: Prisma.devisWhereInput[]
  NOT?: Prisma.devisWhereInput | Prisma.devisWhereInput[]
  id?: Prisma.StringFilter<"devis"> | string
  numero_devis?: Prisma.StringFilter<"devis"> | string
  user_id?: Prisma.StringNullableFilter<"devis"> | string | null
  type_service?: Prisma.Enumdevis_typeFilter<"devis"> | $Enums.devis_type
  nom?: Prisma.StringFilter<"devis"> | string
  email?: Prisma.StringFilter<"devis"> | string
  telephone?: Prisma.StringFilter<"devis"> | string
  pays?: Prisma.StringFilter<"devis"> | string
  details?: Prisma.StringFilter<"devis"> | string
  statut?: Prisma.Enumdevis_statutNullableFilter<"devis"> | $Enums.devis_statut | null
  reponse?: Prisma.StringNullableFilter<"devis"> | string | null
  montant?: Prisma.DecimalNullableFilter<"devis"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.StringNullableFilter<"devis"> | string | null
  delai?: Prisma.StringNullableFilter<"devis"> | string | null
  valide_jusque?: Prisma.DateTimeNullableFilter<"devis"> | Date | string | null
  date_reponse?: Prisma.DateTimeNullableFilter<"devis"> | Date | string | null
  traite_par?: Prisma.StringNullableFilter<"devis"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"devis"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"devis"> | Date | string | null
  users_devis_traite_parTousers?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
  users_devis_user_idTousers?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}

export type devisOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  numero_devis?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  type_service?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  email?: Prisma.SortOrder
  telephone?: Prisma.SortOrder
  pays?: Prisma.SortOrder
  details?: Prisma.SortOrder
  statut?: Prisma.SortOrderInput | Prisma.SortOrder
  reponse?: Prisma.SortOrderInput | Prisma.SortOrder
  montant?: Prisma.SortOrderInput | Prisma.SortOrder
  devise?: Prisma.SortOrderInput | Prisma.SortOrder
  delai?: Prisma.SortOrderInput | Prisma.SortOrder
  valide_jusque?: Prisma.SortOrderInput | Prisma.SortOrder
  date_reponse?: Prisma.SortOrderInput | Prisma.SortOrder
  traite_par?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  users_devis_traite_parTousers?: Prisma.usersOrderByWithRelationInput
  users_devis_user_idTousers?: Prisma.usersOrderByWithRelationInput
}

export type devisWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  numero_devis?: string
  AND?: Prisma.devisWhereInput | Prisma.devisWhereInput[]
  OR?: Prisma.devisWhereInput[]
  NOT?: Prisma.devisWhereInput | Prisma.devisWhereInput[]
  user_id?: Prisma.StringNullableFilter<"devis"> | string | null
  type_service?: Prisma.Enumdevis_typeFilter<"devis"> | $Enums.devis_type
  nom?: Prisma.StringFilter<"devis"> | string
  email?: Prisma.StringFilter<"devis"> | string
  telephone?: Prisma.StringFilter<"devis"> | string
  pays?: Prisma.StringFilter<"devis"> | string
  details?: Prisma.StringFilter<"devis"> | string
  statut?: Prisma.Enumdevis_statutNullableFilter<"devis"> | $Enums.devis_statut | null
  reponse?: Prisma.StringNullableFilter<"devis"> | string | null
  montant?: Prisma.DecimalNullableFilter<"devis"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.StringNullableFilter<"devis"> | string | null
  delai?: Prisma.StringNullableFilter<"devis"> | string | null
  valide_jusque?: Prisma.DateTimeNullableFilter<"devis"> | Date | string | null
  date_reponse?: Prisma.DateTimeNullableFilter<"devis"> | Date | string | null
  traite_par?: Prisma.StringNullableFilter<"devis"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"devis"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"devis"> | Date | string | null
  users_devis_traite_parTousers?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
  users_devis_user_idTousers?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}, "id" | "numero_devis">

export type devisOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  numero_devis?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  type_service?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  email?: Prisma.SortOrder
  telephone?: Prisma.SortOrder
  pays?: Prisma.SortOrder
  details?: Prisma.SortOrder
  statut?: Prisma.SortOrderInput | Prisma.SortOrder
  reponse?: Prisma.SortOrderInput | Prisma.SortOrder
  montant?: Prisma.SortOrderInput | Prisma.SortOrder
  devise?: Prisma.SortOrderInput | Prisma.SortOrder
  delai?: Prisma.SortOrderInput | Prisma.SortOrder
  valide_jusque?: Prisma.SortOrderInput | Prisma.SortOrder
  date_reponse?: Prisma.SortOrderInput | Prisma.SortOrder
  traite_par?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.devisCountOrderByAggregateInput
  _avg?: Prisma.devisAvgOrderByAggregateInput
  _max?: Prisma.devisMaxOrderByAggregateInput
  _min?: Prisma.devisMinOrderByAggregateInput
  _sum?: Prisma.devisSumOrderByAggregateInput
}

export type devisScalarWhereWithAggregatesInput = {
  AND?: Prisma.devisScalarWhereWithAggregatesInput | Prisma.devisScalarWhereWithAggregatesInput[]
  OR?: Prisma.devisScalarWhereWithAggregatesInput[]
  NOT?: Prisma.devisScalarWhereWithAggregatesInput | Prisma.devisScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"devis"> | string
  numero_devis?: Prisma.StringWithAggregatesFilter<"devis"> | string
  user_id?: Prisma.StringNullableWithAggregatesFilter<"devis"> | string | null
  type_service?: Prisma.Enumdevis_typeWithAggregatesFilter<"devis"> | $Enums.devis_type
  nom?: Prisma.StringWithAggregatesFilter<"devis"> | string
  email?: Prisma.StringWithAggregatesFilter<"devis"> | string
  telephone?: Prisma.StringWithAggregatesFilter<"devis"> | string
  pays?: Prisma.StringWithAggregatesFilter<"devis"> | string
  details?: Prisma.StringWithAggregatesFilter<"devis"> | string
  statut?: Prisma.Enumdevis_statutNullableWithAggregatesFilter<"devis"> | $Enums.devis_statut | null
  reponse?: Prisma.StringNullableWithAggregatesFilter<"devis"> | string | null
  montant?: Prisma.DecimalNullableWithAggregatesFilter<"devis"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.StringNullableWithAggregatesFilter<"devis"> | string | null
  delai?: Prisma.StringNullableWithAggregatesFilter<"devis"> | string | null
  valide_jusque?: Prisma.DateTimeNullableWithAggregatesFilter<"devis"> | Date | string | null
  date_reponse?: Prisma.DateTimeNullableWithAggregatesFilter<"devis"> | Date | string | null
  traite_par?: Prisma.StringNullableWithAggregatesFilter<"devis"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"devis"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"devis"> | Date | string | null
}

export type devisCreateInput = {
  id: string
  numero_devis: string
  type_service: $Enums.devis_type
  nom: string
  email: string
  telephone: string
  pays: string
  details: string
  statut?: $Enums.devis_statut | null
  reponse?: string | null
  montant?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  delai?: string | null
  valide_jusque?: Date | string | null
  date_reponse?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  users_devis_traite_parTousers?: Prisma.usersCreateNestedOneWithoutDevis_devis_traite_parTousersInput
  users_devis_user_idTousers?: Prisma.usersCreateNestedOneWithoutDevis_devis_user_idTousersInput
}

export type devisUncheckedCreateInput = {
  id: string
  numero_devis: string
  user_id?: string | null
  type_service: $Enums.devis_type
  nom: string
  email: string
  telephone: string
  pays: string
  details: string
  statut?: $Enums.devis_statut | null
  reponse?: string | null
  montant?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  delai?: string | null
  valide_jusque?: Date | string | null
  date_reponse?: Date | string | null
  traite_par?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type devisUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero_devis?: Prisma.StringFieldUpdateOperationsInput | string
  type_service?: Prisma.Enumdevis_typeFieldUpdateOperationsInput | $Enums.devis_type
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  telephone?: Prisma.StringFieldUpdateOperationsInput | string
  pays?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  statut?: Prisma.NullableEnumdevis_statutFieldUpdateOperationsInput | $Enums.devis_statut | null
  reponse?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  montant?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delai?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valide_jusque?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  date_reponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users_devis_traite_parTousers?: Prisma.usersUpdateOneWithoutDevis_devis_traite_parTousersNestedInput
  users_devis_user_idTousers?: Prisma.usersUpdateOneWithoutDevis_devis_user_idTousersNestedInput
}

export type devisUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero_devis?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type_service?: Prisma.Enumdevis_typeFieldUpdateOperationsInput | $Enums.devis_type
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  telephone?: Prisma.StringFieldUpdateOperationsInput | string
  pays?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  statut?: Prisma.NullableEnumdevis_statutFieldUpdateOperationsInput | $Enums.devis_statut | null
  reponse?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  montant?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delai?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valide_jusque?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  date_reponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  traite_par?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type devisCreateManyInput = {
  id: string
  numero_devis: string
  user_id?: string | null
  type_service: $Enums.devis_type
  nom: string
  email: string
  telephone: string
  pays: string
  details: string
  statut?: $Enums.devis_statut | null
  reponse?: string | null
  montant?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  delai?: string | null
  valide_jusque?: Date | string | null
  date_reponse?: Date | string | null
  traite_par?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type devisUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero_devis?: Prisma.StringFieldUpdateOperationsInput | string
  type_service?: Prisma.Enumdevis_typeFieldUpdateOperationsInput | $Enums.devis_type
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  telephone?: Prisma.StringFieldUpdateOperationsInput | string
  pays?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  statut?: Prisma.NullableEnumdevis_statutFieldUpdateOperationsInput | $Enums.devis_statut | null
  reponse?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  montant?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delai?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valide_jusque?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  date_reponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type devisUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero_devis?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type_service?: Prisma.Enumdevis_typeFieldUpdateOperationsInput | $Enums.devis_type
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  telephone?: Prisma.StringFieldUpdateOperationsInput | string
  pays?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  statut?: Prisma.NullableEnumdevis_statutFieldUpdateOperationsInput | $Enums.devis_statut | null
  reponse?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  montant?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delai?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valide_jusque?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  date_reponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  traite_par?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type devisCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  numero_devis?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  type_service?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  email?: Prisma.SortOrder
  telephone?: Prisma.SortOrder
  pays?: Prisma.SortOrder
  details?: Prisma.SortOrder
  statut?: Prisma.SortOrder
  reponse?: Prisma.SortOrder
  montant?: Prisma.SortOrder
  devise?: Prisma.SortOrder
  delai?: Prisma.SortOrder
  valide_jusque?: Prisma.SortOrder
  date_reponse?: Prisma.SortOrder
  traite_par?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type devisAvgOrderByAggregateInput = {
  montant?: Prisma.SortOrder
}

export type devisMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  numero_devis?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  type_service?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  email?: Prisma.SortOrder
  telephone?: Prisma.SortOrder
  pays?: Prisma.SortOrder
  details?: Prisma.SortOrder
  statut?: Prisma.SortOrder
  reponse?: Prisma.SortOrder
  montant?: Prisma.SortOrder
  devise?: Prisma.SortOrder
  delai?: Prisma.SortOrder
  valide_jusque?: Prisma.SortOrder
  date_reponse?: Prisma.SortOrder
  traite_par?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type devisMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  numero_devis?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  type_service?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  email?: Prisma.SortOrder
  telephone?: Prisma.SortOrder
  pays?: Prisma.SortOrder
  details?: Prisma.SortOrder
  statut?: Prisma.SortOrder
  reponse?: Prisma.SortOrder
  montant?: Prisma.SortOrder
  devise?: Prisma.SortOrder
  delai?: Prisma.SortOrder
  valide_jusque?: Prisma.SortOrder
  date_reponse?: Prisma.SortOrder
  traite_par?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type devisSumOrderByAggregateInput = {
  montant?: Prisma.SortOrder
}

export type DevisListRelationFilter = {
  every?: Prisma.devisWhereInput
  some?: Prisma.devisWhereInput
  none?: Prisma.devisWhereInput
}

export type devisOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type Enumdevis_typeFieldUpdateOperationsInput = {
  set?: $Enums.devis_type
}

export type NullableEnumdevis_statutFieldUpdateOperationsInput = {
  set?: $Enums.devis_statut | null
}

export type devisCreateNestedManyWithoutUsers_devis_traite_parTousersInput = {
  create?: Prisma.XOR<Prisma.devisCreateWithoutUsers_devis_traite_parTousersInput, Prisma.devisUncheckedCreateWithoutUsers_devis_traite_parTousersInput> | Prisma.devisCreateWithoutUsers_devis_traite_parTousersInput[] | Prisma.devisUncheckedCreateWithoutUsers_devis_traite_parTousersInput[]
  connectOrCreate?: Prisma.devisCreateOrConnectWithoutUsers_devis_traite_parTousersInput | Prisma.devisCreateOrConnectWithoutUsers_devis_traite_parTousersInput[]
  createMany?: Prisma.devisCreateManyUsers_devis_traite_parTousersInputEnvelope
  connect?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
}

export type devisCreateNestedManyWithoutUsers_devis_user_idTousersInput = {
  create?: Prisma.XOR<Prisma.devisCreateWithoutUsers_devis_user_idTousersInput, Prisma.devisUncheckedCreateWithoutUsers_devis_user_idTousersInput> | Prisma.devisCreateWithoutUsers_devis_user_idTousersInput[] | Prisma.devisUncheckedCreateWithoutUsers_devis_user_idTousersInput[]
  connectOrCreate?: Prisma.devisCreateOrConnectWithoutUsers_devis_user_idTousersInput | Prisma.devisCreateOrConnectWithoutUsers_devis_user_idTousersInput[]
  createMany?: Prisma.devisCreateManyUsers_devis_user_idTousersInputEnvelope
  connect?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
}

export type devisUncheckedCreateNestedManyWithoutUsers_devis_traite_parTousersInput = {
  create?: Prisma.XOR<Prisma.devisCreateWithoutUsers_devis_traite_parTousersInput, Prisma.devisUncheckedCreateWithoutUsers_devis_traite_parTousersInput> | Prisma.devisCreateWithoutUsers_devis_traite_parTousersInput[] | Prisma.devisUncheckedCreateWithoutUsers_devis_traite_parTousersInput[]
  connectOrCreate?: Prisma.devisCreateOrConnectWithoutUsers_devis_traite_parTousersInput | Prisma.devisCreateOrConnectWithoutUsers_devis_traite_parTousersInput[]
  createMany?: Prisma.devisCreateManyUsers_devis_traite_parTousersInputEnvelope
  connect?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
}

export type devisUncheckedCreateNestedManyWithoutUsers_devis_user_idTousersInput = {
  create?: Prisma.XOR<Prisma.devisCreateWithoutUsers_devis_user_idTousersInput, Prisma.devisUncheckedCreateWithoutUsers_devis_user_idTousersInput> | Prisma.devisCreateWithoutUsers_devis_user_idTousersInput[] | Prisma.devisUncheckedCreateWithoutUsers_devis_user_idTousersInput[]
  connectOrCreate?: Prisma.devisCreateOrConnectWithoutUsers_devis_user_idTousersInput | Prisma.devisCreateOrConnectWithoutUsers_devis_user_idTousersInput[]
  createMany?: Prisma.devisCreateManyUsers_devis_user_idTousersInputEnvelope
  connect?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
}

export type devisUpdateManyWithoutUsers_devis_traite_parTousersNestedInput = {
  create?: Prisma.XOR<Prisma.devisCreateWithoutUsers_devis_traite_parTousersInput, Prisma.devisUncheckedCreateWithoutUsers_devis_traite_parTousersInput> | Prisma.devisCreateWithoutUsers_devis_traite_parTousersInput[] | Prisma.devisUncheckedCreateWithoutUsers_devis_traite_parTousersInput[]
  connectOrCreate?: Prisma.devisCreateOrConnectWithoutUsers_devis_traite_parTousersInput | Prisma.devisCreateOrConnectWithoutUsers_devis_traite_parTousersInput[]
  upsert?: Prisma.devisUpsertWithWhereUniqueWithoutUsers_devis_traite_parTousersInput | Prisma.devisUpsertWithWhereUniqueWithoutUsers_devis_traite_parTousersInput[]
  createMany?: Prisma.devisCreateManyUsers_devis_traite_parTousersInputEnvelope
  set?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  disconnect?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  delete?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  connect?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  update?: Prisma.devisUpdateWithWhereUniqueWithoutUsers_devis_traite_parTousersInput | Prisma.devisUpdateWithWhereUniqueWithoutUsers_devis_traite_parTousersInput[]
  updateMany?: Prisma.devisUpdateManyWithWhereWithoutUsers_devis_traite_parTousersInput | Prisma.devisUpdateManyWithWhereWithoutUsers_devis_traite_parTousersInput[]
  deleteMany?: Prisma.devisScalarWhereInput | Prisma.devisScalarWhereInput[]
}

export type devisUpdateManyWithoutUsers_devis_user_idTousersNestedInput = {
  create?: Prisma.XOR<Prisma.devisCreateWithoutUsers_devis_user_idTousersInput, Prisma.devisUncheckedCreateWithoutUsers_devis_user_idTousersInput> | Prisma.devisCreateWithoutUsers_devis_user_idTousersInput[] | Prisma.devisUncheckedCreateWithoutUsers_devis_user_idTousersInput[]
  connectOrCreate?: Prisma.devisCreateOrConnectWithoutUsers_devis_user_idTousersInput | Prisma.devisCreateOrConnectWithoutUsers_devis_user_idTousersInput[]
  upsert?: Prisma.devisUpsertWithWhereUniqueWithoutUsers_devis_user_idTousersInput | Prisma.devisUpsertWithWhereUniqueWithoutUsers_devis_user_idTousersInput[]
  createMany?: Prisma.devisCreateManyUsers_devis_user_idTousersInputEnvelope
  set?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  disconnect?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  delete?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  connect?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  update?: Prisma.devisUpdateWithWhereUniqueWithoutUsers_devis_user_idTousersInput | Prisma.devisUpdateWithWhereUniqueWithoutUsers_devis_user_idTousersInput[]
  updateMany?: Prisma.devisUpdateManyWithWhereWithoutUsers_devis_user_idTousersInput | Prisma.devisUpdateManyWithWhereWithoutUsers_devis_user_idTousersInput[]
  deleteMany?: Prisma.devisScalarWhereInput | Prisma.devisScalarWhereInput[]
}

export type devisUncheckedUpdateManyWithoutUsers_devis_traite_parTousersNestedInput = {
  create?: Prisma.XOR<Prisma.devisCreateWithoutUsers_devis_traite_parTousersInput, Prisma.devisUncheckedCreateWithoutUsers_devis_traite_parTousersInput> | Prisma.devisCreateWithoutUsers_devis_traite_parTousersInput[] | Prisma.devisUncheckedCreateWithoutUsers_devis_traite_parTousersInput[]
  connectOrCreate?: Prisma.devisCreateOrConnectWithoutUsers_devis_traite_parTousersInput | Prisma.devisCreateOrConnectWithoutUsers_devis_traite_parTousersInput[]
  upsert?: Prisma.devisUpsertWithWhereUniqueWithoutUsers_devis_traite_parTousersInput | Prisma.devisUpsertWithWhereUniqueWithoutUsers_devis_traite_parTousersInput[]
  createMany?: Prisma.devisCreateManyUsers_devis_traite_parTousersInputEnvelope
  set?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  disconnect?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  delete?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  connect?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  update?: Prisma.devisUpdateWithWhereUniqueWithoutUsers_devis_traite_parTousersInput | Prisma.devisUpdateWithWhereUniqueWithoutUsers_devis_traite_parTousersInput[]
  updateMany?: Prisma.devisUpdateManyWithWhereWithoutUsers_devis_traite_parTousersInput | Prisma.devisUpdateManyWithWhereWithoutUsers_devis_traite_parTousersInput[]
  deleteMany?: Prisma.devisScalarWhereInput | Prisma.devisScalarWhereInput[]
}

export type devisUncheckedUpdateManyWithoutUsers_devis_user_idTousersNestedInput = {
  create?: Prisma.XOR<Prisma.devisCreateWithoutUsers_devis_user_idTousersInput, Prisma.devisUncheckedCreateWithoutUsers_devis_user_idTousersInput> | Prisma.devisCreateWithoutUsers_devis_user_idTousersInput[] | Prisma.devisUncheckedCreateWithoutUsers_devis_user_idTousersInput[]
  connectOrCreate?: Prisma.devisCreateOrConnectWithoutUsers_devis_user_idTousersInput | Prisma.devisCreateOrConnectWithoutUsers_devis_user_idTousersInput[]
  upsert?: Prisma.devisUpsertWithWhereUniqueWithoutUsers_devis_user_idTousersInput | Prisma.devisUpsertWithWhereUniqueWithoutUsers_devis_user_idTousersInput[]
  createMany?: Prisma.devisCreateManyUsers_devis_user_idTousersInputEnvelope
  set?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  disconnect?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  delete?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  connect?: Prisma.devisWhereUniqueInput | Prisma.devisWhereUniqueInput[]
  update?: Prisma.devisUpdateWithWhereUniqueWithoutUsers_devis_user_idTousersInput | Prisma.devisUpdateWithWhereUniqueWithoutUsers_devis_user_idTousersInput[]
  updateMany?: Prisma.devisUpdateManyWithWhereWithoutUsers_devis_user_idTousersInput | Prisma.devisUpdateManyWithWhereWithoutUsers_devis_user_idTousersInput[]
  deleteMany?: Prisma.devisScalarWhereInput | Prisma.devisScalarWhereInput[]
}

export type devisCreateWithoutUsers_devis_traite_parTousersInput = {
  id: string
  numero_devis: string
  type_service: $Enums.devis_type
  nom: string
  email: string
  telephone: string
  pays: string
  details: string
  statut?: $Enums.devis_statut | null
  reponse?: string | null
  montant?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  delai?: string | null
  valide_jusque?: Date | string | null
  date_reponse?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  users_devis_user_idTousers?: Prisma.usersCreateNestedOneWithoutDevis_devis_user_idTousersInput
}

export type devisUncheckedCreateWithoutUsers_devis_traite_parTousersInput = {
  id: string
  numero_devis: string
  user_id?: string | null
  type_service: $Enums.devis_type
  nom: string
  email: string
  telephone: string
  pays: string
  details: string
  statut?: $Enums.devis_statut | null
  reponse?: string | null
  montant?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  delai?: string | null
  valide_jusque?: Date | string | null
  date_reponse?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type devisCreateOrConnectWithoutUsers_devis_traite_parTousersInput = {
  where: Prisma.devisWhereUniqueInput
  create: Prisma.XOR<Prisma.devisCreateWithoutUsers_devis_traite_parTousersInput, Prisma.devisUncheckedCreateWithoutUsers_devis_traite_parTousersInput>
}

export type devisCreateManyUsers_devis_traite_parTousersInputEnvelope = {
  data: Prisma.devisCreateManyUsers_devis_traite_parTousersInput | Prisma.devisCreateManyUsers_devis_traite_parTousersInput[]
  skipDuplicates?: boolean
}

export type devisCreateWithoutUsers_devis_user_idTousersInput = {
  id: string
  numero_devis: string
  type_service: $Enums.devis_type
  nom: string
  email: string
  telephone: string
  pays: string
  details: string
  statut?: $Enums.devis_statut | null
  reponse?: string | null
  montant?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  delai?: string | null
  valide_jusque?: Date | string | null
  date_reponse?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  users_devis_traite_parTousers?: Prisma.usersCreateNestedOneWithoutDevis_devis_traite_parTousersInput
}

export type devisUncheckedCreateWithoutUsers_devis_user_idTousersInput = {
  id: string
  numero_devis: string
  type_service: $Enums.devis_type
  nom: string
  email: string
  telephone: string
  pays: string
  details: string
  statut?: $Enums.devis_statut | null
  reponse?: string | null
  montant?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  delai?: string | null
  valide_jusque?: Date | string | null
  date_reponse?: Date | string | null
  traite_par?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type devisCreateOrConnectWithoutUsers_devis_user_idTousersInput = {
  where: Prisma.devisWhereUniqueInput
  create: Prisma.XOR<Prisma.devisCreateWithoutUsers_devis_user_idTousersInput, Prisma.devisUncheckedCreateWithoutUsers_devis_user_idTousersInput>
}

export type devisCreateManyUsers_devis_user_idTousersInputEnvelope = {
  data: Prisma.devisCreateManyUsers_devis_user_idTousersInput | Prisma.devisCreateManyUsers_devis_user_idTousersInput[]
  skipDuplicates?: boolean
}

export type devisUpsertWithWhereUniqueWithoutUsers_devis_traite_parTousersInput = {
  where: Prisma.devisWhereUniqueInput
  update: Prisma.XOR<Prisma.devisUpdateWithoutUsers_devis_traite_parTousersInput, Prisma.devisUncheckedUpdateWithoutUsers_devis_traite_parTousersInput>
  create: Prisma.XOR<Prisma.devisCreateWithoutUsers_devis_traite_parTousersInput, Prisma.devisUncheckedCreateWithoutUsers_devis_traite_parTousersInput>
}

export type devisUpdateWithWhereUniqueWithoutUsers_devis_traite_parTousersInput = {
  where: Prisma.devisWhereUniqueInput
  data: Prisma.XOR<Prisma.devisUpdateWithoutUsers_devis_traite_parTousersInput, Prisma.devisUncheckedUpdateWithoutUsers_devis_traite_parTousersInput>
}

export type devisUpdateManyWithWhereWithoutUsers_devis_traite_parTousersInput = {
  where: Prisma.devisScalarWhereInput
  data: Prisma.XOR<Prisma.devisUpdateManyMutationInput, Prisma.devisUncheckedUpdateManyWithoutUsers_devis_traite_parTousersInput>
}

export type devisScalarWhereInput = {
  AND?: Prisma.devisScalarWhereInput | Prisma.devisScalarWhereInput[]
  OR?: Prisma.devisScalarWhereInput[]
  NOT?: Prisma.devisScalarWhereInput | Prisma.devisScalarWhereInput[]
  id?: Prisma.StringFilter<"devis"> | string
  numero_devis?: Prisma.StringFilter<"devis"> | string
  user_id?: Prisma.StringNullableFilter<"devis"> | string | null
  type_service?: Prisma.Enumdevis_typeFilter<"devis"> | $Enums.devis_type
  nom?: Prisma.StringFilter<"devis"> | string
  email?: Prisma.StringFilter<"devis"> | string
  telephone?: Prisma.StringFilter<"devis"> | string
  pays?: Prisma.StringFilter<"devis"> | string
  details?: Prisma.StringFilter<"devis"> | string
  statut?: Prisma.Enumdevis_statutNullableFilter<"devis"> | $Enums.devis_statut | null
  reponse?: Prisma.StringNullableFilter<"devis"> | string | null
  montant?: Prisma.DecimalNullableFilter<"devis"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.StringNullableFilter<"devis"> | string | null
  delai?: Prisma.StringNullableFilter<"devis"> | string | null
  valide_jusque?: Prisma.DateTimeNullableFilter<"devis"> | Date | string | null
  date_reponse?: Prisma.DateTimeNullableFilter<"devis"> | Date | string | null
  traite_par?: Prisma.StringNullableFilter<"devis"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"devis"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"devis"> | Date | string | null
}

export type devisUpsertWithWhereUniqueWithoutUsers_devis_user_idTousersInput = {
  where: Prisma.devisWhereUniqueInput
  update: Prisma.XOR<Prisma.devisUpdateWithoutUsers_devis_user_idTousersInput, Prisma.devisUncheckedUpdateWithoutUsers_devis_user_idTousersInput>
  create: Prisma.XOR<Prisma.devisCreateWithoutUsers_devis_user_idTousersInput, Prisma.devisUncheckedCreateWithoutUsers_devis_user_idTousersInput>
}

export type devisUpdateWithWhereUniqueWithoutUsers_devis_user_idTousersInput = {
  where: Prisma.devisWhereUniqueInput
  data: Prisma.XOR<Prisma.devisUpdateWithoutUsers_devis_user_idTousersInput, Prisma.devisUncheckedUpdateWithoutUsers_devis_user_idTousersInput>
}

export type devisUpdateManyWithWhereWithoutUsers_devis_user_idTousersInput = {
  where: Prisma.devisScalarWhereInput
  data: Prisma.XOR<Prisma.devisUpdateManyMutationInput, Prisma.devisUncheckedUpdateManyWithoutUsers_devis_user_idTousersInput>
}

export type devisCreateManyUsers_devis_traite_parTousersInput = {
  id: string
  numero_devis: string
  user_id?: string | null
  type_service: $Enums.devis_type
  nom: string
  email: string
  telephone: string
  pays: string
  details: string
  statut?: $Enums.devis_statut | null
  reponse?: string | null
  montant?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  delai?: string | null
  valide_jusque?: Date | string | null
  date_reponse?: Date | string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type devisCreateManyUsers_devis_user_idTousersInput = {
  id: string
  numero_devis: string
  type_service: $Enums.devis_type
  nom: string
  email: string
  telephone: string
  pays: string
  details: string
  statut?: $Enums.devis_statut | null
  reponse?: string | null
  montant?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  delai?: string | null
  valide_jusque?: Date | string | null
  date_reponse?: Date | string | null
  traite_par?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type devisUpdateWithoutUsers_devis_traite_parTousersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero_devis?: Prisma.StringFieldUpdateOperationsInput | string
  type_service?: Prisma.Enumdevis_typeFieldUpdateOperationsInput | $Enums.devis_type
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  telephone?: Prisma.StringFieldUpdateOperationsInput | string
  pays?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  statut?: Prisma.NullableEnumdevis_statutFieldUpdateOperationsInput | $Enums.devis_statut | null
  reponse?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  montant?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delai?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valide_jusque?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  date_reponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users_devis_user_idTousers?: Prisma.usersUpdateOneWithoutDevis_devis_user_idTousersNestedInput
}

export type devisUncheckedUpdateWithoutUsers_devis_traite_parTousersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero_devis?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type_service?: Prisma.Enumdevis_typeFieldUpdateOperationsInput | $Enums.devis_type
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  telephone?: Prisma.StringFieldUpdateOperationsInput | string
  pays?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  statut?: Prisma.NullableEnumdevis_statutFieldUpdateOperationsInput | $Enums.devis_statut | null
  reponse?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  montant?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delai?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valide_jusque?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  date_reponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type devisUncheckedUpdateManyWithoutUsers_devis_traite_parTousersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero_devis?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type_service?: Prisma.Enumdevis_typeFieldUpdateOperationsInput | $Enums.devis_type
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  telephone?: Prisma.StringFieldUpdateOperationsInput | string
  pays?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  statut?: Prisma.NullableEnumdevis_statutFieldUpdateOperationsInput | $Enums.devis_statut | null
  reponse?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  montant?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delai?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valide_jusque?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  date_reponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type devisUpdateWithoutUsers_devis_user_idTousersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero_devis?: Prisma.StringFieldUpdateOperationsInput | string
  type_service?: Prisma.Enumdevis_typeFieldUpdateOperationsInput | $Enums.devis_type
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  telephone?: Prisma.StringFieldUpdateOperationsInput | string
  pays?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  statut?: Prisma.NullableEnumdevis_statutFieldUpdateOperationsInput | $Enums.devis_statut | null
  reponse?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  montant?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delai?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valide_jusque?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  date_reponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users_devis_traite_parTousers?: Prisma.usersUpdateOneWithoutDevis_devis_traite_parTousersNestedInput
}

export type devisUncheckedUpdateWithoutUsers_devis_user_idTousersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero_devis?: Prisma.StringFieldUpdateOperationsInput | string
  type_service?: Prisma.Enumdevis_typeFieldUpdateOperationsInput | $Enums.devis_type
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  telephone?: Prisma.StringFieldUpdateOperationsInput | string
  pays?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  statut?: Prisma.NullableEnumdevis_statutFieldUpdateOperationsInput | $Enums.devis_statut | null
  reponse?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  montant?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delai?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valide_jusque?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  date_reponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  traite_par?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type devisUncheckedUpdateManyWithoutUsers_devis_user_idTousersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero_devis?: Prisma.StringFieldUpdateOperationsInput | string
  type_service?: Prisma.Enumdevis_typeFieldUpdateOperationsInput | $Enums.devis_type
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  telephone?: Prisma.StringFieldUpdateOperationsInput | string
  pays?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  statut?: Prisma.NullableEnumdevis_statutFieldUpdateOperationsInput | $Enums.devis_statut | null
  reponse?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  montant?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delai?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valide_jusque?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  date_reponse?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  traite_par?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type devisSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  numero_devis?: boolean
  user_id?: boolean
  type_service?: boolean
  nom?: boolean
  email?: boolean
  telephone?: boolean
  pays?: boolean
  details?: boolean
  statut?: boolean
  reponse?: boolean
  montant?: boolean
  devise?: boolean
  delai?: boolean
  valide_jusque?: boolean
  date_reponse?: boolean
  traite_par?: boolean
  created_at?: boolean
  updated_at?: boolean
  users_devis_traite_parTousers?: boolean | Prisma.devis$users_devis_traite_parTousersArgs<ExtArgs>
  users_devis_user_idTousers?: boolean | Prisma.devis$users_devis_user_idTousersArgs<ExtArgs>
}, ExtArgs["result"]["devis"]>

export type devisSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  numero_devis?: boolean
  user_id?: boolean
  type_service?: boolean
  nom?: boolean
  email?: boolean
  telephone?: boolean
  pays?: boolean
  details?: boolean
  statut?: boolean
  reponse?: boolean
  montant?: boolean
  devise?: boolean
  delai?: boolean
  valide_jusque?: boolean
  date_reponse?: boolean
  traite_par?: boolean
  created_at?: boolean
  updated_at?: boolean
  users_devis_traite_parTousers?: boolean | Prisma.devis$users_devis_traite_parTousersArgs<ExtArgs>
  users_devis_user_idTousers?: boolean | Prisma.devis$users_devis_user_idTousersArgs<ExtArgs>
}, ExtArgs["result"]["devis"]>

export type devisSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  numero_devis?: boolean
  user_id?: boolean
  type_service?: boolean
  nom?: boolean
  email?: boolean
  telephone?: boolean
  pays?: boolean
  details?: boolean
  statut?: boolean
  reponse?: boolean
  montant?: boolean
  devise?: boolean
  delai?: boolean
  valide_jusque?: boolean
  date_reponse?: boolean
  traite_par?: boolean
  created_at?: boolean
  updated_at?: boolean
  users_devis_traite_parTousers?: boolean | Prisma.devis$users_devis_traite_parTousersArgs<ExtArgs>
  users_devis_user_idTousers?: boolean | Prisma.devis$users_devis_user_idTousersArgs<ExtArgs>
}, ExtArgs["result"]["devis"]>

export type devisSelectScalar = {
  id?: boolean
  numero_devis?: boolean
  user_id?: boolean
  type_service?: boolean
  nom?: boolean
  email?: boolean
  telephone?: boolean
  pays?: boolean
  details?: boolean
  statut?: boolean
  reponse?: boolean
  montant?: boolean
  devise?: boolean
  delai?: boolean
  valide_jusque?: boolean
  date_reponse?: boolean
  traite_par?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type devisOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "numero_devis" | "user_id" | "type_service" | "nom" | "email" | "telephone" | "pays" | "details" | "statut" | "reponse" | "montant" | "devise" | "delai" | "valide_jusque" | "date_reponse" | "traite_par" | "created_at" | "updated_at", ExtArgs["result"]["devis"]>
export type devisInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users_devis_traite_parTousers?: boolean | Prisma.devis$users_devis_traite_parTousersArgs<ExtArgs>
  users_devis_user_idTousers?: boolean | Prisma.devis$users_devis_user_idTousersArgs<ExtArgs>
}
export type devisIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users_devis_traite_parTousers?: boolean | Prisma.devis$users_devis_traite_parTousersArgs<ExtArgs>
  users_devis_user_idTousers?: boolean | Prisma.devis$users_devis_user_idTousersArgs<ExtArgs>
}
export type devisIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users_devis_traite_parTousers?: boolean | Prisma.devis$users_devis_traite_parTousersArgs<ExtArgs>
  users_devis_user_idTousers?: boolean | Prisma.devis$users_devis_user_idTousersArgs<ExtArgs>
}

export type $devisPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "devis"
  objects: {
    users_devis_traite_parTousers: Prisma.$usersPayload<ExtArgs> | null
    users_devis_user_idTousers: Prisma.$usersPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    numero_devis: string
    user_id: string | null
    type_service: $Enums.devis_type
    nom: string
    email: string
    telephone: string
    pays: string
    details: string
    statut: $Enums.devis_statut | null
    reponse: string | null
    montant: runtime.Decimal | null
    devise: string | null
    delai: string | null
    valide_jusque: Date | null
    date_reponse: Date | null
    traite_par: string | null
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["devis"]>
  composites: {}
}

export type devisGetPayload<S extends boolean | null | undefined | devisDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$devisPayload, S>

export type devisCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<devisFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DevisCountAggregateInputType | true
  }

export interface devisDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['devis'], meta: { name: 'devis' } }
  /**
   * Find zero or one Devis that matches the filter.
   * @param {devisFindUniqueArgs} args - Arguments to find a Devis
   * @example
   * // Get one Devis
   * const devis = await prisma.devis.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends devisFindUniqueArgs>(args: Prisma.SelectSubset<T, devisFindUniqueArgs<ExtArgs>>): Prisma.Prisma__devisClient<runtime.Types.Result.GetResult<Prisma.$devisPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Devis that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {devisFindUniqueOrThrowArgs} args - Arguments to find a Devis
   * @example
   * // Get one Devis
   * const devis = await prisma.devis.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends devisFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, devisFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__devisClient<runtime.Types.Result.GetResult<Prisma.$devisPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Devis that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {devisFindFirstArgs} args - Arguments to find a Devis
   * @example
   * // Get one Devis
   * const devis = await prisma.devis.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends devisFindFirstArgs>(args?: Prisma.SelectSubset<T, devisFindFirstArgs<ExtArgs>>): Prisma.Prisma__devisClient<runtime.Types.Result.GetResult<Prisma.$devisPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Devis that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {devisFindFirstOrThrowArgs} args - Arguments to find a Devis
   * @example
   * // Get one Devis
   * const devis = await prisma.devis.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends devisFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, devisFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__devisClient<runtime.Types.Result.GetResult<Prisma.$devisPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Devis that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {devisFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Devis
   * const devis = await prisma.devis.findMany()
   * 
   * // Get first 10 Devis
   * const devis = await prisma.devis.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const devisWithIdOnly = await prisma.devis.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends devisFindManyArgs>(args?: Prisma.SelectSubset<T, devisFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$devisPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Devis.
   * @param {devisCreateArgs} args - Arguments to create a Devis.
   * @example
   * // Create one Devis
   * const Devis = await prisma.devis.create({
   *   data: {
   *     // ... data to create a Devis
   *   }
   * })
   * 
   */
  create<T extends devisCreateArgs>(args: Prisma.SelectSubset<T, devisCreateArgs<ExtArgs>>): Prisma.Prisma__devisClient<runtime.Types.Result.GetResult<Prisma.$devisPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Devis.
   * @param {devisCreateManyArgs} args - Arguments to create many Devis.
   * @example
   * // Create many Devis
   * const devis = await prisma.devis.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends devisCreateManyArgs>(args?: Prisma.SelectSubset<T, devisCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Devis and returns the data saved in the database.
   * @param {devisCreateManyAndReturnArgs} args - Arguments to create many Devis.
   * @example
   * // Create many Devis
   * const devis = await prisma.devis.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Devis and only return the `id`
   * const devisWithIdOnly = await prisma.devis.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends devisCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, devisCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$devisPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Devis.
   * @param {devisDeleteArgs} args - Arguments to delete one Devis.
   * @example
   * // Delete one Devis
   * const Devis = await prisma.devis.delete({
   *   where: {
   *     // ... filter to delete one Devis
   *   }
   * })
   * 
   */
  delete<T extends devisDeleteArgs>(args: Prisma.SelectSubset<T, devisDeleteArgs<ExtArgs>>): Prisma.Prisma__devisClient<runtime.Types.Result.GetResult<Prisma.$devisPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Devis.
   * @param {devisUpdateArgs} args - Arguments to update one Devis.
   * @example
   * // Update one Devis
   * const devis = await prisma.devis.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends devisUpdateArgs>(args: Prisma.SelectSubset<T, devisUpdateArgs<ExtArgs>>): Prisma.Prisma__devisClient<runtime.Types.Result.GetResult<Prisma.$devisPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Devis.
   * @param {devisDeleteManyArgs} args - Arguments to filter Devis to delete.
   * @example
   * // Delete a few Devis
   * const { count } = await prisma.devis.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends devisDeleteManyArgs>(args?: Prisma.SelectSubset<T, devisDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Devis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {devisUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Devis
   * const devis = await prisma.devis.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends devisUpdateManyArgs>(args: Prisma.SelectSubset<T, devisUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Devis and returns the data updated in the database.
   * @param {devisUpdateManyAndReturnArgs} args - Arguments to update many Devis.
   * @example
   * // Update many Devis
   * const devis = await prisma.devis.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Devis and only return the `id`
   * const devisWithIdOnly = await prisma.devis.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends devisUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, devisUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$devisPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Devis.
   * @param {devisUpsertArgs} args - Arguments to update or create a Devis.
   * @example
   * // Update or create a Devis
   * const devis = await prisma.devis.upsert({
   *   create: {
   *     // ... data to create a Devis
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Devis we want to update
   *   }
   * })
   */
  upsert<T extends devisUpsertArgs>(args: Prisma.SelectSubset<T, devisUpsertArgs<ExtArgs>>): Prisma.Prisma__devisClient<runtime.Types.Result.GetResult<Prisma.$devisPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Devis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {devisCountArgs} args - Arguments to filter Devis to count.
   * @example
   * // Count the number of Devis
   * const count = await prisma.devis.count({
   *   where: {
   *     // ... the filter for the Devis we want to count
   *   }
   * })
  **/
  count<T extends devisCountArgs>(
    args?: Prisma.Subset<T, devisCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DevisCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Devis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DevisAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DevisAggregateArgs>(args: Prisma.Subset<T, DevisAggregateArgs>): Prisma.PrismaPromise<GetDevisAggregateType<T>>

  /**
   * Group by Devis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {devisGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends devisGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: devisGroupByArgs['orderBy'] }
      : { orderBy?: devisGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, devisGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDevisGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the devis model
 */
readonly fields: devisFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for devis.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__devisClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users_devis_traite_parTousers<T extends Prisma.devis$users_devis_traite_parTousersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.devis$users_devis_traite_parTousersArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  users_devis_user_idTousers<T extends Prisma.devis$users_devis_user_idTousersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.devis$users_devis_user_idTousersArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the devis model
 */
export interface devisFieldRefs {
  readonly id: Prisma.FieldRef<"devis", 'String'>
  readonly numero_devis: Prisma.FieldRef<"devis", 'String'>
  readonly user_id: Prisma.FieldRef<"devis", 'String'>
  readonly type_service: Prisma.FieldRef<"devis", 'devis_type'>
  readonly nom: Prisma.FieldRef<"devis", 'String'>
  readonly email: Prisma.FieldRef<"devis", 'String'>
  readonly telephone: Prisma.FieldRef<"devis", 'String'>
  readonly pays: Prisma.FieldRef<"devis", 'String'>
  readonly details: Prisma.FieldRef<"devis", 'String'>
  readonly statut: Prisma.FieldRef<"devis", 'devis_statut'>
  readonly reponse: Prisma.FieldRef<"devis", 'String'>
  readonly montant: Prisma.FieldRef<"devis", 'Decimal'>
  readonly devise: Prisma.FieldRef<"devis", 'String'>
  readonly delai: Prisma.FieldRef<"devis", 'String'>
  readonly valide_jusque: Prisma.FieldRef<"devis", 'DateTime'>
  readonly date_reponse: Prisma.FieldRef<"devis", 'DateTime'>
  readonly traite_par: Prisma.FieldRef<"devis", 'String'>
  readonly created_at: Prisma.FieldRef<"devis", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"devis", 'DateTime'>
}
    

// Custom InputTypes
/**
 * devis findUnique
 */
export type devisFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the devis
   */
  select?: Prisma.devisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the devis
   */
  omit?: Prisma.devisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.devisInclude<ExtArgs> | null
  /**
   * Filter, which devis to fetch.
   */
  where: Prisma.devisWhereUniqueInput
}

/**
 * devis findUniqueOrThrow
 */
export type devisFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the devis
   */
  select?: Prisma.devisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the devis
   */
  omit?: Prisma.devisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.devisInclude<ExtArgs> | null
  /**
   * Filter, which devis to fetch.
   */
  where: Prisma.devisWhereUniqueInput
}

/**
 * devis findFirst
 */
export type devisFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the devis
   */
  select?: Prisma.devisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the devis
   */
  omit?: Prisma.devisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.devisInclude<ExtArgs> | null
  /**
   * Filter, which devis to fetch.
   */
  where?: Prisma.devisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of devis to fetch.
   */
  orderBy?: Prisma.devisOrderByWithRelationInput | Prisma.devisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for devis.
   */
  cursor?: Prisma.devisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` devis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` devis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of devis.
   */
  distinct?: Prisma.DevisScalarFieldEnum | Prisma.DevisScalarFieldEnum[]
}

/**
 * devis findFirstOrThrow
 */
export type devisFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the devis
   */
  select?: Prisma.devisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the devis
   */
  omit?: Prisma.devisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.devisInclude<ExtArgs> | null
  /**
   * Filter, which devis to fetch.
   */
  where?: Prisma.devisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of devis to fetch.
   */
  orderBy?: Prisma.devisOrderByWithRelationInput | Prisma.devisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for devis.
   */
  cursor?: Prisma.devisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` devis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` devis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of devis.
   */
  distinct?: Prisma.DevisScalarFieldEnum | Prisma.DevisScalarFieldEnum[]
}

/**
 * devis findMany
 */
export type devisFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the devis
   */
  select?: Prisma.devisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the devis
   */
  omit?: Prisma.devisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.devisInclude<ExtArgs> | null
  /**
   * Filter, which devis to fetch.
   */
  where?: Prisma.devisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of devis to fetch.
   */
  orderBy?: Prisma.devisOrderByWithRelationInput | Prisma.devisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing devis.
   */
  cursor?: Prisma.devisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` devis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` devis.
   */
  skip?: number
  distinct?: Prisma.DevisScalarFieldEnum | Prisma.DevisScalarFieldEnum[]
}

/**
 * devis create
 */
export type devisCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the devis
   */
  select?: Prisma.devisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the devis
   */
  omit?: Prisma.devisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.devisInclude<ExtArgs> | null
  /**
   * The data needed to create a devis.
   */
  data: Prisma.XOR<Prisma.devisCreateInput, Prisma.devisUncheckedCreateInput>
}

/**
 * devis createMany
 */
export type devisCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many devis.
   */
  data: Prisma.devisCreateManyInput | Prisma.devisCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * devis createManyAndReturn
 */
export type devisCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the devis
   */
  select?: Prisma.devisSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the devis
   */
  omit?: Prisma.devisOmit<ExtArgs> | null
  /**
   * The data used to create many devis.
   */
  data: Prisma.devisCreateManyInput | Prisma.devisCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.devisIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * devis update
 */
export type devisUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the devis
   */
  select?: Prisma.devisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the devis
   */
  omit?: Prisma.devisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.devisInclude<ExtArgs> | null
  /**
   * The data needed to update a devis.
   */
  data: Prisma.XOR<Prisma.devisUpdateInput, Prisma.devisUncheckedUpdateInput>
  /**
   * Choose, which devis to update.
   */
  where: Prisma.devisWhereUniqueInput
}

/**
 * devis updateMany
 */
export type devisUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update devis.
   */
  data: Prisma.XOR<Prisma.devisUpdateManyMutationInput, Prisma.devisUncheckedUpdateManyInput>
  /**
   * Filter which devis to update
   */
  where?: Prisma.devisWhereInput
  /**
   * Limit how many devis to update.
   */
  limit?: number
}

/**
 * devis updateManyAndReturn
 */
export type devisUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the devis
   */
  select?: Prisma.devisSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the devis
   */
  omit?: Prisma.devisOmit<ExtArgs> | null
  /**
   * The data used to update devis.
   */
  data: Prisma.XOR<Prisma.devisUpdateManyMutationInput, Prisma.devisUncheckedUpdateManyInput>
  /**
   * Filter which devis to update
   */
  where?: Prisma.devisWhereInput
  /**
   * Limit how many devis to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.devisIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * devis upsert
 */
export type devisUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the devis
   */
  select?: Prisma.devisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the devis
   */
  omit?: Prisma.devisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.devisInclude<ExtArgs> | null
  /**
   * The filter to search for the devis to update in case it exists.
   */
  where: Prisma.devisWhereUniqueInput
  /**
   * In case the devis found by the `where` argument doesn't exist, create a new devis with this data.
   */
  create: Prisma.XOR<Prisma.devisCreateInput, Prisma.devisUncheckedCreateInput>
  /**
   * In case the devis was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.devisUpdateInput, Prisma.devisUncheckedUpdateInput>
}

/**
 * devis delete
 */
export type devisDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the devis
   */
  select?: Prisma.devisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the devis
   */
  omit?: Prisma.devisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.devisInclude<ExtArgs> | null
  /**
   * Filter which devis to delete.
   */
  where: Prisma.devisWhereUniqueInput
}

/**
 * devis deleteMany
 */
export type devisDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which devis to delete
   */
  where?: Prisma.devisWhereInput
  /**
   * Limit how many devis to delete.
   */
  limit?: number
}

/**
 * devis.users_devis_traite_parTousers
 */
export type devis$users_devis_traite_parTousersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
}

/**
 * devis.users_devis_user_idTousers
 */
export type devis$users_devis_user_idTousersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
}

/**
 * devis without action
 */
export type devisDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the devis
   */
  select?: Prisma.devisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the devis
   */
  omit?: Prisma.devisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.devisInclude<ExtArgs> | null
}
