
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `formules_accompagnement` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model formules_accompagnement
 * 
 */
export type formules_accompagnementModel = runtime.Types.Result.DefaultSelection<Prisma.$formules_accompagnementPayload>

export type AggregateFormules_accompagnement = {
  _count: Formules_accompagnementCountAggregateOutputType | null
  _avg: Formules_accompagnementAvgAggregateOutputType | null
  _sum: Formules_accompagnementSumAggregateOutputType | null
  _min: Formules_accompagnementMinAggregateOutputType | null
  _max: Formules_accompagnementMaxAggregateOutputType | null
}

export type Formules_accompagnementAvgAggregateOutputType = {
  prix: runtime.Decimal | null
  ordre: number | null
}

export type Formules_accompagnementSumAggregateOutputType = {
  prix: runtime.Decimal | null
  ordre: number | null
}

export type Formules_accompagnementMinAggregateOutputType = {
  id: string | null
  nom: string | null
  slug: string | null
  description: string | null
  prix: runtime.Decimal | null
  devise: string | null
  duree: string | null
  ordre: number | null
  actif: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type Formules_accompagnementMaxAggregateOutputType = {
  id: string | null
  nom: string | null
  slug: string | null
  description: string | null
  prix: runtime.Decimal | null
  devise: string | null
  duree: string | null
  ordre: number | null
  actif: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type Formules_accompagnementCountAggregateOutputType = {
  id: number
  nom: number
  slug: number
  description: number
  services_inclus: number
  prix: number
  devise: number
  duree: number
  ordre: number
  actif: number
  created_at: number
  updated_at: number
  _all: number
}


export type Formules_accompagnementAvgAggregateInputType = {
  prix?: true
  ordre?: true
}

export type Formules_accompagnementSumAggregateInputType = {
  prix?: true
  ordre?: true
}

export type Formules_accompagnementMinAggregateInputType = {
  id?: true
  nom?: true
  slug?: true
  description?: true
  prix?: true
  devise?: true
  duree?: true
  ordre?: true
  actif?: true
  created_at?: true
  updated_at?: true
}

export type Formules_accompagnementMaxAggregateInputType = {
  id?: true
  nom?: true
  slug?: true
  description?: true
  prix?: true
  devise?: true
  duree?: true
  ordre?: true
  actif?: true
  created_at?: true
  updated_at?: true
}

export type Formules_accompagnementCountAggregateInputType = {
  id?: true
  nom?: true
  slug?: true
  description?: true
  services_inclus?: true
  prix?: true
  devise?: true
  duree?: true
  ordre?: true
  actif?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Formules_accompagnementAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which formules_accompagnement to aggregate.
   */
  where?: Prisma.formules_accompagnementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of formules_accompagnements to fetch.
   */
  orderBy?: Prisma.formules_accompagnementOrderByWithRelationInput | Prisma.formules_accompagnementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.formules_accompagnementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` formules_accompagnements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` formules_accompagnements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned formules_accompagnements
  **/
  _count?: true | Formules_accompagnementCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Formules_accompagnementAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Formules_accompagnementSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Formules_accompagnementMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Formules_accompagnementMaxAggregateInputType
}

export type GetFormules_accompagnementAggregateType<T extends Formules_accompagnementAggregateArgs> = {
      [P in keyof T & keyof AggregateFormules_accompagnement]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFormules_accompagnement[P]>
    : Prisma.GetScalarType<T[P], AggregateFormules_accompagnement[P]>
}




export type formules_accompagnementGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.formules_accompagnementWhereInput
  orderBy?: Prisma.formules_accompagnementOrderByWithAggregationInput | Prisma.formules_accompagnementOrderByWithAggregationInput[]
  by: Prisma.Formules_accompagnementScalarFieldEnum[] | Prisma.Formules_accompagnementScalarFieldEnum
  having?: Prisma.formules_accompagnementScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Formules_accompagnementCountAggregateInputType | true
  _avg?: Formules_accompagnementAvgAggregateInputType
  _sum?: Formules_accompagnementSumAggregateInputType
  _min?: Formules_accompagnementMinAggregateInputType
  _max?: Formules_accompagnementMaxAggregateInputType
}

export type Formules_accompagnementGroupByOutputType = {
  id: string
  nom: string
  slug: string
  description: string | null
  services_inclus: runtime.JsonValue | null
  prix: runtime.Decimal | null
  devise: string | null
  duree: string | null
  ordre: number | null
  actif: boolean | null
  created_at: Date | null
  updated_at: Date | null
  _count: Formules_accompagnementCountAggregateOutputType | null
  _avg: Formules_accompagnementAvgAggregateOutputType | null
  _sum: Formules_accompagnementSumAggregateOutputType | null
  _min: Formules_accompagnementMinAggregateOutputType | null
  _max: Formules_accompagnementMaxAggregateOutputType | null
}

type GetFormules_accompagnementGroupByPayload<T extends formules_accompagnementGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Formules_accompagnementGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Formules_accompagnementGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Formules_accompagnementGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Formules_accompagnementGroupByOutputType[P]>
      }
    >
  >



export type formules_accompagnementWhereInput = {
  AND?: Prisma.formules_accompagnementWhereInput | Prisma.formules_accompagnementWhereInput[]
  OR?: Prisma.formules_accompagnementWhereInput[]
  NOT?: Prisma.formules_accompagnementWhereInput | Prisma.formules_accompagnementWhereInput[]
  id?: Prisma.StringFilter<"formules_accompagnement"> | string
  nom?: Prisma.StringFilter<"formules_accompagnement"> | string
  slug?: Prisma.StringFilter<"formules_accompagnement"> | string
  description?: Prisma.StringNullableFilter<"formules_accompagnement"> | string | null
  services_inclus?: Prisma.JsonNullableFilter<"formules_accompagnement">
  prix?: Prisma.DecimalNullableFilter<"formules_accompagnement"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.StringNullableFilter<"formules_accompagnement"> | string | null
  duree?: Prisma.StringNullableFilter<"formules_accompagnement"> | string | null
  ordre?: Prisma.IntNullableFilter<"formules_accompagnement"> | number | null
  actif?: Prisma.BoolNullableFilter<"formules_accompagnement"> | boolean | null
  created_at?: Prisma.DateTimeNullableFilter<"formules_accompagnement"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"formules_accompagnement"> | Date | string | null
  demandes_accompagnement?: Prisma.Demandes_accompagnementListRelationFilter
}

export type formules_accompagnementOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  services_inclus?: Prisma.SortOrderInput | Prisma.SortOrder
  prix?: Prisma.SortOrderInput | Prisma.SortOrder
  devise?: Prisma.SortOrderInput | Prisma.SortOrder
  duree?: Prisma.SortOrderInput | Prisma.SortOrder
  ordre?: Prisma.SortOrderInput | Prisma.SortOrder
  actif?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  demandes_accompagnement?: Prisma.demandes_accompagnementOrderByRelationAggregateInput
}

export type formules_accompagnementWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.formules_accompagnementWhereInput | Prisma.formules_accompagnementWhereInput[]
  OR?: Prisma.formules_accompagnementWhereInput[]
  NOT?: Prisma.formules_accompagnementWhereInput | Prisma.formules_accompagnementWhereInput[]
  nom?: Prisma.StringFilter<"formules_accompagnement"> | string
  description?: Prisma.StringNullableFilter<"formules_accompagnement"> | string | null
  services_inclus?: Prisma.JsonNullableFilter<"formules_accompagnement">
  prix?: Prisma.DecimalNullableFilter<"formules_accompagnement"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.StringNullableFilter<"formules_accompagnement"> | string | null
  duree?: Prisma.StringNullableFilter<"formules_accompagnement"> | string | null
  ordre?: Prisma.IntNullableFilter<"formules_accompagnement"> | number | null
  actif?: Prisma.BoolNullableFilter<"formules_accompagnement"> | boolean | null
  created_at?: Prisma.DateTimeNullableFilter<"formules_accompagnement"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"formules_accompagnement"> | Date | string | null
  demandes_accompagnement?: Prisma.Demandes_accompagnementListRelationFilter
}, "id" | "slug">

export type formules_accompagnementOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  services_inclus?: Prisma.SortOrderInput | Prisma.SortOrder
  prix?: Prisma.SortOrderInput | Prisma.SortOrder
  devise?: Prisma.SortOrderInput | Prisma.SortOrder
  duree?: Prisma.SortOrderInput | Prisma.SortOrder
  ordre?: Prisma.SortOrderInput | Prisma.SortOrder
  actif?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.formules_accompagnementCountOrderByAggregateInput
  _avg?: Prisma.formules_accompagnementAvgOrderByAggregateInput
  _max?: Prisma.formules_accompagnementMaxOrderByAggregateInput
  _min?: Prisma.formules_accompagnementMinOrderByAggregateInput
  _sum?: Prisma.formules_accompagnementSumOrderByAggregateInput
}

export type formules_accompagnementScalarWhereWithAggregatesInput = {
  AND?: Prisma.formules_accompagnementScalarWhereWithAggregatesInput | Prisma.formules_accompagnementScalarWhereWithAggregatesInput[]
  OR?: Prisma.formules_accompagnementScalarWhereWithAggregatesInput[]
  NOT?: Prisma.formules_accompagnementScalarWhereWithAggregatesInput | Prisma.formules_accompagnementScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"formules_accompagnement"> | string
  nom?: Prisma.StringWithAggregatesFilter<"formules_accompagnement"> | string
  slug?: Prisma.StringWithAggregatesFilter<"formules_accompagnement"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"formules_accompagnement"> | string | null
  services_inclus?: Prisma.JsonNullableWithAggregatesFilter<"formules_accompagnement">
  prix?: Prisma.DecimalNullableWithAggregatesFilter<"formules_accompagnement"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.StringNullableWithAggregatesFilter<"formules_accompagnement"> | string | null
  duree?: Prisma.StringNullableWithAggregatesFilter<"formules_accompagnement"> | string | null
  ordre?: Prisma.IntNullableWithAggregatesFilter<"formules_accompagnement"> | number | null
  actif?: Prisma.BoolNullableWithAggregatesFilter<"formules_accompagnement"> | boolean | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"formules_accompagnement"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"formules_accompagnement"> | Date | string | null
}

export type formules_accompagnementCreateInput = {
  id: string
  nom: string
  slug: string
  description?: string | null
  services_inclus?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prix?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  duree?: string | null
  ordre?: number | null
  actif?: boolean | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  demandes_accompagnement?: Prisma.demandes_accompagnementCreateNestedManyWithoutFormules_accompagnementInput
}

export type formules_accompagnementUncheckedCreateInput = {
  id: string
  nom: string
  slug: string
  description?: string | null
  services_inclus?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prix?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  duree?: string | null
  ordre?: number | null
  actif?: boolean | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  demandes_accompagnement?: Prisma.demandes_accompagnementUncheckedCreateNestedManyWithoutFormules_accompagnementInput
}

export type formules_accompagnementUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  services_inclus?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prix?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duree?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  actif?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  demandes_accompagnement?: Prisma.demandes_accompagnementUpdateManyWithoutFormules_accompagnementNestedInput
}

export type formules_accompagnementUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  services_inclus?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prix?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duree?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  actif?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  demandes_accompagnement?: Prisma.demandes_accompagnementUncheckedUpdateManyWithoutFormules_accompagnementNestedInput
}

export type formules_accompagnementCreateManyInput = {
  id: string
  nom: string
  slug: string
  description?: string | null
  services_inclus?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prix?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  duree?: string | null
  ordre?: number | null
  actif?: boolean | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type formules_accompagnementUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  services_inclus?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prix?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duree?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  actif?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type formules_accompagnementUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  services_inclus?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prix?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duree?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  actif?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type Formules_accompagnementNullableScalarRelationFilter = {
  is?: Prisma.formules_accompagnementWhereInput | null
  isNot?: Prisma.formules_accompagnementWhereInput | null
}

export type formules_accompagnementCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  services_inclus?: Prisma.SortOrder
  prix?: Prisma.SortOrder
  devise?: Prisma.SortOrder
  duree?: Prisma.SortOrder
  ordre?: Prisma.SortOrder
  actif?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type formules_accompagnementAvgOrderByAggregateInput = {
  prix?: Prisma.SortOrder
  ordre?: Prisma.SortOrder
}

export type formules_accompagnementMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  prix?: Prisma.SortOrder
  devise?: Prisma.SortOrder
  duree?: Prisma.SortOrder
  ordre?: Prisma.SortOrder
  actif?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type formules_accompagnementMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  prix?: Prisma.SortOrder
  devise?: Prisma.SortOrder
  duree?: Prisma.SortOrder
  ordre?: Prisma.SortOrder
  actif?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type formules_accompagnementSumOrderByAggregateInput = {
  prix?: Prisma.SortOrder
  ordre?: Prisma.SortOrder
}

export type formules_accompagnementCreateNestedOneWithoutDemandes_accompagnementInput = {
  create?: Prisma.XOR<Prisma.formules_accompagnementCreateWithoutDemandes_accompagnementInput, Prisma.formules_accompagnementUncheckedCreateWithoutDemandes_accompagnementInput>
  connectOrCreate?: Prisma.formules_accompagnementCreateOrConnectWithoutDemandes_accompagnementInput
  connect?: Prisma.formules_accompagnementWhereUniqueInput
}

export type formules_accompagnementUpdateOneWithoutDemandes_accompagnementNestedInput = {
  create?: Prisma.XOR<Prisma.formules_accompagnementCreateWithoutDemandes_accompagnementInput, Prisma.formules_accompagnementUncheckedCreateWithoutDemandes_accompagnementInput>
  connectOrCreate?: Prisma.formules_accompagnementCreateOrConnectWithoutDemandes_accompagnementInput
  upsert?: Prisma.formules_accompagnementUpsertWithoutDemandes_accompagnementInput
  disconnect?: Prisma.formules_accompagnementWhereInput | boolean
  delete?: Prisma.formules_accompagnementWhereInput | boolean
  connect?: Prisma.formules_accompagnementWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.formules_accompagnementUpdateToOneWithWhereWithoutDemandes_accompagnementInput, Prisma.formules_accompagnementUpdateWithoutDemandes_accompagnementInput>, Prisma.formules_accompagnementUncheckedUpdateWithoutDemandes_accompagnementInput>
}

export type formules_accompagnementCreateWithoutDemandes_accompagnementInput = {
  id: string
  nom: string
  slug: string
  description?: string | null
  services_inclus?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prix?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  duree?: string | null
  ordre?: number | null
  actif?: boolean | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type formules_accompagnementUncheckedCreateWithoutDemandes_accompagnementInput = {
  id: string
  nom: string
  slug: string
  description?: string | null
  services_inclus?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prix?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: string | null
  duree?: string | null
  ordre?: number | null
  actif?: boolean | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type formules_accompagnementCreateOrConnectWithoutDemandes_accompagnementInput = {
  where: Prisma.formules_accompagnementWhereUniqueInput
  create: Prisma.XOR<Prisma.formules_accompagnementCreateWithoutDemandes_accompagnementInput, Prisma.formules_accompagnementUncheckedCreateWithoutDemandes_accompagnementInput>
}

export type formules_accompagnementUpsertWithoutDemandes_accompagnementInput = {
  update: Prisma.XOR<Prisma.formules_accompagnementUpdateWithoutDemandes_accompagnementInput, Prisma.formules_accompagnementUncheckedUpdateWithoutDemandes_accompagnementInput>
  create: Prisma.XOR<Prisma.formules_accompagnementCreateWithoutDemandes_accompagnementInput, Prisma.formules_accompagnementUncheckedCreateWithoutDemandes_accompagnementInput>
  where?: Prisma.formules_accompagnementWhereInput
}

export type formules_accompagnementUpdateToOneWithWhereWithoutDemandes_accompagnementInput = {
  where?: Prisma.formules_accompagnementWhereInput
  data: Prisma.XOR<Prisma.formules_accompagnementUpdateWithoutDemandes_accompagnementInput, Prisma.formules_accompagnementUncheckedUpdateWithoutDemandes_accompagnementInput>
}

export type formules_accompagnementUpdateWithoutDemandes_accompagnementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  services_inclus?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prix?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duree?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  actif?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type formules_accompagnementUncheckedUpdateWithoutDemandes_accompagnementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  services_inclus?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prix?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duree?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  actif?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type Formules_accompagnementCountOutputType
 */

export type Formules_accompagnementCountOutputType = {
  demandes_accompagnement: number
}

export type Formules_accompagnementCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  demandes_accompagnement?: boolean | Formules_accompagnementCountOutputTypeCountDemandes_accompagnementArgs
}

/**
 * Formules_accompagnementCountOutputType without action
 */
export type Formules_accompagnementCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Formules_accompagnementCountOutputType
   */
  select?: Prisma.Formules_accompagnementCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Formules_accompagnementCountOutputType without action
 */
export type Formules_accompagnementCountOutputTypeCountDemandes_accompagnementArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.demandes_accompagnementWhereInput
}


export type formules_accompagnementSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nom?: boolean
  slug?: boolean
  description?: boolean
  services_inclus?: boolean
  prix?: boolean
  devise?: boolean
  duree?: boolean
  ordre?: boolean
  actif?: boolean
  created_at?: boolean
  updated_at?: boolean
  demandes_accompagnement?: boolean | Prisma.formules_accompagnement$demandes_accompagnementArgs<ExtArgs>
  _count?: boolean | Prisma.Formules_accompagnementCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["formules_accompagnement"]>

export type formules_accompagnementSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nom?: boolean
  slug?: boolean
  description?: boolean
  services_inclus?: boolean
  prix?: boolean
  devise?: boolean
  duree?: boolean
  ordre?: boolean
  actif?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["formules_accompagnement"]>

export type formules_accompagnementSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nom?: boolean
  slug?: boolean
  description?: boolean
  services_inclus?: boolean
  prix?: boolean
  devise?: boolean
  duree?: boolean
  ordre?: boolean
  actif?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["formules_accompagnement"]>

export type formules_accompagnementSelectScalar = {
  id?: boolean
  nom?: boolean
  slug?: boolean
  description?: boolean
  services_inclus?: boolean
  prix?: boolean
  devise?: boolean
  duree?: boolean
  ordre?: boolean
  actif?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type formules_accompagnementOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nom" | "slug" | "description" | "services_inclus" | "prix" | "devise" | "duree" | "ordre" | "actif" | "created_at" | "updated_at", ExtArgs["result"]["formules_accompagnement"]>
export type formules_accompagnementInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  demandes_accompagnement?: boolean | Prisma.formules_accompagnement$demandes_accompagnementArgs<ExtArgs>
  _count?: boolean | Prisma.Formules_accompagnementCountOutputTypeDefaultArgs<ExtArgs>
}
export type formules_accompagnementIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type formules_accompagnementIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $formules_accompagnementPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "formules_accompagnement"
  objects: {
    demandes_accompagnement: Prisma.$demandes_accompagnementPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    nom: string
    slug: string
    description: string | null
    services_inclus: runtime.JsonValue | null
    prix: runtime.Decimal | null
    devise: string | null
    duree: string | null
    ordre: number | null
    actif: boolean | null
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["formules_accompagnement"]>
  composites: {}
}

export type formules_accompagnementGetPayload<S extends boolean | null | undefined | formules_accompagnementDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$formules_accompagnementPayload, S>

export type formules_accompagnementCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<formules_accompagnementFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Formules_accompagnementCountAggregateInputType | true
  }

export interface formules_accompagnementDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['formules_accompagnement'], meta: { name: 'formules_accompagnement' } }
  /**
   * Find zero or one Formules_accompagnement that matches the filter.
   * @param {formules_accompagnementFindUniqueArgs} args - Arguments to find a Formules_accompagnement
   * @example
   * // Get one Formules_accompagnement
   * const formules_accompagnement = await prisma.formules_accompagnement.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends formules_accompagnementFindUniqueArgs>(args: Prisma.SelectSubset<T, formules_accompagnementFindUniqueArgs<ExtArgs>>): Prisma.Prisma__formules_accompagnementClient<runtime.Types.Result.GetResult<Prisma.$formules_accompagnementPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Formules_accompagnement that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {formules_accompagnementFindUniqueOrThrowArgs} args - Arguments to find a Formules_accompagnement
   * @example
   * // Get one Formules_accompagnement
   * const formules_accompagnement = await prisma.formules_accompagnement.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends formules_accompagnementFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, formules_accompagnementFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__formules_accompagnementClient<runtime.Types.Result.GetResult<Prisma.$formules_accompagnementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Formules_accompagnement that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {formules_accompagnementFindFirstArgs} args - Arguments to find a Formules_accompagnement
   * @example
   * // Get one Formules_accompagnement
   * const formules_accompagnement = await prisma.formules_accompagnement.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends formules_accompagnementFindFirstArgs>(args?: Prisma.SelectSubset<T, formules_accompagnementFindFirstArgs<ExtArgs>>): Prisma.Prisma__formules_accompagnementClient<runtime.Types.Result.GetResult<Prisma.$formules_accompagnementPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Formules_accompagnement that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {formules_accompagnementFindFirstOrThrowArgs} args - Arguments to find a Formules_accompagnement
   * @example
   * // Get one Formules_accompagnement
   * const formules_accompagnement = await prisma.formules_accompagnement.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends formules_accompagnementFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, formules_accompagnementFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__formules_accompagnementClient<runtime.Types.Result.GetResult<Prisma.$formules_accompagnementPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Formules_accompagnements that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {formules_accompagnementFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Formules_accompagnements
   * const formules_accompagnements = await prisma.formules_accompagnement.findMany()
   * 
   * // Get first 10 Formules_accompagnements
   * const formules_accompagnements = await prisma.formules_accompagnement.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const formules_accompagnementWithIdOnly = await prisma.formules_accompagnement.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends formules_accompagnementFindManyArgs>(args?: Prisma.SelectSubset<T, formules_accompagnementFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$formules_accompagnementPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Formules_accompagnement.
   * @param {formules_accompagnementCreateArgs} args - Arguments to create a Formules_accompagnement.
   * @example
   * // Create one Formules_accompagnement
   * const Formules_accompagnement = await prisma.formules_accompagnement.create({
   *   data: {
   *     // ... data to create a Formules_accompagnement
   *   }
   * })
   * 
   */
  create<T extends formules_accompagnementCreateArgs>(args: Prisma.SelectSubset<T, formules_accompagnementCreateArgs<ExtArgs>>): Prisma.Prisma__formules_accompagnementClient<runtime.Types.Result.GetResult<Prisma.$formules_accompagnementPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Formules_accompagnements.
   * @param {formules_accompagnementCreateManyArgs} args - Arguments to create many Formules_accompagnements.
   * @example
   * // Create many Formules_accompagnements
   * const formules_accompagnement = await prisma.formules_accompagnement.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends formules_accompagnementCreateManyArgs>(args?: Prisma.SelectSubset<T, formules_accompagnementCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Formules_accompagnements and returns the data saved in the database.
   * @param {formules_accompagnementCreateManyAndReturnArgs} args - Arguments to create many Formules_accompagnements.
   * @example
   * // Create many Formules_accompagnements
   * const formules_accompagnement = await prisma.formules_accompagnement.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Formules_accompagnements and only return the `id`
   * const formules_accompagnementWithIdOnly = await prisma.formules_accompagnement.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends formules_accompagnementCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, formules_accompagnementCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$formules_accompagnementPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Formules_accompagnement.
   * @param {formules_accompagnementDeleteArgs} args - Arguments to delete one Formules_accompagnement.
   * @example
   * // Delete one Formules_accompagnement
   * const Formules_accompagnement = await prisma.formules_accompagnement.delete({
   *   where: {
   *     // ... filter to delete one Formules_accompagnement
   *   }
   * })
   * 
   */
  delete<T extends formules_accompagnementDeleteArgs>(args: Prisma.SelectSubset<T, formules_accompagnementDeleteArgs<ExtArgs>>): Prisma.Prisma__formules_accompagnementClient<runtime.Types.Result.GetResult<Prisma.$formules_accompagnementPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Formules_accompagnement.
   * @param {formules_accompagnementUpdateArgs} args - Arguments to update one Formules_accompagnement.
   * @example
   * // Update one Formules_accompagnement
   * const formules_accompagnement = await prisma.formules_accompagnement.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends formules_accompagnementUpdateArgs>(args: Prisma.SelectSubset<T, formules_accompagnementUpdateArgs<ExtArgs>>): Prisma.Prisma__formules_accompagnementClient<runtime.Types.Result.GetResult<Prisma.$formules_accompagnementPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Formules_accompagnements.
   * @param {formules_accompagnementDeleteManyArgs} args - Arguments to filter Formules_accompagnements to delete.
   * @example
   * // Delete a few Formules_accompagnements
   * const { count } = await prisma.formules_accompagnement.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends formules_accompagnementDeleteManyArgs>(args?: Prisma.SelectSubset<T, formules_accompagnementDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Formules_accompagnements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {formules_accompagnementUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Formules_accompagnements
   * const formules_accompagnement = await prisma.formules_accompagnement.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends formules_accompagnementUpdateManyArgs>(args: Prisma.SelectSubset<T, formules_accompagnementUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Formules_accompagnements and returns the data updated in the database.
   * @param {formules_accompagnementUpdateManyAndReturnArgs} args - Arguments to update many Formules_accompagnements.
   * @example
   * // Update many Formules_accompagnements
   * const formules_accompagnement = await prisma.formules_accompagnement.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Formules_accompagnements and only return the `id`
   * const formules_accompagnementWithIdOnly = await prisma.formules_accompagnement.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends formules_accompagnementUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, formules_accompagnementUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$formules_accompagnementPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Formules_accompagnement.
   * @param {formules_accompagnementUpsertArgs} args - Arguments to update or create a Formules_accompagnement.
   * @example
   * // Update or create a Formules_accompagnement
   * const formules_accompagnement = await prisma.formules_accompagnement.upsert({
   *   create: {
   *     // ... data to create a Formules_accompagnement
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Formules_accompagnement we want to update
   *   }
   * })
   */
  upsert<T extends formules_accompagnementUpsertArgs>(args: Prisma.SelectSubset<T, formules_accompagnementUpsertArgs<ExtArgs>>): Prisma.Prisma__formules_accompagnementClient<runtime.Types.Result.GetResult<Prisma.$formules_accompagnementPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Formules_accompagnements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {formules_accompagnementCountArgs} args - Arguments to filter Formules_accompagnements to count.
   * @example
   * // Count the number of Formules_accompagnements
   * const count = await prisma.formules_accompagnement.count({
   *   where: {
   *     // ... the filter for the Formules_accompagnements we want to count
   *   }
   * })
  **/
  count<T extends formules_accompagnementCountArgs>(
    args?: Prisma.Subset<T, formules_accompagnementCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Formules_accompagnementCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Formules_accompagnement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Formules_accompagnementAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Formules_accompagnementAggregateArgs>(args: Prisma.Subset<T, Formules_accompagnementAggregateArgs>): Prisma.PrismaPromise<GetFormules_accompagnementAggregateType<T>>

  /**
   * Group by Formules_accompagnement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {formules_accompagnementGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends formules_accompagnementGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: formules_accompagnementGroupByArgs['orderBy'] }
      : { orderBy?: formules_accompagnementGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, formules_accompagnementGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFormules_accompagnementGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the formules_accompagnement model
 */
readonly fields: formules_accompagnementFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for formules_accompagnement.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__formules_accompagnementClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  demandes_accompagnement<T extends Prisma.formules_accompagnement$demandes_accompagnementArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.formules_accompagnement$demandes_accompagnementArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$demandes_accompagnementPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the formules_accompagnement model
 */
export interface formules_accompagnementFieldRefs {
  readonly id: Prisma.FieldRef<"formules_accompagnement", 'String'>
  readonly nom: Prisma.FieldRef<"formules_accompagnement", 'String'>
  readonly slug: Prisma.FieldRef<"formules_accompagnement", 'String'>
  readonly description: Prisma.FieldRef<"formules_accompagnement", 'String'>
  readonly services_inclus: Prisma.FieldRef<"formules_accompagnement", 'Json'>
  readonly prix: Prisma.FieldRef<"formules_accompagnement", 'Decimal'>
  readonly devise: Prisma.FieldRef<"formules_accompagnement", 'String'>
  readonly duree: Prisma.FieldRef<"formules_accompagnement", 'String'>
  readonly ordre: Prisma.FieldRef<"formules_accompagnement", 'Int'>
  readonly actif: Prisma.FieldRef<"formules_accompagnement", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"formules_accompagnement", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"formules_accompagnement", 'DateTime'>
}
    

// Custom InputTypes
/**
 * formules_accompagnement findUnique
 */
export type formules_accompagnementFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the formules_accompagnement
   */
  select?: Prisma.formules_accompagnementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the formules_accompagnement
   */
  omit?: Prisma.formules_accompagnementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.formules_accompagnementInclude<ExtArgs> | null
  /**
   * Filter, which formules_accompagnement to fetch.
   */
  where: Prisma.formules_accompagnementWhereUniqueInput
}

/**
 * formules_accompagnement findUniqueOrThrow
 */
export type formules_accompagnementFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the formules_accompagnement
   */
  select?: Prisma.formules_accompagnementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the formules_accompagnement
   */
  omit?: Prisma.formules_accompagnementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.formules_accompagnementInclude<ExtArgs> | null
  /**
   * Filter, which formules_accompagnement to fetch.
   */
  where: Prisma.formules_accompagnementWhereUniqueInput
}

/**
 * formules_accompagnement findFirst
 */
export type formules_accompagnementFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the formules_accompagnement
   */
  select?: Prisma.formules_accompagnementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the formules_accompagnement
   */
  omit?: Prisma.formules_accompagnementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.formules_accompagnementInclude<ExtArgs> | null
  /**
   * Filter, which formules_accompagnement to fetch.
   */
  where?: Prisma.formules_accompagnementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of formules_accompagnements to fetch.
   */
  orderBy?: Prisma.formules_accompagnementOrderByWithRelationInput | Prisma.formules_accompagnementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for formules_accompagnements.
   */
  cursor?: Prisma.formules_accompagnementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` formules_accompagnements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` formules_accompagnements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of formules_accompagnements.
   */
  distinct?: Prisma.Formules_accompagnementScalarFieldEnum | Prisma.Formules_accompagnementScalarFieldEnum[]
}

/**
 * formules_accompagnement findFirstOrThrow
 */
export type formules_accompagnementFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the formules_accompagnement
   */
  select?: Prisma.formules_accompagnementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the formules_accompagnement
   */
  omit?: Prisma.formules_accompagnementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.formules_accompagnementInclude<ExtArgs> | null
  /**
   * Filter, which formules_accompagnement to fetch.
   */
  where?: Prisma.formules_accompagnementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of formules_accompagnements to fetch.
   */
  orderBy?: Prisma.formules_accompagnementOrderByWithRelationInput | Prisma.formules_accompagnementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for formules_accompagnements.
   */
  cursor?: Prisma.formules_accompagnementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` formules_accompagnements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` formules_accompagnements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of formules_accompagnements.
   */
  distinct?: Prisma.Formules_accompagnementScalarFieldEnum | Prisma.Formules_accompagnementScalarFieldEnum[]
}

/**
 * formules_accompagnement findMany
 */
export type formules_accompagnementFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the formules_accompagnement
   */
  select?: Prisma.formules_accompagnementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the formules_accompagnement
   */
  omit?: Prisma.formules_accompagnementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.formules_accompagnementInclude<ExtArgs> | null
  /**
   * Filter, which formules_accompagnements to fetch.
   */
  where?: Prisma.formules_accompagnementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of formules_accompagnements to fetch.
   */
  orderBy?: Prisma.formules_accompagnementOrderByWithRelationInput | Prisma.formules_accompagnementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing formules_accompagnements.
   */
  cursor?: Prisma.formules_accompagnementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` formules_accompagnements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` formules_accompagnements.
   */
  skip?: number
  distinct?: Prisma.Formules_accompagnementScalarFieldEnum | Prisma.Formules_accompagnementScalarFieldEnum[]
}

/**
 * formules_accompagnement create
 */
export type formules_accompagnementCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the formules_accompagnement
   */
  select?: Prisma.formules_accompagnementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the formules_accompagnement
   */
  omit?: Prisma.formules_accompagnementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.formules_accompagnementInclude<ExtArgs> | null
  /**
   * The data needed to create a formules_accompagnement.
   */
  data: Prisma.XOR<Prisma.formules_accompagnementCreateInput, Prisma.formules_accompagnementUncheckedCreateInput>
}

/**
 * formules_accompagnement createMany
 */
export type formules_accompagnementCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many formules_accompagnements.
   */
  data: Prisma.formules_accompagnementCreateManyInput | Prisma.formules_accompagnementCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * formules_accompagnement createManyAndReturn
 */
export type formules_accompagnementCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the formules_accompagnement
   */
  select?: Prisma.formules_accompagnementSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the formules_accompagnement
   */
  omit?: Prisma.formules_accompagnementOmit<ExtArgs> | null
  /**
   * The data used to create many formules_accompagnements.
   */
  data: Prisma.formules_accompagnementCreateManyInput | Prisma.formules_accompagnementCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * formules_accompagnement update
 */
export type formules_accompagnementUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the formules_accompagnement
   */
  select?: Prisma.formules_accompagnementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the formules_accompagnement
   */
  omit?: Prisma.formules_accompagnementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.formules_accompagnementInclude<ExtArgs> | null
  /**
   * The data needed to update a formules_accompagnement.
   */
  data: Prisma.XOR<Prisma.formules_accompagnementUpdateInput, Prisma.formules_accompagnementUncheckedUpdateInput>
  /**
   * Choose, which formules_accompagnement to update.
   */
  where: Prisma.formules_accompagnementWhereUniqueInput
}

/**
 * formules_accompagnement updateMany
 */
export type formules_accompagnementUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update formules_accompagnements.
   */
  data: Prisma.XOR<Prisma.formules_accompagnementUpdateManyMutationInput, Prisma.formules_accompagnementUncheckedUpdateManyInput>
  /**
   * Filter which formules_accompagnements to update
   */
  where?: Prisma.formules_accompagnementWhereInput
  /**
   * Limit how many formules_accompagnements to update.
   */
  limit?: number
}

/**
 * formules_accompagnement updateManyAndReturn
 */
export type formules_accompagnementUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the formules_accompagnement
   */
  select?: Prisma.formules_accompagnementSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the formules_accompagnement
   */
  omit?: Prisma.formules_accompagnementOmit<ExtArgs> | null
  /**
   * The data used to update formules_accompagnements.
   */
  data: Prisma.XOR<Prisma.formules_accompagnementUpdateManyMutationInput, Prisma.formules_accompagnementUncheckedUpdateManyInput>
  /**
   * Filter which formules_accompagnements to update
   */
  where?: Prisma.formules_accompagnementWhereInput
  /**
   * Limit how many formules_accompagnements to update.
   */
  limit?: number
}

/**
 * formules_accompagnement upsert
 */
export type formules_accompagnementUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the formules_accompagnement
   */
  select?: Prisma.formules_accompagnementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the formules_accompagnement
   */
  omit?: Prisma.formules_accompagnementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.formules_accompagnementInclude<ExtArgs> | null
  /**
   * The filter to search for the formules_accompagnement to update in case it exists.
   */
  where: Prisma.formules_accompagnementWhereUniqueInput
  /**
   * In case the formules_accompagnement found by the `where` argument doesn't exist, create a new formules_accompagnement with this data.
   */
  create: Prisma.XOR<Prisma.formules_accompagnementCreateInput, Prisma.formules_accompagnementUncheckedCreateInput>
  /**
   * In case the formules_accompagnement was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.formules_accompagnementUpdateInput, Prisma.formules_accompagnementUncheckedUpdateInput>
}

/**
 * formules_accompagnement delete
 */
export type formules_accompagnementDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the formules_accompagnement
   */
  select?: Prisma.formules_accompagnementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the formules_accompagnement
   */
  omit?: Prisma.formules_accompagnementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.formules_accompagnementInclude<ExtArgs> | null
  /**
   * Filter which formules_accompagnement to delete.
   */
  where: Prisma.formules_accompagnementWhereUniqueInput
}

/**
 * formules_accompagnement deleteMany
 */
export type formules_accompagnementDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which formules_accompagnements to delete
   */
  where?: Prisma.formules_accompagnementWhereInput
  /**
   * Limit how many formules_accompagnements to delete.
   */
  limit?: number
}

/**
 * formules_accompagnement.demandes_accompagnement
 */
export type formules_accompagnement$demandes_accompagnementArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the demandes_accompagnement
   */
  select?: Prisma.demandes_accompagnementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the demandes_accompagnement
   */
  omit?: Prisma.demandes_accompagnementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.demandes_accompagnementInclude<ExtArgs> | null
  where?: Prisma.demandes_accompagnementWhereInput
  orderBy?: Prisma.demandes_accompagnementOrderByWithRelationInput | Prisma.demandes_accompagnementOrderByWithRelationInput[]
  cursor?: Prisma.demandes_accompagnementWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Demandes_accompagnementScalarFieldEnum | Prisma.Demandes_accompagnementScalarFieldEnum[]
}

/**
 * formules_accompagnement without action
 */
export type formules_accompagnementDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the formules_accompagnement
   */
  select?: Prisma.formules_accompagnementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the formules_accompagnement
   */
  omit?: Prisma.formules_accompagnementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.formules_accompagnementInclude<ExtArgs> | null
}
