
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `messages` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model messages
 * 
 */
export type messagesModel = runtime.Types.Result.DefaultSelection<Prisma.$messagesPayload>

export type AggregateMessages = {
  _count: MessagesCountAggregateOutputType | null
  _min: MessagesMinAggregateOutputType | null
  _max: MessagesMaxAggregateOutputType | null
}

export type MessagesMinAggregateOutputType = {
  id: string | null
  conversation_id: string | null
  expediteur_id: string | null
  contenu: string | null
  est_admin: boolean | null
  lu: boolean | null
  date_lecture: Date | null
  created_at: Date | null
}

export type MessagesMaxAggregateOutputType = {
  id: string | null
  conversation_id: string | null
  expediteur_id: string | null
  contenu: string | null
  est_admin: boolean | null
  lu: boolean | null
  date_lecture: Date | null
  created_at: Date | null
}

export type MessagesCountAggregateOutputType = {
  id: number
  conversation_id: number
  expediteur_id: number
  contenu: number
  est_admin: number
  lu: number
  date_lecture: number
  fichiers_attaches: number
  created_at: number
  _all: number
}


export type MessagesMinAggregateInputType = {
  id?: true
  conversation_id?: true
  expediteur_id?: true
  contenu?: true
  est_admin?: true
  lu?: true
  date_lecture?: true
  created_at?: true
}

export type MessagesMaxAggregateInputType = {
  id?: true
  conversation_id?: true
  expediteur_id?: true
  contenu?: true
  est_admin?: true
  lu?: true
  date_lecture?: true
  created_at?: true
}

export type MessagesCountAggregateInputType = {
  id?: true
  conversation_id?: true
  expediteur_id?: true
  contenu?: true
  est_admin?: true
  lu?: true
  date_lecture?: true
  fichiers_attaches?: true
  created_at?: true
  _all?: true
}

export type MessagesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which messages to aggregate.
   */
  where?: Prisma.messagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of messages to fetch.
   */
  orderBy?: Prisma.messagesOrderByWithRelationInput | Prisma.messagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.messagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned messages
  **/
  _count?: true | MessagesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MessagesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MessagesMaxAggregateInputType
}

export type GetMessagesAggregateType<T extends MessagesAggregateArgs> = {
      [P in keyof T & keyof AggregateMessages]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMessages[P]>
    : Prisma.GetScalarType<T[P], AggregateMessages[P]>
}




export type messagesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.messagesWhereInput
  orderBy?: Prisma.messagesOrderByWithAggregationInput | Prisma.messagesOrderByWithAggregationInput[]
  by: Prisma.MessagesScalarFieldEnum[] | Prisma.MessagesScalarFieldEnum
  having?: Prisma.messagesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MessagesCountAggregateInputType | true
  _min?: MessagesMinAggregateInputType
  _max?: MessagesMaxAggregateInputType
}

export type MessagesGroupByOutputType = {
  id: string
  conversation_id: string
  expediteur_id: string
  contenu: string
  est_admin: boolean | null
  lu: boolean | null
  date_lecture: Date | null
  fichiers_attaches: runtime.JsonValue | null
  created_at: Date | null
  _count: MessagesCountAggregateOutputType | null
  _min: MessagesMinAggregateOutputType | null
  _max: MessagesMaxAggregateOutputType | null
}

type GetMessagesGroupByPayload<T extends messagesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MessagesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MessagesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MessagesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MessagesGroupByOutputType[P]>
      }
    >
  >



export type messagesWhereInput = {
  AND?: Prisma.messagesWhereInput | Prisma.messagesWhereInput[]
  OR?: Prisma.messagesWhereInput[]
  NOT?: Prisma.messagesWhereInput | Prisma.messagesWhereInput[]
  id?: Prisma.StringFilter<"messages"> | string
  conversation_id?: Prisma.StringFilter<"messages"> | string
  expediteur_id?: Prisma.StringFilter<"messages"> | string
  contenu?: Prisma.StringFilter<"messages"> | string
  est_admin?: Prisma.BoolNullableFilter<"messages"> | boolean | null
  lu?: Prisma.BoolNullableFilter<"messages"> | boolean | null
  date_lecture?: Prisma.DateTimeNullableFilter<"messages"> | Date | string | null
  fichiers_attaches?: Prisma.JsonNullableFilter<"messages">
  created_at?: Prisma.DateTimeNullableFilter<"messages"> | Date | string | null
  conversations?: Prisma.XOR<Prisma.ConversationsScalarRelationFilter, Prisma.conversationsWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}

export type messagesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  conversation_id?: Prisma.SortOrder
  expediteur_id?: Prisma.SortOrder
  contenu?: Prisma.SortOrder
  est_admin?: Prisma.SortOrderInput | Prisma.SortOrder
  lu?: Prisma.SortOrderInput | Prisma.SortOrder
  date_lecture?: Prisma.SortOrderInput | Prisma.SortOrder
  fichiers_attaches?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  conversations?: Prisma.conversationsOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
}

export type messagesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.messagesWhereInput | Prisma.messagesWhereInput[]
  OR?: Prisma.messagesWhereInput[]
  NOT?: Prisma.messagesWhereInput | Prisma.messagesWhereInput[]
  conversation_id?: Prisma.StringFilter<"messages"> | string
  expediteur_id?: Prisma.StringFilter<"messages"> | string
  contenu?: Prisma.StringFilter<"messages"> | string
  est_admin?: Prisma.BoolNullableFilter<"messages"> | boolean | null
  lu?: Prisma.BoolNullableFilter<"messages"> | boolean | null
  date_lecture?: Prisma.DateTimeNullableFilter<"messages"> | Date | string | null
  fichiers_attaches?: Prisma.JsonNullableFilter<"messages">
  created_at?: Prisma.DateTimeNullableFilter<"messages"> | Date | string | null
  conversations?: Prisma.XOR<Prisma.ConversationsScalarRelationFilter, Prisma.conversationsWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}, "id">

export type messagesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  conversation_id?: Prisma.SortOrder
  expediteur_id?: Prisma.SortOrder
  contenu?: Prisma.SortOrder
  est_admin?: Prisma.SortOrderInput | Prisma.SortOrder
  lu?: Prisma.SortOrderInput | Prisma.SortOrder
  date_lecture?: Prisma.SortOrderInput | Prisma.SortOrder
  fichiers_attaches?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.messagesCountOrderByAggregateInput
  _max?: Prisma.messagesMaxOrderByAggregateInput
  _min?: Prisma.messagesMinOrderByAggregateInput
}

export type messagesScalarWhereWithAggregatesInput = {
  AND?: Prisma.messagesScalarWhereWithAggregatesInput | Prisma.messagesScalarWhereWithAggregatesInput[]
  OR?: Prisma.messagesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.messagesScalarWhereWithAggregatesInput | Prisma.messagesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"messages"> | string
  conversation_id?: Prisma.StringWithAggregatesFilter<"messages"> | string
  expediteur_id?: Prisma.StringWithAggregatesFilter<"messages"> | string
  contenu?: Prisma.StringWithAggregatesFilter<"messages"> | string
  est_admin?: Prisma.BoolNullableWithAggregatesFilter<"messages"> | boolean | null
  lu?: Prisma.BoolNullableWithAggregatesFilter<"messages"> | boolean | null
  date_lecture?: Prisma.DateTimeNullableWithAggregatesFilter<"messages"> | Date | string | null
  fichiers_attaches?: Prisma.JsonNullableWithAggregatesFilter<"messages">
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"messages"> | Date | string | null
}

export type messagesCreateInput = {
  id: string
  contenu: string
  est_admin?: boolean | null
  lu?: boolean | null
  date_lecture?: Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
  conversations: Prisma.conversationsCreateNestedOneWithoutMessagesInput
  users: Prisma.usersCreateNestedOneWithoutMessagesInput
}

export type messagesUncheckedCreateInput = {
  id: string
  conversation_id: string
  expediteur_id: string
  contenu: string
  est_admin?: boolean | null
  lu?: boolean | null
  date_lecture?: Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
}

export type messagesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contenu?: Prisma.StringFieldUpdateOperationsInput | string
  est_admin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  lu?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  date_lecture?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  conversations?: Prisma.conversationsUpdateOneRequiredWithoutMessagesNestedInput
  users?: Prisma.usersUpdateOneRequiredWithoutMessagesNestedInput
}

export type messagesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversation_id?: Prisma.StringFieldUpdateOperationsInput | string
  expediteur_id?: Prisma.StringFieldUpdateOperationsInput | string
  contenu?: Prisma.StringFieldUpdateOperationsInput | string
  est_admin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  lu?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  date_lecture?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type messagesCreateManyInput = {
  id: string
  conversation_id: string
  expediteur_id: string
  contenu: string
  est_admin?: boolean | null
  lu?: boolean | null
  date_lecture?: Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
}

export type messagesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contenu?: Prisma.StringFieldUpdateOperationsInput | string
  est_admin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  lu?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  date_lecture?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type messagesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversation_id?: Prisma.StringFieldUpdateOperationsInput | string
  expediteur_id?: Prisma.StringFieldUpdateOperationsInput | string
  contenu?: Prisma.StringFieldUpdateOperationsInput | string
  est_admin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  lu?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  date_lecture?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type MessagesListRelationFilter = {
  every?: Prisma.messagesWhereInput
  some?: Prisma.messagesWhereInput
  none?: Prisma.messagesWhereInput
}

export type messagesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type messagesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conversation_id?: Prisma.SortOrder
  expediteur_id?: Prisma.SortOrder
  contenu?: Prisma.SortOrder
  est_admin?: Prisma.SortOrder
  lu?: Prisma.SortOrder
  date_lecture?: Prisma.SortOrder
  fichiers_attaches?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type messagesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conversation_id?: Prisma.SortOrder
  expediteur_id?: Prisma.SortOrder
  contenu?: Prisma.SortOrder
  est_admin?: Prisma.SortOrder
  lu?: Prisma.SortOrder
  date_lecture?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type messagesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conversation_id?: Prisma.SortOrder
  expediteur_id?: Prisma.SortOrder
  contenu?: Prisma.SortOrder
  est_admin?: Prisma.SortOrder
  lu?: Prisma.SortOrder
  date_lecture?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type messagesCreateNestedManyWithoutConversationsInput = {
  create?: Prisma.XOR<Prisma.messagesCreateWithoutConversationsInput, Prisma.messagesUncheckedCreateWithoutConversationsInput> | Prisma.messagesCreateWithoutConversationsInput[] | Prisma.messagesUncheckedCreateWithoutConversationsInput[]
  connectOrCreate?: Prisma.messagesCreateOrConnectWithoutConversationsInput | Prisma.messagesCreateOrConnectWithoutConversationsInput[]
  createMany?: Prisma.messagesCreateManyConversationsInputEnvelope
  connect?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
}

export type messagesUncheckedCreateNestedManyWithoutConversationsInput = {
  create?: Prisma.XOR<Prisma.messagesCreateWithoutConversationsInput, Prisma.messagesUncheckedCreateWithoutConversationsInput> | Prisma.messagesCreateWithoutConversationsInput[] | Prisma.messagesUncheckedCreateWithoutConversationsInput[]
  connectOrCreate?: Prisma.messagesCreateOrConnectWithoutConversationsInput | Prisma.messagesCreateOrConnectWithoutConversationsInput[]
  createMany?: Prisma.messagesCreateManyConversationsInputEnvelope
  connect?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
}

export type messagesUpdateManyWithoutConversationsNestedInput = {
  create?: Prisma.XOR<Prisma.messagesCreateWithoutConversationsInput, Prisma.messagesUncheckedCreateWithoutConversationsInput> | Prisma.messagesCreateWithoutConversationsInput[] | Prisma.messagesUncheckedCreateWithoutConversationsInput[]
  connectOrCreate?: Prisma.messagesCreateOrConnectWithoutConversationsInput | Prisma.messagesCreateOrConnectWithoutConversationsInput[]
  upsert?: Prisma.messagesUpsertWithWhereUniqueWithoutConversationsInput | Prisma.messagesUpsertWithWhereUniqueWithoutConversationsInput[]
  createMany?: Prisma.messagesCreateManyConversationsInputEnvelope
  set?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  disconnect?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  delete?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  connect?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  update?: Prisma.messagesUpdateWithWhereUniqueWithoutConversationsInput | Prisma.messagesUpdateWithWhereUniqueWithoutConversationsInput[]
  updateMany?: Prisma.messagesUpdateManyWithWhereWithoutConversationsInput | Prisma.messagesUpdateManyWithWhereWithoutConversationsInput[]
  deleteMany?: Prisma.messagesScalarWhereInput | Prisma.messagesScalarWhereInput[]
}

export type messagesUncheckedUpdateManyWithoutConversationsNestedInput = {
  create?: Prisma.XOR<Prisma.messagesCreateWithoutConversationsInput, Prisma.messagesUncheckedCreateWithoutConversationsInput> | Prisma.messagesCreateWithoutConversationsInput[] | Prisma.messagesUncheckedCreateWithoutConversationsInput[]
  connectOrCreate?: Prisma.messagesCreateOrConnectWithoutConversationsInput | Prisma.messagesCreateOrConnectWithoutConversationsInput[]
  upsert?: Prisma.messagesUpsertWithWhereUniqueWithoutConversationsInput | Prisma.messagesUpsertWithWhereUniqueWithoutConversationsInput[]
  createMany?: Prisma.messagesCreateManyConversationsInputEnvelope
  set?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  disconnect?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  delete?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  connect?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  update?: Prisma.messagesUpdateWithWhereUniqueWithoutConversationsInput | Prisma.messagesUpdateWithWhereUniqueWithoutConversationsInput[]
  updateMany?: Prisma.messagesUpdateManyWithWhereWithoutConversationsInput | Prisma.messagesUpdateManyWithWhereWithoutConversationsInput[]
  deleteMany?: Prisma.messagesScalarWhereInput | Prisma.messagesScalarWhereInput[]
}

export type messagesCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.messagesCreateWithoutUsersInput, Prisma.messagesUncheckedCreateWithoutUsersInput> | Prisma.messagesCreateWithoutUsersInput[] | Prisma.messagesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.messagesCreateOrConnectWithoutUsersInput | Prisma.messagesCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.messagesCreateManyUsersInputEnvelope
  connect?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
}

export type messagesUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.messagesCreateWithoutUsersInput, Prisma.messagesUncheckedCreateWithoutUsersInput> | Prisma.messagesCreateWithoutUsersInput[] | Prisma.messagesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.messagesCreateOrConnectWithoutUsersInput | Prisma.messagesCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.messagesCreateManyUsersInputEnvelope
  connect?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
}

export type messagesUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.messagesCreateWithoutUsersInput, Prisma.messagesUncheckedCreateWithoutUsersInput> | Prisma.messagesCreateWithoutUsersInput[] | Prisma.messagesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.messagesCreateOrConnectWithoutUsersInput | Prisma.messagesCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.messagesUpsertWithWhereUniqueWithoutUsersInput | Prisma.messagesUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.messagesCreateManyUsersInputEnvelope
  set?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  disconnect?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  delete?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  connect?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  update?: Prisma.messagesUpdateWithWhereUniqueWithoutUsersInput | Prisma.messagesUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.messagesUpdateManyWithWhereWithoutUsersInput | Prisma.messagesUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.messagesScalarWhereInput | Prisma.messagesScalarWhereInput[]
}

export type messagesUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.messagesCreateWithoutUsersInput, Prisma.messagesUncheckedCreateWithoutUsersInput> | Prisma.messagesCreateWithoutUsersInput[] | Prisma.messagesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.messagesCreateOrConnectWithoutUsersInput | Prisma.messagesCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.messagesUpsertWithWhereUniqueWithoutUsersInput | Prisma.messagesUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.messagesCreateManyUsersInputEnvelope
  set?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  disconnect?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  delete?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  connect?: Prisma.messagesWhereUniqueInput | Prisma.messagesWhereUniqueInput[]
  update?: Prisma.messagesUpdateWithWhereUniqueWithoutUsersInput | Prisma.messagesUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.messagesUpdateManyWithWhereWithoutUsersInput | Prisma.messagesUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.messagesScalarWhereInput | Prisma.messagesScalarWhereInput[]
}

export type messagesCreateWithoutConversationsInput = {
  id: string
  contenu: string
  est_admin?: boolean | null
  lu?: boolean | null
  date_lecture?: Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
  users: Prisma.usersCreateNestedOneWithoutMessagesInput
}

export type messagesUncheckedCreateWithoutConversationsInput = {
  id: string
  expediteur_id: string
  contenu: string
  est_admin?: boolean | null
  lu?: boolean | null
  date_lecture?: Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
}

export type messagesCreateOrConnectWithoutConversationsInput = {
  where: Prisma.messagesWhereUniqueInput
  create: Prisma.XOR<Prisma.messagesCreateWithoutConversationsInput, Prisma.messagesUncheckedCreateWithoutConversationsInput>
}

export type messagesCreateManyConversationsInputEnvelope = {
  data: Prisma.messagesCreateManyConversationsInput | Prisma.messagesCreateManyConversationsInput[]
  skipDuplicates?: boolean
}

export type messagesUpsertWithWhereUniqueWithoutConversationsInput = {
  where: Prisma.messagesWhereUniqueInput
  update: Prisma.XOR<Prisma.messagesUpdateWithoutConversationsInput, Prisma.messagesUncheckedUpdateWithoutConversationsInput>
  create: Prisma.XOR<Prisma.messagesCreateWithoutConversationsInput, Prisma.messagesUncheckedCreateWithoutConversationsInput>
}

export type messagesUpdateWithWhereUniqueWithoutConversationsInput = {
  where: Prisma.messagesWhereUniqueInput
  data: Prisma.XOR<Prisma.messagesUpdateWithoutConversationsInput, Prisma.messagesUncheckedUpdateWithoutConversationsInput>
}

export type messagesUpdateManyWithWhereWithoutConversationsInput = {
  where: Prisma.messagesScalarWhereInput
  data: Prisma.XOR<Prisma.messagesUpdateManyMutationInput, Prisma.messagesUncheckedUpdateManyWithoutConversationsInput>
}

export type messagesScalarWhereInput = {
  AND?: Prisma.messagesScalarWhereInput | Prisma.messagesScalarWhereInput[]
  OR?: Prisma.messagesScalarWhereInput[]
  NOT?: Prisma.messagesScalarWhereInput | Prisma.messagesScalarWhereInput[]
  id?: Prisma.StringFilter<"messages"> | string
  conversation_id?: Prisma.StringFilter<"messages"> | string
  expediteur_id?: Prisma.StringFilter<"messages"> | string
  contenu?: Prisma.StringFilter<"messages"> | string
  est_admin?: Prisma.BoolNullableFilter<"messages"> | boolean | null
  lu?: Prisma.BoolNullableFilter<"messages"> | boolean | null
  date_lecture?: Prisma.DateTimeNullableFilter<"messages"> | Date | string | null
  fichiers_attaches?: Prisma.JsonNullableFilter<"messages">
  created_at?: Prisma.DateTimeNullableFilter<"messages"> | Date | string | null
}

export type messagesCreateWithoutUsersInput = {
  id: string
  contenu: string
  est_admin?: boolean | null
  lu?: boolean | null
  date_lecture?: Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
  conversations: Prisma.conversationsCreateNestedOneWithoutMessagesInput
}

export type messagesUncheckedCreateWithoutUsersInput = {
  id: string
  conversation_id: string
  contenu: string
  est_admin?: boolean | null
  lu?: boolean | null
  date_lecture?: Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
}

export type messagesCreateOrConnectWithoutUsersInput = {
  where: Prisma.messagesWhereUniqueInput
  create: Prisma.XOR<Prisma.messagesCreateWithoutUsersInput, Prisma.messagesUncheckedCreateWithoutUsersInput>
}

export type messagesCreateManyUsersInputEnvelope = {
  data: Prisma.messagesCreateManyUsersInput | Prisma.messagesCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type messagesUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.messagesWhereUniqueInput
  update: Prisma.XOR<Prisma.messagesUpdateWithoutUsersInput, Prisma.messagesUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.messagesCreateWithoutUsersInput, Prisma.messagesUncheckedCreateWithoutUsersInput>
}

export type messagesUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.messagesWhereUniqueInput
  data: Prisma.XOR<Prisma.messagesUpdateWithoutUsersInput, Prisma.messagesUncheckedUpdateWithoutUsersInput>
}

export type messagesUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.messagesScalarWhereInput
  data: Prisma.XOR<Prisma.messagesUpdateManyMutationInput, Prisma.messagesUncheckedUpdateManyWithoutUsersInput>
}

export type messagesCreateManyConversationsInput = {
  id: string
  expediteur_id: string
  contenu: string
  est_admin?: boolean | null
  lu?: boolean | null
  date_lecture?: Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
}

export type messagesUpdateWithoutConversationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contenu?: Prisma.StringFieldUpdateOperationsInput | string
  est_admin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  lu?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  date_lecture?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneRequiredWithoutMessagesNestedInput
}

export type messagesUncheckedUpdateWithoutConversationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expediteur_id?: Prisma.StringFieldUpdateOperationsInput | string
  contenu?: Prisma.StringFieldUpdateOperationsInput | string
  est_admin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  lu?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  date_lecture?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type messagesUncheckedUpdateManyWithoutConversationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expediteur_id?: Prisma.StringFieldUpdateOperationsInput | string
  contenu?: Prisma.StringFieldUpdateOperationsInput | string
  est_admin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  lu?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  date_lecture?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type messagesCreateManyUsersInput = {
  id: string
  conversation_id: string
  contenu: string
  est_admin?: boolean | null
  lu?: boolean | null
  date_lecture?: Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
}

export type messagesUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contenu?: Prisma.StringFieldUpdateOperationsInput | string
  est_admin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  lu?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  date_lecture?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  conversations?: Prisma.conversationsUpdateOneRequiredWithoutMessagesNestedInput
}

export type messagesUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversation_id?: Prisma.StringFieldUpdateOperationsInput | string
  contenu?: Prisma.StringFieldUpdateOperationsInput | string
  est_admin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  lu?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  date_lecture?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type messagesUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversation_id?: Prisma.StringFieldUpdateOperationsInput | string
  contenu?: Prisma.StringFieldUpdateOperationsInput | string
  est_admin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  lu?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  date_lecture?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fichiers_attaches?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type messagesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conversation_id?: boolean
  expediteur_id?: boolean
  contenu?: boolean
  est_admin?: boolean
  lu?: boolean
  date_lecture?: boolean
  fichiers_attaches?: boolean
  created_at?: boolean
  conversations?: boolean | Prisma.conversationsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["messages"]>

export type messagesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conversation_id?: boolean
  expediteur_id?: boolean
  contenu?: boolean
  est_admin?: boolean
  lu?: boolean
  date_lecture?: boolean
  fichiers_attaches?: boolean
  created_at?: boolean
  conversations?: boolean | Prisma.conversationsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["messages"]>

export type messagesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conversation_id?: boolean
  expediteur_id?: boolean
  contenu?: boolean
  est_admin?: boolean
  lu?: boolean
  date_lecture?: boolean
  fichiers_attaches?: boolean
  created_at?: boolean
  conversations?: boolean | Prisma.conversationsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["messages"]>

export type messagesSelectScalar = {
  id?: boolean
  conversation_id?: boolean
  expediteur_id?: boolean
  contenu?: boolean
  est_admin?: boolean
  lu?: boolean
  date_lecture?: boolean
  fichiers_attaches?: boolean
  created_at?: boolean
}

export type messagesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "conversation_id" | "expediteur_id" | "contenu" | "est_admin" | "lu" | "date_lecture" | "fichiers_attaches" | "created_at", ExtArgs["result"]["messages"]>
export type messagesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  conversations?: boolean | Prisma.conversationsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type messagesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  conversations?: boolean | Prisma.conversationsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type messagesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  conversations?: boolean | Prisma.conversationsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}

export type $messagesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "messages"
  objects: {
    conversations: Prisma.$conversationsPayload<ExtArgs>
    users: Prisma.$usersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    conversation_id: string
    expediteur_id: string
    contenu: string
    est_admin: boolean | null
    lu: boolean | null
    date_lecture: Date | null
    fichiers_attaches: runtime.JsonValue | null
    created_at: Date | null
  }, ExtArgs["result"]["messages"]>
  composites: {}
}

export type messagesGetPayload<S extends boolean | null | undefined | messagesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$messagesPayload, S>

export type messagesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<messagesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MessagesCountAggregateInputType | true
  }

export interface messagesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['messages'], meta: { name: 'messages' } }
  /**
   * Find zero or one Messages that matches the filter.
   * @param {messagesFindUniqueArgs} args - Arguments to find a Messages
   * @example
   * // Get one Messages
   * const messages = await prisma.messages.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends messagesFindUniqueArgs>(args: Prisma.SelectSubset<T, messagesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__messagesClient<runtime.Types.Result.GetResult<Prisma.$messagesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Messages that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {messagesFindUniqueOrThrowArgs} args - Arguments to find a Messages
   * @example
   * // Get one Messages
   * const messages = await prisma.messages.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends messagesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, messagesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__messagesClient<runtime.Types.Result.GetResult<Prisma.$messagesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Messages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {messagesFindFirstArgs} args - Arguments to find a Messages
   * @example
   * // Get one Messages
   * const messages = await prisma.messages.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends messagesFindFirstArgs>(args?: Prisma.SelectSubset<T, messagesFindFirstArgs<ExtArgs>>): Prisma.Prisma__messagesClient<runtime.Types.Result.GetResult<Prisma.$messagesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Messages that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {messagesFindFirstOrThrowArgs} args - Arguments to find a Messages
   * @example
   * // Get one Messages
   * const messages = await prisma.messages.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends messagesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, messagesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__messagesClient<runtime.Types.Result.GetResult<Prisma.$messagesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Messages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {messagesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Messages
   * const messages = await prisma.messages.findMany()
   * 
   * // Get first 10 Messages
   * const messages = await prisma.messages.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const messagesWithIdOnly = await prisma.messages.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends messagesFindManyArgs>(args?: Prisma.SelectSubset<T, messagesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$messagesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Messages.
   * @param {messagesCreateArgs} args - Arguments to create a Messages.
   * @example
   * // Create one Messages
   * const Messages = await prisma.messages.create({
   *   data: {
   *     // ... data to create a Messages
   *   }
   * })
   * 
   */
  create<T extends messagesCreateArgs>(args: Prisma.SelectSubset<T, messagesCreateArgs<ExtArgs>>): Prisma.Prisma__messagesClient<runtime.Types.Result.GetResult<Prisma.$messagesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Messages.
   * @param {messagesCreateManyArgs} args - Arguments to create many Messages.
   * @example
   * // Create many Messages
   * const messages = await prisma.messages.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends messagesCreateManyArgs>(args?: Prisma.SelectSubset<T, messagesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Messages and returns the data saved in the database.
   * @param {messagesCreateManyAndReturnArgs} args - Arguments to create many Messages.
   * @example
   * // Create many Messages
   * const messages = await prisma.messages.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Messages and only return the `id`
   * const messagesWithIdOnly = await prisma.messages.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends messagesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, messagesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$messagesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Messages.
   * @param {messagesDeleteArgs} args - Arguments to delete one Messages.
   * @example
   * // Delete one Messages
   * const Messages = await prisma.messages.delete({
   *   where: {
   *     // ... filter to delete one Messages
   *   }
   * })
   * 
   */
  delete<T extends messagesDeleteArgs>(args: Prisma.SelectSubset<T, messagesDeleteArgs<ExtArgs>>): Prisma.Prisma__messagesClient<runtime.Types.Result.GetResult<Prisma.$messagesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Messages.
   * @param {messagesUpdateArgs} args - Arguments to update one Messages.
   * @example
   * // Update one Messages
   * const messages = await prisma.messages.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends messagesUpdateArgs>(args: Prisma.SelectSubset<T, messagesUpdateArgs<ExtArgs>>): Prisma.Prisma__messagesClient<runtime.Types.Result.GetResult<Prisma.$messagesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Messages.
   * @param {messagesDeleteManyArgs} args - Arguments to filter Messages to delete.
   * @example
   * // Delete a few Messages
   * const { count } = await prisma.messages.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends messagesDeleteManyArgs>(args?: Prisma.SelectSubset<T, messagesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Messages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {messagesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Messages
   * const messages = await prisma.messages.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends messagesUpdateManyArgs>(args: Prisma.SelectSubset<T, messagesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Messages and returns the data updated in the database.
   * @param {messagesUpdateManyAndReturnArgs} args - Arguments to update many Messages.
   * @example
   * // Update many Messages
   * const messages = await prisma.messages.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Messages and only return the `id`
   * const messagesWithIdOnly = await prisma.messages.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends messagesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, messagesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$messagesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Messages.
   * @param {messagesUpsertArgs} args - Arguments to update or create a Messages.
   * @example
   * // Update or create a Messages
   * const messages = await prisma.messages.upsert({
   *   create: {
   *     // ... data to create a Messages
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Messages we want to update
   *   }
   * })
   */
  upsert<T extends messagesUpsertArgs>(args: Prisma.SelectSubset<T, messagesUpsertArgs<ExtArgs>>): Prisma.Prisma__messagesClient<runtime.Types.Result.GetResult<Prisma.$messagesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Messages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {messagesCountArgs} args - Arguments to filter Messages to count.
   * @example
   * // Count the number of Messages
   * const count = await prisma.messages.count({
   *   where: {
   *     // ... the filter for the Messages we want to count
   *   }
   * })
  **/
  count<T extends messagesCountArgs>(
    args?: Prisma.Subset<T, messagesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MessagesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Messages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessagesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MessagesAggregateArgs>(args: Prisma.Subset<T, MessagesAggregateArgs>): Prisma.PrismaPromise<GetMessagesAggregateType<T>>

  /**
   * Group by Messages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {messagesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends messagesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: messagesGroupByArgs['orderBy'] }
      : { orderBy?: messagesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, messagesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMessagesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the messages model
 */
readonly fields: messagesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for messages.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__messagesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  conversations<T extends Prisma.conversationsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.conversationsDefaultArgs<ExtArgs>>): Prisma.Prisma__conversationsClient<runtime.Types.Result.GetResult<Prisma.$conversationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the messages model
 */
export interface messagesFieldRefs {
  readonly id: Prisma.FieldRef<"messages", 'String'>
  readonly conversation_id: Prisma.FieldRef<"messages", 'String'>
  readonly expediteur_id: Prisma.FieldRef<"messages", 'String'>
  readonly contenu: Prisma.FieldRef<"messages", 'String'>
  readonly est_admin: Prisma.FieldRef<"messages", 'Boolean'>
  readonly lu: Prisma.FieldRef<"messages", 'Boolean'>
  readonly date_lecture: Prisma.FieldRef<"messages", 'DateTime'>
  readonly fichiers_attaches: Prisma.FieldRef<"messages", 'Json'>
  readonly created_at: Prisma.FieldRef<"messages", 'DateTime'>
}
    

// Custom InputTypes
/**
 * messages findUnique
 */
export type messagesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the messages
   */
  select?: Prisma.messagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the messages
   */
  omit?: Prisma.messagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.messagesInclude<ExtArgs> | null
  /**
   * Filter, which messages to fetch.
   */
  where: Prisma.messagesWhereUniqueInput
}

/**
 * messages findUniqueOrThrow
 */
export type messagesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the messages
   */
  select?: Prisma.messagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the messages
   */
  omit?: Prisma.messagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.messagesInclude<ExtArgs> | null
  /**
   * Filter, which messages to fetch.
   */
  where: Prisma.messagesWhereUniqueInput
}

/**
 * messages findFirst
 */
export type messagesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the messages
   */
  select?: Prisma.messagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the messages
   */
  omit?: Prisma.messagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.messagesInclude<ExtArgs> | null
  /**
   * Filter, which messages to fetch.
   */
  where?: Prisma.messagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of messages to fetch.
   */
  orderBy?: Prisma.messagesOrderByWithRelationInput | Prisma.messagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for messages.
   */
  cursor?: Prisma.messagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of messages.
   */
  distinct?: Prisma.MessagesScalarFieldEnum | Prisma.MessagesScalarFieldEnum[]
}

/**
 * messages findFirstOrThrow
 */
export type messagesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the messages
   */
  select?: Prisma.messagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the messages
   */
  omit?: Prisma.messagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.messagesInclude<ExtArgs> | null
  /**
   * Filter, which messages to fetch.
   */
  where?: Prisma.messagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of messages to fetch.
   */
  orderBy?: Prisma.messagesOrderByWithRelationInput | Prisma.messagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for messages.
   */
  cursor?: Prisma.messagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of messages.
   */
  distinct?: Prisma.MessagesScalarFieldEnum | Prisma.MessagesScalarFieldEnum[]
}

/**
 * messages findMany
 */
export type messagesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the messages
   */
  select?: Prisma.messagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the messages
   */
  omit?: Prisma.messagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.messagesInclude<ExtArgs> | null
  /**
   * Filter, which messages to fetch.
   */
  where?: Prisma.messagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of messages to fetch.
   */
  orderBy?: Prisma.messagesOrderByWithRelationInput | Prisma.messagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing messages.
   */
  cursor?: Prisma.messagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` messages.
   */
  skip?: number
  distinct?: Prisma.MessagesScalarFieldEnum | Prisma.MessagesScalarFieldEnum[]
}

/**
 * messages create
 */
export type messagesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the messages
   */
  select?: Prisma.messagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the messages
   */
  omit?: Prisma.messagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.messagesInclude<ExtArgs> | null
  /**
   * The data needed to create a messages.
   */
  data: Prisma.XOR<Prisma.messagesCreateInput, Prisma.messagesUncheckedCreateInput>
}

/**
 * messages createMany
 */
export type messagesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many messages.
   */
  data: Prisma.messagesCreateManyInput | Prisma.messagesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * messages createManyAndReturn
 */
export type messagesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the messages
   */
  select?: Prisma.messagesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the messages
   */
  omit?: Prisma.messagesOmit<ExtArgs> | null
  /**
   * The data used to create many messages.
   */
  data: Prisma.messagesCreateManyInput | Prisma.messagesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.messagesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * messages update
 */
export type messagesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the messages
   */
  select?: Prisma.messagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the messages
   */
  omit?: Prisma.messagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.messagesInclude<ExtArgs> | null
  /**
   * The data needed to update a messages.
   */
  data: Prisma.XOR<Prisma.messagesUpdateInput, Prisma.messagesUncheckedUpdateInput>
  /**
   * Choose, which messages to update.
   */
  where: Prisma.messagesWhereUniqueInput
}

/**
 * messages updateMany
 */
export type messagesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update messages.
   */
  data: Prisma.XOR<Prisma.messagesUpdateManyMutationInput, Prisma.messagesUncheckedUpdateManyInput>
  /**
   * Filter which messages to update
   */
  where?: Prisma.messagesWhereInput
  /**
   * Limit how many messages to update.
   */
  limit?: number
}

/**
 * messages updateManyAndReturn
 */
export type messagesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the messages
   */
  select?: Prisma.messagesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the messages
   */
  omit?: Prisma.messagesOmit<ExtArgs> | null
  /**
   * The data used to update messages.
   */
  data: Prisma.XOR<Prisma.messagesUpdateManyMutationInput, Prisma.messagesUncheckedUpdateManyInput>
  /**
   * Filter which messages to update
   */
  where?: Prisma.messagesWhereInput
  /**
   * Limit how many messages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.messagesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * messages upsert
 */
export type messagesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the messages
   */
  select?: Prisma.messagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the messages
   */
  omit?: Prisma.messagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.messagesInclude<ExtArgs> | null
  /**
   * The filter to search for the messages to update in case it exists.
   */
  where: Prisma.messagesWhereUniqueInput
  /**
   * In case the messages found by the `where` argument doesn't exist, create a new messages with this data.
   */
  create: Prisma.XOR<Prisma.messagesCreateInput, Prisma.messagesUncheckedCreateInput>
  /**
   * In case the messages was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.messagesUpdateInput, Prisma.messagesUncheckedUpdateInput>
}

/**
 * messages delete
 */
export type messagesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the messages
   */
  select?: Prisma.messagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the messages
   */
  omit?: Prisma.messagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.messagesInclude<ExtArgs> | null
  /**
   * Filter which messages to delete.
   */
  where: Prisma.messagesWhereUniqueInput
}

/**
 * messages deleteMany
 */
export type messagesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which messages to delete
   */
  where?: Prisma.messagesWhereInput
  /**
   * Limit how many messages to delete.
   */
  limit?: number
}

/**
 * messages without action
 */
export type messagesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the messages
   */
  select?: Prisma.messagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the messages
   */
  omit?: Prisma.messagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.messagesInclude<ExtArgs> | null
}
