
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `produits` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model produits
 * 
 */
export type produitsModel = runtime.Types.Result.DefaultSelection<Prisma.$produitsPayload>

export type AggregateProduits = {
  _count: ProduitsCountAggregateOutputType | null
  _avg: ProduitsAvgAggregateOutputType | null
  _sum: ProduitsSumAggregateOutputType | null
  _min: ProduitsMinAggregateOutputType | null
  _max: ProduitsMaxAggregateOutputType | null
}

export type ProduitsAvgAggregateOutputType = {
  prix: runtime.Decimal | null
  quantite_minimum: number | null
  poids: runtime.Decimal | null
  stock: number | null
  nombre_vues: number | null
  nombre_reservations: number | null
}

export type ProduitsSumAggregateOutputType = {
  prix: runtime.Decimal | null
  quantite_minimum: number | null
  poids: runtime.Decimal | null
  stock: number | null
  nombre_vues: number | null
  nombre_reservations: number | null
}

export type ProduitsMinAggregateOutputType = {
  id: string | null
  categorie_id: string | null
  nom: string | null
  slug: string | null
  description: string | null
  description_courte: string | null
  prix: runtime.Decimal | null
  devise: string | null
  pays_origine: $Enums.pays_enum | null
  quantite_minimum: number | null
  delai_livraison: string | null
  poids: runtime.Decimal | null
  dimensions: string | null
  disponible: boolean | null
  stock: number | null
  nombre_vues: number | null
  nombre_reservations: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type ProduitsMaxAggregateOutputType = {
  id: string | null
  categorie_id: string | null
  nom: string | null
  slug: string | null
  description: string | null
  description_courte: string | null
  prix: runtime.Decimal | null
  devise: string | null
  pays_origine: $Enums.pays_enum | null
  quantite_minimum: number | null
  delai_livraison: string | null
  poids: runtime.Decimal | null
  dimensions: string | null
  disponible: boolean | null
  stock: number | null
  nombre_vues: number | null
  nombre_reservations: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type ProduitsCountAggregateOutputType = {
  id: number
  categorie_id: number
  nom: number
  slug: number
  description: number
  description_courte: number
  prix: number
  devise: number
  pays_origine: number
  quantite_minimum: number
  delai_livraison: number
  poids: number
  dimensions: number
  caracteristiques: number
  disponible: number
  stock: number
  nombre_vues: number
  nombre_reservations: number
  created_at: number
  updated_at: number
  _all: number
}


export type ProduitsAvgAggregateInputType = {
  prix?: true
  quantite_minimum?: true
  poids?: true
  stock?: true
  nombre_vues?: true
  nombre_reservations?: true
}

export type ProduitsSumAggregateInputType = {
  prix?: true
  quantite_minimum?: true
  poids?: true
  stock?: true
  nombre_vues?: true
  nombre_reservations?: true
}

export type ProduitsMinAggregateInputType = {
  id?: true
  categorie_id?: true
  nom?: true
  slug?: true
  description?: true
  description_courte?: true
  prix?: true
  devise?: true
  pays_origine?: true
  quantite_minimum?: true
  delai_livraison?: true
  poids?: true
  dimensions?: true
  disponible?: true
  stock?: true
  nombre_vues?: true
  nombre_reservations?: true
  created_at?: true
  updated_at?: true
}

export type ProduitsMaxAggregateInputType = {
  id?: true
  categorie_id?: true
  nom?: true
  slug?: true
  description?: true
  description_courte?: true
  prix?: true
  devise?: true
  pays_origine?: true
  quantite_minimum?: true
  delai_livraison?: true
  poids?: true
  dimensions?: true
  disponible?: true
  stock?: true
  nombre_vues?: true
  nombre_reservations?: true
  created_at?: true
  updated_at?: true
}

export type ProduitsCountAggregateInputType = {
  id?: true
  categorie_id?: true
  nom?: true
  slug?: true
  description?: true
  description_courte?: true
  prix?: true
  devise?: true
  pays_origine?: true
  quantite_minimum?: true
  delai_livraison?: true
  poids?: true
  dimensions?: true
  caracteristiques?: true
  disponible?: true
  stock?: true
  nombre_vues?: true
  nombre_reservations?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type ProduitsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which produits to aggregate.
   */
  where?: Prisma.produitsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of produits to fetch.
   */
  orderBy?: Prisma.produitsOrderByWithRelationInput | Prisma.produitsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.produitsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` produits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` produits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned produits
  **/
  _count?: true | ProduitsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProduitsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProduitsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProduitsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProduitsMaxAggregateInputType
}

export type GetProduitsAggregateType<T extends ProduitsAggregateArgs> = {
      [P in keyof T & keyof AggregateProduits]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProduits[P]>
    : Prisma.GetScalarType<T[P], AggregateProduits[P]>
}




export type produitsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.produitsWhereInput
  orderBy?: Prisma.produitsOrderByWithAggregationInput | Prisma.produitsOrderByWithAggregationInput[]
  by: Prisma.ProduitsScalarFieldEnum[] | Prisma.ProduitsScalarFieldEnum
  having?: Prisma.produitsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProduitsCountAggregateInputType | true
  _avg?: ProduitsAvgAggregateInputType
  _sum?: ProduitsSumAggregateInputType
  _min?: ProduitsMinAggregateInputType
  _max?: ProduitsMaxAggregateInputType
}

export type ProduitsGroupByOutputType = {
  id: string
  categorie_id: string
  nom: string
  slug: string
  description: string | null
  description_courte: string | null
  prix: runtime.Decimal
  devise: string | null
  pays_origine: $Enums.pays_enum
  quantite_minimum: number | null
  delai_livraison: string | null
  poids: runtime.Decimal | null
  dimensions: string | null
  caracteristiques: runtime.JsonValue | null
  disponible: boolean | null
  stock: number | null
  nombre_vues: number | null
  nombre_reservations: number | null
  created_at: Date | null
  updated_at: Date | null
  _count: ProduitsCountAggregateOutputType | null
  _avg: ProduitsAvgAggregateOutputType | null
  _sum: ProduitsSumAggregateOutputType | null
  _min: ProduitsMinAggregateOutputType | null
  _max: ProduitsMaxAggregateOutputType | null
}

type GetProduitsGroupByPayload<T extends produitsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProduitsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProduitsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProduitsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProduitsGroupByOutputType[P]>
      }
    >
  >



export type produitsWhereInput = {
  AND?: Prisma.produitsWhereInput | Prisma.produitsWhereInput[]
  OR?: Prisma.produitsWhereInput[]
  NOT?: Prisma.produitsWhereInput | Prisma.produitsWhereInput[]
  id?: Prisma.StringFilter<"produits"> | string
  categorie_id?: Prisma.StringFilter<"produits"> | string
  nom?: Prisma.StringFilter<"produits"> | string
  slug?: Prisma.StringFilter<"produits"> | string
  description?: Prisma.StringNullableFilter<"produits"> | string | null
  description_courte?: Prisma.StringNullableFilter<"produits"> | string | null
  prix?: Prisma.DecimalFilter<"produits"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.StringNullableFilter<"produits"> | string | null
  pays_origine?: Prisma.Enumpays_enumFilter<"produits"> | $Enums.pays_enum
  quantite_minimum?: Prisma.IntNullableFilter<"produits"> | number | null
  delai_livraison?: Prisma.StringNullableFilter<"produits"> | string | null
  poids?: Prisma.DecimalNullableFilter<"produits"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.StringNullableFilter<"produits"> | string | null
  caracteristiques?: Prisma.JsonNullableFilter<"produits">
  disponible?: Prisma.BoolNullableFilter<"produits"> | boolean | null
  stock?: Prisma.IntNullableFilter<"produits"> | number | null
  nombre_vues?: Prisma.IntNullableFilter<"produits"> | number | null
  nombre_reservations?: Prisma.IntNullableFilter<"produits"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"produits"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"produits"> | Date | string | null
  categories?: Prisma.XOR<Prisma.CategoriesScalarRelationFilter, Prisma.categoriesWhereInput>
  produits_images?: Prisma.Produits_imagesListRelationFilter
  reservations?: Prisma.ReservationsListRelationFilter
}

export type produitsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  categorie_id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  description_courte?: Prisma.SortOrderInput | Prisma.SortOrder
  prix?: Prisma.SortOrder
  devise?: Prisma.SortOrderInput | Prisma.SortOrder
  pays_origine?: Prisma.SortOrder
  quantite_minimum?: Prisma.SortOrderInput | Prisma.SortOrder
  delai_livraison?: Prisma.SortOrderInput | Prisma.SortOrder
  poids?: Prisma.SortOrderInput | Prisma.SortOrder
  dimensions?: Prisma.SortOrderInput | Prisma.SortOrder
  caracteristiques?: Prisma.SortOrderInput | Prisma.SortOrder
  disponible?: Prisma.SortOrderInput | Prisma.SortOrder
  stock?: Prisma.SortOrderInput | Prisma.SortOrder
  nombre_vues?: Prisma.SortOrderInput | Prisma.SortOrder
  nombre_reservations?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  categories?: Prisma.categoriesOrderByWithRelationInput
  produits_images?: Prisma.produits_imagesOrderByRelationAggregateInput
  reservations?: Prisma.reservationsOrderByRelationAggregateInput
}

export type produitsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.produitsWhereInput | Prisma.produitsWhereInput[]
  OR?: Prisma.produitsWhereInput[]
  NOT?: Prisma.produitsWhereInput | Prisma.produitsWhereInput[]
  categorie_id?: Prisma.StringFilter<"produits"> | string
  nom?: Prisma.StringFilter<"produits"> | string
  description?: Prisma.StringNullableFilter<"produits"> | string | null
  description_courte?: Prisma.StringNullableFilter<"produits"> | string | null
  prix?: Prisma.DecimalFilter<"produits"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.StringNullableFilter<"produits"> | string | null
  pays_origine?: Prisma.Enumpays_enumFilter<"produits"> | $Enums.pays_enum
  quantite_minimum?: Prisma.IntNullableFilter<"produits"> | number | null
  delai_livraison?: Prisma.StringNullableFilter<"produits"> | string | null
  poids?: Prisma.DecimalNullableFilter<"produits"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.StringNullableFilter<"produits"> | string | null
  caracteristiques?: Prisma.JsonNullableFilter<"produits">
  disponible?: Prisma.BoolNullableFilter<"produits"> | boolean | null
  stock?: Prisma.IntNullableFilter<"produits"> | number | null
  nombre_vues?: Prisma.IntNullableFilter<"produits"> | number | null
  nombre_reservations?: Prisma.IntNullableFilter<"produits"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"produits"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"produits"> | Date | string | null
  categories?: Prisma.XOR<Prisma.CategoriesScalarRelationFilter, Prisma.categoriesWhereInput>
  produits_images?: Prisma.Produits_imagesListRelationFilter
  reservations?: Prisma.ReservationsListRelationFilter
}, "id" | "slug">

export type produitsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  categorie_id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  description_courte?: Prisma.SortOrderInput | Prisma.SortOrder
  prix?: Prisma.SortOrder
  devise?: Prisma.SortOrderInput | Prisma.SortOrder
  pays_origine?: Prisma.SortOrder
  quantite_minimum?: Prisma.SortOrderInput | Prisma.SortOrder
  delai_livraison?: Prisma.SortOrderInput | Prisma.SortOrder
  poids?: Prisma.SortOrderInput | Prisma.SortOrder
  dimensions?: Prisma.SortOrderInput | Prisma.SortOrder
  caracteristiques?: Prisma.SortOrderInput | Prisma.SortOrder
  disponible?: Prisma.SortOrderInput | Prisma.SortOrder
  stock?: Prisma.SortOrderInput | Prisma.SortOrder
  nombre_vues?: Prisma.SortOrderInput | Prisma.SortOrder
  nombre_reservations?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.produitsCountOrderByAggregateInput
  _avg?: Prisma.produitsAvgOrderByAggregateInput
  _max?: Prisma.produitsMaxOrderByAggregateInput
  _min?: Prisma.produitsMinOrderByAggregateInput
  _sum?: Prisma.produitsSumOrderByAggregateInput
}

export type produitsScalarWhereWithAggregatesInput = {
  AND?: Prisma.produitsScalarWhereWithAggregatesInput | Prisma.produitsScalarWhereWithAggregatesInput[]
  OR?: Prisma.produitsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.produitsScalarWhereWithAggregatesInput | Prisma.produitsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"produits"> | string
  categorie_id?: Prisma.StringWithAggregatesFilter<"produits"> | string
  nom?: Prisma.StringWithAggregatesFilter<"produits"> | string
  slug?: Prisma.StringWithAggregatesFilter<"produits"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"produits"> | string | null
  description_courte?: Prisma.StringNullableWithAggregatesFilter<"produits"> | string | null
  prix?: Prisma.DecimalWithAggregatesFilter<"produits"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.StringNullableWithAggregatesFilter<"produits"> | string | null
  pays_origine?: Prisma.Enumpays_enumWithAggregatesFilter<"produits"> | $Enums.pays_enum
  quantite_minimum?: Prisma.IntNullableWithAggregatesFilter<"produits"> | number | null
  delai_livraison?: Prisma.StringNullableWithAggregatesFilter<"produits"> | string | null
  poids?: Prisma.DecimalNullableWithAggregatesFilter<"produits"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.StringNullableWithAggregatesFilter<"produits"> | string | null
  caracteristiques?: Prisma.JsonNullableWithAggregatesFilter<"produits">
  disponible?: Prisma.BoolNullableWithAggregatesFilter<"produits"> | boolean | null
  stock?: Prisma.IntNullableWithAggregatesFilter<"produits"> | number | null
  nombre_vues?: Prisma.IntNullableWithAggregatesFilter<"produits"> | number | null
  nombre_reservations?: Prisma.IntNullableWithAggregatesFilter<"produits"> | number | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"produits"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"produits"> | Date | string | null
}

export type produitsCreateInput = {
  id: string
  nom: string
  slug: string
  description?: string | null
  description_courte?: string | null
  prix: runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: string | null
  pays_origine: $Enums.pays_enum
  quantite_minimum?: number | null
  delai_livraison?: string | null
  poids?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: boolean | null
  stock?: number | null
  nombre_vues?: number | null
  nombre_reservations?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  categories: Prisma.categoriesCreateNestedOneWithoutProduitsInput
  produits_images?: Prisma.produits_imagesCreateNestedManyWithoutProduitsInput
  reservations?: Prisma.reservationsCreateNestedManyWithoutProduitsInput
}

export type produitsUncheckedCreateInput = {
  id: string
  categorie_id: string
  nom: string
  slug: string
  description?: string | null
  description_courte?: string | null
  prix: runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: string | null
  pays_origine: $Enums.pays_enum
  quantite_minimum?: number | null
  delai_livraison?: string | null
  poids?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: boolean | null
  stock?: number | null
  nombre_vues?: number | null
  nombre_reservations?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  produits_images?: Prisma.produits_imagesUncheckedCreateNestedManyWithoutProduitsInput
  reservations?: Prisma.reservationsUncheckedCreateNestedManyWithoutProduitsInput
}

export type produitsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description_courte?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prix?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pays_origine?: Prisma.Enumpays_enumFieldUpdateOperationsInput | $Enums.pays_enum
  quantite_minimum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  delai_livraison?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  poids?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_vues?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_reservations?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.categoriesUpdateOneRequiredWithoutProduitsNestedInput
  produits_images?: Prisma.produits_imagesUpdateManyWithoutProduitsNestedInput
  reservations?: Prisma.reservationsUpdateManyWithoutProduitsNestedInput
}

export type produitsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categorie_id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description_courte?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prix?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pays_origine?: Prisma.Enumpays_enumFieldUpdateOperationsInput | $Enums.pays_enum
  quantite_minimum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  delai_livraison?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  poids?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_vues?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_reservations?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  produits_images?: Prisma.produits_imagesUncheckedUpdateManyWithoutProduitsNestedInput
  reservations?: Prisma.reservationsUncheckedUpdateManyWithoutProduitsNestedInput
}

export type produitsCreateManyInput = {
  id: string
  categorie_id: string
  nom: string
  slug: string
  description?: string | null
  description_courte?: string | null
  prix: runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: string | null
  pays_origine: $Enums.pays_enum
  quantite_minimum?: number | null
  delai_livraison?: string | null
  poids?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: boolean | null
  stock?: number | null
  nombre_vues?: number | null
  nombre_reservations?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type produitsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description_courte?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prix?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pays_origine?: Prisma.Enumpays_enumFieldUpdateOperationsInput | $Enums.pays_enum
  quantite_minimum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  delai_livraison?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  poids?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_vues?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_reservations?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type produitsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categorie_id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description_courte?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prix?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pays_origine?: Prisma.Enumpays_enumFieldUpdateOperationsInput | $Enums.pays_enum
  quantite_minimum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  delai_livraison?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  poids?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_vues?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_reservations?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ProduitsListRelationFilter = {
  every?: Prisma.produitsWhereInput
  some?: Prisma.produitsWhereInput
  none?: Prisma.produitsWhereInput
}

export type produitsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type produitsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  categorie_id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  description_courte?: Prisma.SortOrder
  prix?: Prisma.SortOrder
  devise?: Prisma.SortOrder
  pays_origine?: Prisma.SortOrder
  quantite_minimum?: Prisma.SortOrder
  delai_livraison?: Prisma.SortOrder
  poids?: Prisma.SortOrder
  dimensions?: Prisma.SortOrder
  caracteristiques?: Prisma.SortOrder
  disponible?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  nombre_vues?: Prisma.SortOrder
  nombre_reservations?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type produitsAvgOrderByAggregateInput = {
  prix?: Prisma.SortOrder
  quantite_minimum?: Prisma.SortOrder
  poids?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  nombre_vues?: Prisma.SortOrder
  nombre_reservations?: Prisma.SortOrder
}

export type produitsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  categorie_id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  description_courte?: Prisma.SortOrder
  prix?: Prisma.SortOrder
  devise?: Prisma.SortOrder
  pays_origine?: Prisma.SortOrder
  quantite_minimum?: Prisma.SortOrder
  delai_livraison?: Prisma.SortOrder
  poids?: Prisma.SortOrder
  dimensions?: Prisma.SortOrder
  disponible?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  nombre_vues?: Prisma.SortOrder
  nombre_reservations?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type produitsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  categorie_id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  description_courte?: Prisma.SortOrder
  prix?: Prisma.SortOrder
  devise?: Prisma.SortOrder
  pays_origine?: Prisma.SortOrder
  quantite_minimum?: Prisma.SortOrder
  delai_livraison?: Prisma.SortOrder
  poids?: Prisma.SortOrder
  dimensions?: Prisma.SortOrder
  disponible?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  nombre_vues?: Prisma.SortOrder
  nombre_reservations?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type produitsSumOrderByAggregateInput = {
  prix?: Prisma.SortOrder
  quantite_minimum?: Prisma.SortOrder
  poids?: Prisma.SortOrder
  stock?: Prisma.SortOrder
  nombre_vues?: Prisma.SortOrder
  nombre_reservations?: Prisma.SortOrder
}

export type ProduitsScalarRelationFilter = {
  is?: Prisma.produitsWhereInput
  isNot?: Prisma.produitsWhereInput
}

export type produitsCreateNestedManyWithoutCategoriesInput = {
  create?: Prisma.XOR<Prisma.produitsCreateWithoutCategoriesInput, Prisma.produitsUncheckedCreateWithoutCategoriesInput> | Prisma.produitsCreateWithoutCategoriesInput[] | Prisma.produitsUncheckedCreateWithoutCategoriesInput[]
  connectOrCreate?: Prisma.produitsCreateOrConnectWithoutCategoriesInput | Prisma.produitsCreateOrConnectWithoutCategoriesInput[]
  createMany?: Prisma.produitsCreateManyCategoriesInputEnvelope
  connect?: Prisma.produitsWhereUniqueInput | Prisma.produitsWhereUniqueInput[]
}

export type produitsUncheckedCreateNestedManyWithoutCategoriesInput = {
  create?: Prisma.XOR<Prisma.produitsCreateWithoutCategoriesInput, Prisma.produitsUncheckedCreateWithoutCategoriesInput> | Prisma.produitsCreateWithoutCategoriesInput[] | Prisma.produitsUncheckedCreateWithoutCategoriesInput[]
  connectOrCreate?: Prisma.produitsCreateOrConnectWithoutCategoriesInput | Prisma.produitsCreateOrConnectWithoutCategoriesInput[]
  createMany?: Prisma.produitsCreateManyCategoriesInputEnvelope
  connect?: Prisma.produitsWhereUniqueInput | Prisma.produitsWhereUniqueInput[]
}

export type produitsUpdateManyWithoutCategoriesNestedInput = {
  create?: Prisma.XOR<Prisma.produitsCreateWithoutCategoriesInput, Prisma.produitsUncheckedCreateWithoutCategoriesInput> | Prisma.produitsCreateWithoutCategoriesInput[] | Prisma.produitsUncheckedCreateWithoutCategoriesInput[]
  connectOrCreate?: Prisma.produitsCreateOrConnectWithoutCategoriesInput | Prisma.produitsCreateOrConnectWithoutCategoriesInput[]
  upsert?: Prisma.produitsUpsertWithWhereUniqueWithoutCategoriesInput | Prisma.produitsUpsertWithWhereUniqueWithoutCategoriesInput[]
  createMany?: Prisma.produitsCreateManyCategoriesInputEnvelope
  set?: Prisma.produitsWhereUniqueInput | Prisma.produitsWhereUniqueInput[]
  disconnect?: Prisma.produitsWhereUniqueInput | Prisma.produitsWhereUniqueInput[]
  delete?: Prisma.produitsWhereUniqueInput | Prisma.produitsWhereUniqueInput[]
  connect?: Prisma.produitsWhereUniqueInput | Prisma.produitsWhereUniqueInput[]
  update?: Prisma.produitsUpdateWithWhereUniqueWithoutCategoriesInput | Prisma.produitsUpdateWithWhereUniqueWithoutCategoriesInput[]
  updateMany?: Prisma.produitsUpdateManyWithWhereWithoutCategoriesInput | Prisma.produitsUpdateManyWithWhereWithoutCategoriesInput[]
  deleteMany?: Prisma.produitsScalarWhereInput | Prisma.produitsScalarWhereInput[]
}

export type produitsUncheckedUpdateManyWithoutCategoriesNestedInput = {
  create?: Prisma.XOR<Prisma.produitsCreateWithoutCategoriesInput, Prisma.produitsUncheckedCreateWithoutCategoriesInput> | Prisma.produitsCreateWithoutCategoriesInput[] | Prisma.produitsUncheckedCreateWithoutCategoriesInput[]
  connectOrCreate?: Prisma.produitsCreateOrConnectWithoutCategoriesInput | Prisma.produitsCreateOrConnectWithoutCategoriesInput[]
  upsert?: Prisma.produitsUpsertWithWhereUniqueWithoutCategoriesInput | Prisma.produitsUpsertWithWhereUniqueWithoutCategoriesInput[]
  createMany?: Prisma.produitsCreateManyCategoriesInputEnvelope
  set?: Prisma.produitsWhereUniqueInput | Prisma.produitsWhereUniqueInput[]
  disconnect?: Prisma.produitsWhereUniqueInput | Prisma.produitsWhereUniqueInput[]
  delete?: Prisma.produitsWhereUniqueInput | Prisma.produitsWhereUniqueInput[]
  connect?: Prisma.produitsWhereUniqueInput | Prisma.produitsWhereUniqueInput[]
  update?: Prisma.produitsUpdateWithWhereUniqueWithoutCategoriesInput | Prisma.produitsUpdateWithWhereUniqueWithoutCategoriesInput[]
  updateMany?: Prisma.produitsUpdateManyWithWhereWithoutCategoriesInput | Prisma.produitsUpdateManyWithWhereWithoutCategoriesInput[]
  deleteMany?: Prisma.produitsScalarWhereInput | Prisma.produitsScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type Enumpays_enumFieldUpdateOperationsInput = {
  set?: $Enums.pays_enum
}

export type produitsCreateNestedOneWithoutProduits_imagesInput = {
  create?: Prisma.XOR<Prisma.produitsCreateWithoutProduits_imagesInput, Prisma.produitsUncheckedCreateWithoutProduits_imagesInput>
  connectOrCreate?: Prisma.produitsCreateOrConnectWithoutProduits_imagesInput
  connect?: Prisma.produitsWhereUniqueInput
}

export type produitsUpdateOneRequiredWithoutProduits_imagesNestedInput = {
  create?: Prisma.XOR<Prisma.produitsCreateWithoutProduits_imagesInput, Prisma.produitsUncheckedCreateWithoutProduits_imagesInput>
  connectOrCreate?: Prisma.produitsCreateOrConnectWithoutProduits_imagesInput
  upsert?: Prisma.produitsUpsertWithoutProduits_imagesInput
  connect?: Prisma.produitsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.produitsUpdateToOneWithWhereWithoutProduits_imagesInput, Prisma.produitsUpdateWithoutProduits_imagesInput>, Prisma.produitsUncheckedUpdateWithoutProduits_imagesInput>
}

export type produitsCreateNestedOneWithoutReservationsInput = {
  create?: Prisma.XOR<Prisma.produitsCreateWithoutReservationsInput, Prisma.produitsUncheckedCreateWithoutReservationsInput>
  connectOrCreate?: Prisma.produitsCreateOrConnectWithoutReservationsInput
  connect?: Prisma.produitsWhereUniqueInput
}

export type produitsUpdateOneRequiredWithoutReservationsNestedInput = {
  create?: Prisma.XOR<Prisma.produitsCreateWithoutReservationsInput, Prisma.produitsUncheckedCreateWithoutReservationsInput>
  connectOrCreate?: Prisma.produitsCreateOrConnectWithoutReservationsInput
  upsert?: Prisma.produitsUpsertWithoutReservationsInput
  connect?: Prisma.produitsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.produitsUpdateToOneWithWhereWithoutReservationsInput, Prisma.produitsUpdateWithoutReservationsInput>, Prisma.produitsUncheckedUpdateWithoutReservationsInput>
}

export type produitsCreateWithoutCategoriesInput = {
  id: string
  nom: string
  slug: string
  description?: string | null
  description_courte?: string | null
  prix: runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: string | null
  pays_origine: $Enums.pays_enum
  quantite_minimum?: number | null
  delai_livraison?: string | null
  poids?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: boolean | null
  stock?: number | null
  nombre_vues?: number | null
  nombre_reservations?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  produits_images?: Prisma.produits_imagesCreateNestedManyWithoutProduitsInput
  reservations?: Prisma.reservationsCreateNestedManyWithoutProduitsInput
}

export type produitsUncheckedCreateWithoutCategoriesInput = {
  id: string
  nom: string
  slug: string
  description?: string | null
  description_courte?: string | null
  prix: runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: string | null
  pays_origine: $Enums.pays_enum
  quantite_minimum?: number | null
  delai_livraison?: string | null
  poids?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: boolean | null
  stock?: number | null
  nombre_vues?: number | null
  nombre_reservations?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  produits_images?: Prisma.produits_imagesUncheckedCreateNestedManyWithoutProduitsInput
  reservations?: Prisma.reservationsUncheckedCreateNestedManyWithoutProduitsInput
}

export type produitsCreateOrConnectWithoutCategoriesInput = {
  where: Prisma.produitsWhereUniqueInput
  create: Prisma.XOR<Prisma.produitsCreateWithoutCategoriesInput, Prisma.produitsUncheckedCreateWithoutCategoriesInput>
}

export type produitsCreateManyCategoriesInputEnvelope = {
  data: Prisma.produitsCreateManyCategoriesInput | Prisma.produitsCreateManyCategoriesInput[]
  skipDuplicates?: boolean
}

export type produitsUpsertWithWhereUniqueWithoutCategoriesInput = {
  where: Prisma.produitsWhereUniqueInput
  update: Prisma.XOR<Prisma.produitsUpdateWithoutCategoriesInput, Prisma.produitsUncheckedUpdateWithoutCategoriesInput>
  create: Prisma.XOR<Prisma.produitsCreateWithoutCategoriesInput, Prisma.produitsUncheckedCreateWithoutCategoriesInput>
}

export type produitsUpdateWithWhereUniqueWithoutCategoriesInput = {
  where: Prisma.produitsWhereUniqueInput
  data: Prisma.XOR<Prisma.produitsUpdateWithoutCategoriesInput, Prisma.produitsUncheckedUpdateWithoutCategoriesInput>
}

export type produitsUpdateManyWithWhereWithoutCategoriesInput = {
  where: Prisma.produitsScalarWhereInput
  data: Prisma.XOR<Prisma.produitsUpdateManyMutationInput, Prisma.produitsUncheckedUpdateManyWithoutCategoriesInput>
}

export type produitsScalarWhereInput = {
  AND?: Prisma.produitsScalarWhereInput | Prisma.produitsScalarWhereInput[]
  OR?: Prisma.produitsScalarWhereInput[]
  NOT?: Prisma.produitsScalarWhereInput | Prisma.produitsScalarWhereInput[]
  id?: Prisma.StringFilter<"produits"> | string
  categorie_id?: Prisma.StringFilter<"produits"> | string
  nom?: Prisma.StringFilter<"produits"> | string
  slug?: Prisma.StringFilter<"produits"> | string
  description?: Prisma.StringNullableFilter<"produits"> | string | null
  description_courte?: Prisma.StringNullableFilter<"produits"> | string | null
  prix?: Prisma.DecimalFilter<"produits"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.StringNullableFilter<"produits"> | string | null
  pays_origine?: Prisma.Enumpays_enumFilter<"produits"> | $Enums.pays_enum
  quantite_minimum?: Prisma.IntNullableFilter<"produits"> | number | null
  delai_livraison?: Prisma.StringNullableFilter<"produits"> | string | null
  poids?: Prisma.DecimalNullableFilter<"produits"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.StringNullableFilter<"produits"> | string | null
  caracteristiques?: Prisma.JsonNullableFilter<"produits">
  disponible?: Prisma.BoolNullableFilter<"produits"> | boolean | null
  stock?: Prisma.IntNullableFilter<"produits"> | number | null
  nombre_vues?: Prisma.IntNullableFilter<"produits"> | number | null
  nombre_reservations?: Prisma.IntNullableFilter<"produits"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"produits"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"produits"> | Date | string | null
}

export type produitsCreateWithoutProduits_imagesInput = {
  id: string
  nom: string
  slug: string
  description?: string | null
  description_courte?: string | null
  prix: runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: string | null
  pays_origine: $Enums.pays_enum
  quantite_minimum?: number | null
  delai_livraison?: string | null
  poids?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: boolean | null
  stock?: number | null
  nombre_vues?: number | null
  nombre_reservations?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  categories: Prisma.categoriesCreateNestedOneWithoutProduitsInput
  reservations?: Prisma.reservationsCreateNestedManyWithoutProduitsInput
}

export type produitsUncheckedCreateWithoutProduits_imagesInput = {
  id: string
  categorie_id: string
  nom: string
  slug: string
  description?: string | null
  description_courte?: string | null
  prix: runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: string | null
  pays_origine: $Enums.pays_enum
  quantite_minimum?: number | null
  delai_livraison?: string | null
  poids?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: boolean | null
  stock?: number | null
  nombre_vues?: number | null
  nombre_reservations?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  reservations?: Prisma.reservationsUncheckedCreateNestedManyWithoutProduitsInput
}

export type produitsCreateOrConnectWithoutProduits_imagesInput = {
  where: Prisma.produitsWhereUniqueInput
  create: Prisma.XOR<Prisma.produitsCreateWithoutProduits_imagesInput, Prisma.produitsUncheckedCreateWithoutProduits_imagesInput>
}

export type produitsUpsertWithoutProduits_imagesInput = {
  update: Prisma.XOR<Prisma.produitsUpdateWithoutProduits_imagesInput, Prisma.produitsUncheckedUpdateWithoutProduits_imagesInput>
  create: Prisma.XOR<Prisma.produitsCreateWithoutProduits_imagesInput, Prisma.produitsUncheckedCreateWithoutProduits_imagesInput>
  where?: Prisma.produitsWhereInput
}

export type produitsUpdateToOneWithWhereWithoutProduits_imagesInput = {
  where?: Prisma.produitsWhereInput
  data: Prisma.XOR<Prisma.produitsUpdateWithoutProduits_imagesInput, Prisma.produitsUncheckedUpdateWithoutProduits_imagesInput>
}

export type produitsUpdateWithoutProduits_imagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description_courte?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prix?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pays_origine?: Prisma.Enumpays_enumFieldUpdateOperationsInput | $Enums.pays_enum
  quantite_minimum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  delai_livraison?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  poids?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_vues?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_reservations?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.categoriesUpdateOneRequiredWithoutProduitsNestedInput
  reservations?: Prisma.reservationsUpdateManyWithoutProduitsNestedInput
}

export type produitsUncheckedUpdateWithoutProduits_imagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categorie_id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description_courte?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prix?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pays_origine?: Prisma.Enumpays_enumFieldUpdateOperationsInput | $Enums.pays_enum
  quantite_minimum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  delai_livraison?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  poids?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_vues?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_reservations?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reservations?: Prisma.reservationsUncheckedUpdateManyWithoutProduitsNestedInput
}

export type produitsCreateWithoutReservationsInput = {
  id: string
  nom: string
  slug: string
  description?: string | null
  description_courte?: string | null
  prix: runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: string | null
  pays_origine: $Enums.pays_enum
  quantite_minimum?: number | null
  delai_livraison?: string | null
  poids?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: boolean | null
  stock?: number | null
  nombre_vues?: number | null
  nombre_reservations?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  categories: Prisma.categoriesCreateNestedOneWithoutProduitsInput
  produits_images?: Prisma.produits_imagesCreateNestedManyWithoutProduitsInput
}

export type produitsUncheckedCreateWithoutReservationsInput = {
  id: string
  categorie_id: string
  nom: string
  slug: string
  description?: string | null
  description_courte?: string | null
  prix: runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: string | null
  pays_origine: $Enums.pays_enum
  quantite_minimum?: number | null
  delai_livraison?: string | null
  poids?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: boolean | null
  stock?: number | null
  nombre_vues?: number | null
  nombre_reservations?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  produits_images?: Prisma.produits_imagesUncheckedCreateNestedManyWithoutProduitsInput
}

export type produitsCreateOrConnectWithoutReservationsInput = {
  where: Prisma.produitsWhereUniqueInput
  create: Prisma.XOR<Prisma.produitsCreateWithoutReservationsInput, Prisma.produitsUncheckedCreateWithoutReservationsInput>
}

export type produitsUpsertWithoutReservationsInput = {
  update: Prisma.XOR<Prisma.produitsUpdateWithoutReservationsInput, Prisma.produitsUncheckedUpdateWithoutReservationsInput>
  create: Prisma.XOR<Prisma.produitsCreateWithoutReservationsInput, Prisma.produitsUncheckedCreateWithoutReservationsInput>
  where?: Prisma.produitsWhereInput
}

export type produitsUpdateToOneWithWhereWithoutReservationsInput = {
  where?: Prisma.produitsWhereInput
  data: Prisma.XOR<Prisma.produitsUpdateWithoutReservationsInput, Prisma.produitsUncheckedUpdateWithoutReservationsInput>
}

export type produitsUpdateWithoutReservationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description_courte?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prix?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pays_origine?: Prisma.Enumpays_enumFieldUpdateOperationsInput | $Enums.pays_enum
  quantite_minimum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  delai_livraison?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  poids?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_vues?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_reservations?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.categoriesUpdateOneRequiredWithoutProduitsNestedInput
  produits_images?: Prisma.produits_imagesUpdateManyWithoutProduitsNestedInput
}

export type produitsUncheckedUpdateWithoutReservationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categorie_id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description_courte?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prix?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pays_origine?: Prisma.Enumpays_enumFieldUpdateOperationsInput | $Enums.pays_enum
  quantite_minimum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  delai_livraison?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  poids?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_vues?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_reservations?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  produits_images?: Prisma.produits_imagesUncheckedUpdateManyWithoutProduitsNestedInput
}

export type produitsCreateManyCategoriesInput = {
  id: string
  nom: string
  slug: string
  description?: string | null
  description_courte?: string | null
  prix: runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: string | null
  pays_origine: $Enums.pays_enum
  quantite_minimum?: number | null
  delai_livraison?: string | null
  poids?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: boolean | null
  stock?: number | null
  nombre_vues?: number | null
  nombre_reservations?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type produitsUpdateWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description_courte?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prix?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pays_origine?: Prisma.Enumpays_enumFieldUpdateOperationsInput | $Enums.pays_enum
  quantite_minimum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  delai_livraison?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  poids?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_vues?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_reservations?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  produits_images?: Prisma.produits_imagesUpdateManyWithoutProduitsNestedInput
  reservations?: Prisma.reservationsUpdateManyWithoutProduitsNestedInput
}

export type produitsUncheckedUpdateWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description_courte?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prix?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pays_origine?: Prisma.Enumpays_enumFieldUpdateOperationsInput | $Enums.pays_enum
  quantite_minimum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  delai_livraison?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  poids?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_vues?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_reservations?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  produits_images?: Prisma.produits_imagesUncheckedUpdateManyWithoutProduitsNestedInput
  reservations?: Prisma.reservationsUncheckedUpdateManyWithoutProduitsNestedInput
}

export type produitsUncheckedUpdateManyWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description_courte?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prix?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  devise?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pays_origine?: Prisma.Enumpays_enumFieldUpdateOperationsInput | $Enums.pays_enum
  quantite_minimum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  delai_livraison?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  poids?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dimensions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caracteristiques?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  disponible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  stock?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_vues?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nombre_reservations?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type ProduitsCountOutputType
 */

export type ProduitsCountOutputType = {
  produits_images: number
  reservations: number
}

export type ProduitsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  produits_images?: boolean | ProduitsCountOutputTypeCountProduits_imagesArgs
  reservations?: boolean | ProduitsCountOutputTypeCountReservationsArgs
}

/**
 * ProduitsCountOutputType without action
 */
export type ProduitsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProduitsCountOutputType
   */
  select?: Prisma.ProduitsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProduitsCountOutputType without action
 */
export type ProduitsCountOutputTypeCountProduits_imagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.produits_imagesWhereInput
}

/**
 * ProduitsCountOutputType without action
 */
export type ProduitsCountOutputTypeCountReservationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.reservationsWhereInput
}


export type produitsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  categorie_id?: boolean
  nom?: boolean
  slug?: boolean
  description?: boolean
  description_courte?: boolean
  prix?: boolean
  devise?: boolean
  pays_origine?: boolean
  quantite_minimum?: boolean
  delai_livraison?: boolean
  poids?: boolean
  dimensions?: boolean
  caracteristiques?: boolean
  disponible?: boolean
  stock?: boolean
  nombre_vues?: boolean
  nombre_reservations?: boolean
  created_at?: boolean
  updated_at?: boolean
  categories?: boolean | Prisma.categoriesDefaultArgs<ExtArgs>
  produits_images?: boolean | Prisma.produits$produits_imagesArgs<ExtArgs>
  reservations?: boolean | Prisma.produits$reservationsArgs<ExtArgs>
  _count?: boolean | Prisma.ProduitsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["produits"]>

export type produitsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  categorie_id?: boolean
  nom?: boolean
  slug?: boolean
  description?: boolean
  description_courte?: boolean
  prix?: boolean
  devise?: boolean
  pays_origine?: boolean
  quantite_minimum?: boolean
  delai_livraison?: boolean
  poids?: boolean
  dimensions?: boolean
  caracteristiques?: boolean
  disponible?: boolean
  stock?: boolean
  nombre_vues?: boolean
  nombre_reservations?: boolean
  created_at?: boolean
  updated_at?: boolean
  categories?: boolean | Prisma.categoriesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["produits"]>

export type produitsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  categorie_id?: boolean
  nom?: boolean
  slug?: boolean
  description?: boolean
  description_courte?: boolean
  prix?: boolean
  devise?: boolean
  pays_origine?: boolean
  quantite_minimum?: boolean
  delai_livraison?: boolean
  poids?: boolean
  dimensions?: boolean
  caracteristiques?: boolean
  disponible?: boolean
  stock?: boolean
  nombre_vues?: boolean
  nombre_reservations?: boolean
  created_at?: boolean
  updated_at?: boolean
  categories?: boolean | Prisma.categoriesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["produits"]>

export type produitsSelectScalar = {
  id?: boolean
  categorie_id?: boolean
  nom?: boolean
  slug?: boolean
  description?: boolean
  description_courte?: boolean
  prix?: boolean
  devise?: boolean
  pays_origine?: boolean
  quantite_minimum?: boolean
  delai_livraison?: boolean
  poids?: boolean
  dimensions?: boolean
  caracteristiques?: boolean
  disponible?: boolean
  stock?: boolean
  nombre_vues?: boolean
  nombre_reservations?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type produitsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "categorie_id" | "nom" | "slug" | "description" | "description_courte" | "prix" | "devise" | "pays_origine" | "quantite_minimum" | "delai_livraison" | "poids" | "dimensions" | "caracteristiques" | "disponible" | "stock" | "nombre_vues" | "nombre_reservations" | "created_at" | "updated_at", ExtArgs["result"]["produits"]>
export type produitsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  categories?: boolean | Prisma.categoriesDefaultArgs<ExtArgs>
  produits_images?: boolean | Prisma.produits$produits_imagesArgs<ExtArgs>
  reservations?: boolean | Prisma.produits$reservationsArgs<ExtArgs>
  _count?: boolean | Prisma.ProduitsCountOutputTypeDefaultArgs<ExtArgs>
}
export type produitsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  categories?: boolean | Prisma.categoriesDefaultArgs<ExtArgs>
}
export type produitsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  categories?: boolean | Prisma.categoriesDefaultArgs<ExtArgs>
}

export type $produitsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "produits"
  objects: {
    categories: Prisma.$categoriesPayload<ExtArgs>
    produits_images: Prisma.$produits_imagesPayload<ExtArgs>[]
    reservations: Prisma.$reservationsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    categorie_id: string
    nom: string
    slug: string
    description: string | null
    description_courte: string | null
    prix: runtime.Decimal
    devise: string | null
    pays_origine: $Enums.pays_enum
    quantite_minimum: number | null
    delai_livraison: string | null
    poids: runtime.Decimal | null
    dimensions: string | null
    caracteristiques: runtime.JsonValue | null
    disponible: boolean | null
    stock: number | null
    nombre_vues: number | null
    nombre_reservations: number | null
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["produits"]>
  composites: {}
}

export type produitsGetPayload<S extends boolean | null | undefined | produitsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$produitsPayload, S>

export type produitsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<produitsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProduitsCountAggregateInputType | true
  }

export interface produitsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['produits'], meta: { name: 'produits' } }
  /**
   * Find zero or one Produits that matches the filter.
   * @param {produitsFindUniqueArgs} args - Arguments to find a Produits
   * @example
   * // Get one Produits
   * const produits = await prisma.produits.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends produitsFindUniqueArgs>(args: Prisma.SelectSubset<T, produitsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__produitsClient<runtime.Types.Result.GetResult<Prisma.$produitsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Produits that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {produitsFindUniqueOrThrowArgs} args - Arguments to find a Produits
   * @example
   * // Get one Produits
   * const produits = await prisma.produits.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends produitsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, produitsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__produitsClient<runtime.Types.Result.GetResult<Prisma.$produitsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Produits that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {produitsFindFirstArgs} args - Arguments to find a Produits
   * @example
   * // Get one Produits
   * const produits = await prisma.produits.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends produitsFindFirstArgs>(args?: Prisma.SelectSubset<T, produitsFindFirstArgs<ExtArgs>>): Prisma.Prisma__produitsClient<runtime.Types.Result.GetResult<Prisma.$produitsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Produits that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {produitsFindFirstOrThrowArgs} args - Arguments to find a Produits
   * @example
   * // Get one Produits
   * const produits = await prisma.produits.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends produitsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, produitsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__produitsClient<runtime.Types.Result.GetResult<Prisma.$produitsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Produits that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {produitsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Produits
   * const produits = await prisma.produits.findMany()
   * 
   * // Get first 10 Produits
   * const produits = await prisma.produits.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const produitsWithIdOnly = await prisma.produits.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends produitsFindManyArgs>(args?: Prisma.SelectSubset<T, produitsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$produitsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Produits.
   * @param {produitsCreateArgs} args - Arguments to create a Produits.
   * @example
   * // Create one Produits
   * const Produits = await prisma.produits.create({
   *   data: {
   *     // ... data to create a Produits
   *   }
   * })
   * 
   */
  create<T extends produitsCreateArgs>(args: Prisma.SelectSubset<T, produitsCreateArgs<ExtArgs>>): Prisma.Prisma__produitsClient<runtime.Types.Result.GetResult<Prisma.$produitsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Produits.
   * @param {produitsCreateManyArgs} args - Arguments to create many Produits.
   * @example
   * // Create many Produits
   * const produits = await prisma.produits.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends produitsCreateManyArgs>(args?: Prisma.SelectSubset<T, produitsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Produits and returns the data saved in the database.
   * @param {produitsCreateManyAndReturnArgs} args - Arguments to create many Produits.
   * @example
   * // Create many Produits
   * const produits = await prisma.produits.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Produits and only return the `id`
   * const produitsWithIdOnly = await prisma.produits.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends produitsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, produitsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$produitsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Produits.
   * @param {produitsDeleteArgs} args - Arguments to delete one Produits.
   * @example
   * // Delete one Produits
   * const Produits = await prisma.produits.delete({
   *   where: {
   *     // ... filter to delete one Produits
   *   }
   * })
   * 
   */
  delete<T extends produitsDeleteArgs>(args: Prisma.SelectSubset<T, produitsDeleteArgs<ExtArgs>>): Prisma.Prisma__produitsClient<runtime.Types.Result.GetResult<Prisma.$produitsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Produits.
   * @param {produitsUpdateArgs} args - Arguments to update one Produits.
   * @example
   * // Update one Produits
   * const produits = await prisma.produits.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends produitsUpdateArgs>(args: Prisma.SelectSubset<T, produitsUpdateArgs<ExtArgs>>): Prisma.Prisma__produitsClient<runtime.Types.Result.GetResult<Prisma.$produitsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Produits.
   * @param {produitsDeleteManyArgs} args - Arguments to filter Produits to delete.
   * @example
   * // Delete a few Produits
   * const { count } = await prisma.produits.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends produitsDeleteManyArgs>(args?: Prisma.SelectSubset<T, produitsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Produits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {produitsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Produits
   * const produits = await prisma.produits.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends produitsUpdateManyArgs>(args: Prisma.SelectSubset<T, produitsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Produits and returns the data updated in the database.
   * @param {produitsUpdateManyAndReturnArgs} args - Arguments to update many Produits.
   * @example
   * // Update many Produits
   * const produits = await prisma.produits.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Produits and only return the `id`
   * const produitsWithIdOnly = await prisma.produits.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends produitsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, produitsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$produitsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Produits.
   * @param {produitsUpsertArgs} args - Arguments to update or create a Produits.
   * @example
   * // Update or create a Produits
   * const produits = await prisma.produits.upsert({
   *   create: {
   *     // ... data to create a Produits
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Produits we want to update
   *   }
   * })
   */
  upsert<T extends produitsUpsertArgs>(args: Prisma.SelectSubset<T, produitsUpsertArgs<ExtArgs>>): Prisma.Prisma__produitsClient<runtime.Types.Result.GetResult<Prisma.$produitsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Produits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {produitsCountArgs} args - Arguments to filter Produits to count.
   * @example
   * // Count the number of Produits
   * const count = await prisma.produits.count({
   *   where: {
   *     // ... the filter for the Produits we want to count
   *   }
   * })
  **/
  count<T extends produitsCountArgs>(
    args?: Prisma.Subset<T, produitsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProduitsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Produits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProduitsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProduitsAggregateArgs>(args: Prisma.Subset<T, ProduitsAggregateArgs>): Prisma.PrismaPromise<GetProduitsAggregateType<T>>

  /**
   * Group by Produits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {produitsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends produitsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: produitsGroupByArgs['orderBy'] }
      : { orderBy?: produitsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, produitsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProduitsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the produits model
 */
readonly fields: produitsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for produits.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__produitsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  categories<T extends Prisma.categoriesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.categoriesDefaultArgs<ExtArgs>>): Prisma.Prisma__categoriesClient<runtime.Types.Result.GetResult<Prisma.$categoriesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  produits_images<T extends Prisma.produits$produits_imagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.produits$produits_imagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$produits_imagesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  reservations<T extends Prisma.produits$reservationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.produits$reservationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reservationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the produits model
 */
export interface produitsFieldRefs {
  readonly id: Prisma.FieldRef<"produits", 'String'>
  readonly categorie_id: Prisma.FieldRef<"produits", 'String'>
  readonly nom: Prisma.FieldRef<"produits", 'String'>
  readonly slug: Prisma.FieldRef<"produits", 'String'>
  readonly description: Prisma.FieldRef<"produits", 'String'>
  readonly description_courte: Prisma.FieldRef<"produits", 'String'>
  readonly prix: Prisma.FieldRef<"produits", 'Decimal'>
  readonly devise: Prisma.FieldRef<"produits", 'String'>
  readonly pays_origine: Prisma.FieldRef<"produits", 'pays_enum'>
  readonly quantite_minimum: Prisma.FieldRef<"produits", 'Int'>
  readonly delai_livraison: Prisma.FieldRef<"produits", 'String'>
  readonly poids: Prisma.FieldRef<"produits", 'Decimal'>
  readonly dimensions: Prisma.FieldRef<"produits", 'String'>
  readonly caracteristiques: Prisma.FieldRef<"produits", 'Json'>
  readonly disponible: Prisma.FieldRef<"produits", 'Boolean'>
  readonly stock: Prisma.FieldRef<"produits", 'Int'>
  readonly nombre_vues: Prisma.FieldRef<"produits", 'Int'>
  readonly nombre_reservations: Prisma.FieldRef<"produits", 'Int'>
  readonly created_at: Prisma.FieldRef<"produits", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"produits", 'DateTime'>
}
    

// Custom InputTypes
/**
 * produits findUnique
 */
export type produitsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits
   */
  select?: Prisma.produitsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produits
   */
  omit?: Prisma.produitsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produitsInclude<ExtArgs> | null
  /**
   * Filter, which produits to fetch.
   */
  where: Prisma.produitsWhereUniqueInput
}

/**
 * produits findUniqueOrThrow
 */
export type produitsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits
   */
  select?: Prisma.produitsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produits
   */
  omit?: Prisma.produitsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produitsInclude<ExtArgs> | null
  /**
   * Filter, which produits to fetch.
   */
  where: Prisma.produitsWhereUniqueInput
}

/**
 * produits findFirst
 */
export type produitsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits
   */
  select?: Prisma.produitsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produits
   */
  omit?: Prisma.produitsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produitsInclude<ExtArgs> | null
  /**
   * Filter, which produits to fetch.
   */
  where?: Prisma.produitsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of produits to fetch.
   */
  orderBy?: Prisma.produitsOrderByWithRelationInput | Prisma.produitsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for produits.
   */
  cursor?: Prisma.produitsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` produits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` produits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of produits.
   */
  distinct?: Prisma.ProduitsScalarFieldEnum | Prisma.ProduitsScalarFieldEnum[]
}

/**
 * produits findFirstOrThrow
 */
export type produitsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits
   */
  select?: Prisma.produitsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produits
   */
  omit?: Prisma.produitsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produitsInclude<ExtArgs> | null
  /**
   * Filter, which produits to fetch.
   */
  where?: Prisma.produitsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of produits to fetch.
   */
  orderBy?: Prisma.produitsOrderByWithRelationInput | Prisma.produitsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for produits.
   */
  cursor?: Prisma.produitsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` produits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` produits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of produits.
   */
  distinct?: Prisma.ProduitsScalarFieldEnum | Prisma.ProduitsScalarFieldEnum[]
}

/**
 * produits findMany
 */
export type produitsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits
   */
  select?: Prisma.produitsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produits
   */
  omit?: Prisma.produitsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produitsInclude<ExtArgs> | null
  /**
   * Filter, which produits to fetch.
   */
  where?: Prisma.produitsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of produits to fetch.
   */
  orderBy?: Prisma.produitsOrderByWithRelationInput | Prisma.produitsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing produits.
   */
  cursor?: Prisma.produitsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` produits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` produits.
   */
  skip?: number
  distinct?: Prisma.ProduitsScalarFieldEnum | Prisma.ProduitsScalarFieldEnum[]
}

/**
 * produits create
 */
export type produitsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits
   */
  select?: Prisma.produitsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produits
   */
  omit?: Prisma.produitsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produitsInclude<ExtArgs> | null
  /**
   * The data needed to create a produits.
   */
  data: Prisma.XOR<Prisma.produitsCreateInput, Prisma.produitsUncheckedCreateInput>
}

/**
 * produits createMany
 */
export type produitsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many produits.
   */
  data: Prisma.produitsCreateManyInput | Prisma.produitsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * produits createManyAndReturn
 */
export type produitsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits
   */
  select?: Prisma.produitsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the produits
   */
  omit?: Prisma.produitsOmit<ExtArgs> | null
  /**
   * The data used to create many produits.
   */
  data: Prisma.produitsCreateManyInput | Prisma.produitsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produitsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * produits update
 */
export type produitsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits
   */
  select?: Prisma.produitsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produits
   */
  omit?: Prisma.produitsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produitsInclude<ExtArgs> | null
  /**
   * The data needed to update a produits.
   */
  data: Prisma.XOR<Prisma.produitsUpdateInput, Prisma.produitsUncheckedUpdateInput>
  /**
   * Choose, which produits to update.
   */
  where: Prisma.produitsWhereUniqueInput
}

/**
 * produits updateMany
 */
export type produitsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update produits.
   */
  data: Prisma.XOR<Prisma.produitsUpdateManyMutationInput, Prisma.produitsUncheckedUpdateManyInput>
  /**
   * Filter which produits to update
   */
  where?: Prisma.produitsWhereInput
  /**
   * Limit how many produits to update.
   */
  limit?: number
}

/**
 * produits updateManyAndReturn
 */
export type produitsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits
   */
  select?: Prisma.produitsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the produits
   */
  omit?: Prisma.produitsOmit<ExtArgs> | null
  /**
   * The data used to update produits.
   */
  data: Prisma.XOR<Prisma.produitsUpdateManyMutationInput, Prisma.produitsUncheckedUpdateManyInput>
  /**
   * Filter which produits to update
   */
  where?: Prisma.produitsWhereInput
  /**
   * Limit how many produits to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produitsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * produits upsert
 */
export type produitsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits
   */
  select?: Prisma.produitsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produits
   */
  omit?: Prisma.produitsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produitsInclude<ExtArgs> | null
  /**
   * The filter to search for the produits to update in case it exists.
   */
  where: Prisma.produitsWhereUniqueInput
  /**
   * In case the produits found by the `where` argument doesn't exist, create a new produits with this data.
   */
  create: Prisma.XOR<Prisma.produitsCreateInput, Prisma.produitsUncheckedCreateInput>
  /**
   * In case the produits was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.produitsUpdateInput, Prisma.produitsUncheckedUpdateInput>
}

/**
 * produits delete
 */
export type produitsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits
   */
  select?: Prisma.produitsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produits
   */
  omit?: Prisma.produitsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produitsInclude<ExtArgs> | null
  /**
   * Filter which produits to delete.
   */
  where: Prisma.produitsWhereUniqueInput
}

/**
 * produits deleteMany
 */
export type produitsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which produits to delete
   */
  where?: Prisma.produitsWhereInput
  /**
   * Limit how many produits to delete.
   */
  limit?: number
}

/**
 * produits.produits_images
 */
export type produits$produits_imagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits_images
   */
  select?: Prisma.produits_imagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produits_images
   */
  omit?: Prisma.produits_imagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produits_imagesInclude<ExtArgs> | null
  where?: Prisma.produits_imagesWhereInput
  orderBy?: Prisma.produits_imagesOrderByWithRelationInput | Prisma.produits_imagesOrderByWithRelationInput[]
  cursor?: Prisma.produits_imagesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Produits_imagesScalarFieldEnum | Prisma.Produits_imagesScalarFieldEnum[]
}

/**
 * produits.reservations
 */
export type produits$reservationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reservations
   */
  select?: Prisma.reservationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reservations
   */
  omit?: Prisma.reservationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reservationsInclude<ExtArgs> | null
  where?: Prisma.reservationsWhereInput
  orderBy?: Prisma.reservationsOrderByWithRelationInput | Prisma.reservationsOrderByWithRelationInput[]
  cursor?: Prisma.reservationsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReservationsScalarFieldEnum | Prisma.ReservationsScalarFieldEnum[]
}

/**
 * produits without action
 */
export type produitsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produits
   */
  select?: Prisma.produitsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produits
   */
  omit?: Prisma.produitsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produitsInclude<ExtArgs> | null
}
