
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `transport_documents` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model transport_documents
 * 
 */
export type transport_documentsModel = runtime.Types.Result.DefaultSelection<Prisma.$transport_documentsPayload>

export type AggregateTransport_documents = {
  _count: Transport_documentsCountAggregateOutputType | null
  _avg: Transport_documentsAvgAggregateOutputType | null
  _sum: Transport_documentsSumAggregateOutputType | null
  _min: Transport_documentsMinAggregateOutputType | null
  _max: Transport_documentsMaxAggregateOutputType | null
}

export type Transport_documentsAvgAggregateOutputType = {
  taille: number | null
}

export type Transport_documentsSumAggregateOutputType = {
  taille: number | null
}

export type Transport_documentsMinAggregateOutputType = {
  id: string | null
  transport_id: string | null
  nom: string | null
  type: string | null
  url: string | null
  taille: number | null
  uploaded_par: string | null
  created_at: Date | null
}

export type Transport_documentsMaxAggregateOutputType = {
  id: string | null
  transport_id: string | null
  nom: string | null
  type: string | null
  url: string | null
  taille: number | null
  uploaded_par: string | null
  created_at: Date | null
}

export type Transport_documentsCountAggregateOutputType = {
  id: number
  transport_id: number
  nom: number
  type: number
  url: number
  taille: number
  uploaded_par: number
  created_at: number
  _all: number
}


export type Transport_documentsAvgAggregateInputType = {
  taille?: true
}

export type Transport_documentsSumAggregateInputType = {
  taille?: true
}

export type Transport_documentsMinAggregateInputType = {
  id?: true
  transport_id?: true
  nom?: true
  type?: true
  url?: true
  taille?: true
  uploaded_par?: true
  created_at?: true
}

export type Transport_documentsMaxAggregateInputType = {
  id?: true
  transport_id?: true
  nom?: true
  type?: true
  url?: true
  taille?: true
  uploaded_par?: true
  created_at?: true
}

export type Transport_documentsCountAggregateInputType = {
  id?: true
  transport_id?: true
  nom?: true
  type?: true
  url?: true
  taille?: true
  uploaded_par?: true
  created_at?: true
  _all?: true
}

export type Transport_documentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which transport_documents to aggregate.
   */
  where?: Prisma.transport_documentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of transport_documents to fetch.
   */
  orderBy?: Prisma.transport_documentsOrderByWithRelationInput | Prisma.transport_documentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.transport_documentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` transport_documents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` transport_documents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned transport_documents
  **/
  _count?: true | Transport_documentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Transport_documentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Transport_documentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Transport_documentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Transport_documentsMaxAggregateInputType
}

export type GetTransport_documentsAggregateType<T extends Transport_documentsAggregateArgs> = {
      [P in keyof T & keyof AggregateTransport_documents]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTransport_documents[P]>
    : Prisma.GetScalarType<T[P], AggregateTransport_documents[P]>
}




export type transport_documentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.transport_documentsWhereInput
  orderBy?: Prisma.transport_documentsOrderByWithAggregationInput | Prisma.transport_documentsOrderByWithAggregationInput[]
  by: Prisma.Transport_documentsScalarFieldEnum[] | Prisma.Transport_documentsScalarFieldEnum
  having?: Prisma.transport_documentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Transport_documentsCountAggregateInputType | true
  _avg?: Transport_documentsAvgAggregateInputType
  _sum?: Transport_documentsSumAggregateInputType
  _min?: Transport_documentsMinAggregateInputType
  _max?: Transport_documentsMaxAggregateInputType
}

export type Transport_documentsGroupByOutputType = {
  id: string
  transport_id: string
  nom: string
  type: string | null
  url: string
  taille: number | null
  uploaded_par: string | null
  created_at: Date | null
  _count: Transport_documentsCountAggregateOutputType | null
  _avg: Transport_documentsAvgAggregateOutputType | null
  _sum: Transport_documentsSumAggregateOutputType | null
  _min: Transport_documentsMinAggregateOutputType | null
  _max: Transport_documentsMaxAggregateOutputType | null
}

type GetTransport_documentsGroupByPayload<T extends transport_documentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Transport_documentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Transport_documentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Transport_documentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Transport_documentsGroupByOutputType[P]>
      }
    >
  >



export type transport_documentsWhereInput = {
  AND?: Prisma.transport_documentsWhereInput | Prisma.transport_documentsWhereInput[]
  OR?: Prisma.transport_documentsWhereInput[]
  NOT?: Prisma.transport_documentsWhereInput | Prisma.transport_documentsWhereInput[]
  id?: Prisma.StringFilter<"transport_documents"> | string
  transport_id?: Prisma.StringFilter<"transport_documents"> | string
  nom?: Prisma.StringFilter<"transport_documents"> | string
  type?: Prisma.StringNullableFilter<"transport_documents"> | string | null
  url?: Prisma.StringFilter<"transport_documents"> | string
  taille?: Prisma.IntNullableFilter<"transport_documents"> | number | null
  uploaded_par?: Prisma.StringNullableFilter<"transport_documents"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"transport_documents"> | Date | string | null
  transports?: Prisma.XOR<Prisma.TransportsScalarRelationFilter, Prisma.transportsWhereInput>
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}

export type transport_documentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  transport_id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrder
  taille?: Prisma.SortOrderInput | Prisma.SortOrder
  uploaded_par?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  transports?: Prisma.transportsOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
}

export type transport_documentsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.transport_documentsWhereInput | Prisma.transport_documentsWhereInput[]
  OR?: Prisma.transport_documentsWhereInput[]
  NOT?: Prisma.transport_documentsWhereInput | Prisma.transport_documentsWhereInput[]
  transport_id?: Prisma.StringFilter<"transport_documents"> | string
  nom?: Prisma.StringFilter<"transport_documents"> | string
  type?: Prisma.StringNullableFilter<"transport_documents"> | string | null
  url?: Prisma.StringFilter<"transport_documents"> | string
  taille?: Prisma.IntNullableFilter<"transport_documents"> | number | null
  uploaded_par?: Prisma.StringNullableFilter<"transport_documents"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"transport_documents"> | Date | string | null
  transports?: Prisma.XOR<Prisma.TransportsScalarRelationFilter, Prisma.transportsWhereInput>
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}, "id">

export type transport_documentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  transport_id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrder
  taille?: Prisma.SortOrderInput | Prisma.SortOrder
  uploaded_par?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.transport_documentsCountOrderByAggregateInput
  _avg?: Prisma.transport_documentsAvgOrderByAggregateInput
  _max?: Prisma.transport_documentsMaxOrderByAggregateInput
  _min?: Prisma.transport_documentsMinOrderByAggregateInput
  _sum?: Prisma.transport_documentsSumOrderByAggregateInput
}

export type transport_documentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.transport_documentsScalarWhereWithAggregatesInput | Prisma.transport_documentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.transport_documentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.transport_documentsScalarWhereWithAggregatesInput | Prisma.transport_documentsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"transport_documents"> | string
  transport_id?: Prisma.StringWithAggregatesFilter<"transport_documents"> | string
  nom?: Prisma.StringWithAggregatesFilter<"transport_documents"> | string
  type?: Prisma.StringNullableWithAggregatesFilter<"transport_documents"> | string | null
  url?: Prisma.StringWithAggregatesFilter<"transport_documents"> | string
  taille?: Prisma.IntNullableWithAggregatesFilter<"transport_documents"> | number | null
  uploaded_par?: Prisma.StringNullableWithAggregatesFilter<"transport_documents"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"transport_documents"> | Date | string | null
}

export type transport_documentsCreateInput = {
  id: string
  nom: string
  type?: string | null
  url: string
  taille?: number | null
  created_at?: Date | string | null
  transports: Prisma.transportsCreateNestedOneWithoutTransport_documentsInput
  users?: Prisma.usersCreateNestedOneWithoutTransport_documentsInput
}

export type transport_documentsUncheckedCreateInput = {
  id: string
  transport_id: string
  nom: string
  type?: string | null
  url: string
  taille?: number | null
  uploaded_par?: string | null
  created_at?: Date | string | null
}

export type transport_documentsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  taille?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  transports?: Prisma.transportsUpdateOneRequiredWithoutTransport_documentsNestedInput
  users?: Prisma.usersUpdateOneWithoutTransport_documentsNestedInput
}

export type transport_documentsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transport_id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  taille?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploaded_par?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type transport_documentsCreateManyInput = {
  id: string
  transport_id: string
  nom: string
  type?: string | null
  url: string
  taille?: number | null
  uploaded_par?: string | null
  created_at?: Date | string | null
}

export type transport_documentsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  taille?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type transport_documentsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transport_id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  taille?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploaded_par?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type transport_documentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transport_id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  type?: Prisma.SortOrder
  url?: Prisma.SortOrder
  taille?: Prisma.SortOrder
  uploaded_par?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type transport_documentsAvgOrderByAggregateInput = {
  taille?: Prisma.SortOrder
}

export type transport_documentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transport_id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  type?: Prisma.SortOrder
  url?: Prisma.SortOrder
  taille?: Prisma.SortOrder
  uploaded_par?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type transport_documentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transport_id?: Prisma.SortOrder
  nom?: Prisma.SortOrder
  type?: Prisma.SortOrder
  url?: Prisma.SortOrder
  taille?: Prisma.SortOrder
  uploaded_par?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type transport_documentsSumOrderByAggregateInput = {
  taille?: Prisma.SortOrder
}

export type Transport_documentsListRelationFilter = {
  every?: Prisma.transport_documentsWhereInput
  some?: Prisma.transport_documentsWhereInput
  none?: Prisma.transport_documentsWhereInput
}

export type transport_documentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type transport_documentsCreateNestedManyWithoutTransportsInput = {
  create?: Prisma.XOR<Prisma.transport_documentsCreateWithoutTransportsInput, Prisma.transport_documentsUncheckedCreateWithoutTransportsInput> | Prisma.transport_documentsCreateWithoutTransportsInput[] | Prisma.transport_documentsUncheckedCreateWithoutTransportsInput[]
  connectOrCreate?: Prisma.transport_documentsCreateOrConnectWithoutTransportsInput | Prisma.transport_documentsCreateOrConnectWithoutTransportsInput[]
  createMany?: Prisma.transport_documentsCreateManyTransportsInputEnvelope
  connect?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
}

export type transport_documentsUncheckedCreateNestedManyWithoutTransportsInput = {
  create?: Prisma.XOR<Prisma.transport_documentsCreateWithoutTransportsInput, Prisma.transport_documentsUncheckedCreateWithoutTransportsInput> | Prisma.transport_documentsCreateWithoutTransportsInput[] | Prisma.transport_documentsUncheckedCreateWithoutTransportsInput[]
  connectOrCreate?: Prisma.transport_documentsCreateOrConnectWithoutTransportsInput | Prisma.transport_documentsCreateOrConnectWithoutTransportsInput[]
  createMany?: Prisma.transport_documentsCreateManyTransportsInputEnvelope
  connect?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
}

export type transport_documentsUpdateManyWithoutTransportsNestedInput = {
  create?: Prisma.XOR<Prisma.transport_documentsCreateWithoutTransportsInput, Prisma.transport_documentsUncheckedCreateWithoutTransportsInput> | Prisma.transport_documentsCreateWithoutTransportsInput[] | Prisma.transport_documentsUncheckedCreateWithoutTransportsInput[]
  connectOrCreate?: Prisma.transport_documentsCreateOrConnectWithoutTransportsInput | Prisma.transport_documentsCreateOrConnectWithoutTransportsInput[]
  upsert?: Prisma.transport_documentsUpsertWithWhereUniqueWithoutTransportsInput | Prisma.transport_documentsUpsertWithWhereUniqueWithoutTransportsInput[]
  createMany?: Prisma.transport_documentsCreateManyTransportsInputEnvelope
  set?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  disconnect?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  delete?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  connect?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  update?: Prisma.transport_documentsUpdateWithWhereUniqueWithoutTransportsInput | Prisma.transport_documentsUpdateWithWhereUniqueWithoutTransportsInput[]
  updateMany?: Prisma.transport_documentsUpdateManyWithWhereWithoutTransportsInput | Prisma.transport_documentsUpdateManyWithWhereWithoutTransportsInput[]
  deleteMany?: Prisma.transport_documentsScalarWhereInput | Prisma.transport_documentsScalarWhereInput[]
}

export type transport_documentsUncheckedUpdateManyWithoutTransportsNestedInput = {
  create?: Prisma.XOR<Prisma.transport_documentsCreateWithoutTransportsInput, Prisma.transport_documentsUncheckedCreateWithoutTransportsInput> | Prisma.transport_documentsCreateWithoutTransportsInput[] | Prisma.transport_documentsUncheckedCreateWithoutTransportsInput[]
  connectOrCreate?: Prisma.transport_documentsCreateOrConnectWithoutTransportsInput | Prisma.transport_documentsCreateOrConnectWithoutTransportsInput[]
  upsert?: Prisma.transport_documentsUpsertWithWhereUniqueWithoutTransportsInput | Prisma.transport_documentsUpsertWithWhereUniqueWithoutTransportsInput[]
  createMany?: Prisma.transport_documentsCreateManyTransportsInputEnvelope
  set?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  disconnect?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  delete?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  connect?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  update?: Prisma.transport_documentsUpdateWithWhereUniqueWithoutTransportsInput | Prisma.transport_documentsUpdateWithWhereUniqueWithoutTransportsInput[]
  updateMany?: Prisma.transport_documentsUpdateManyWithWhereWithoutTransportsInput | Prisma.transport_documentsUpdateManyWithWhereWithoutTransportsInput[]
  deleteMany?: Prisma.transport_documentsScalarWhereInput | Prisma.transport_documentsScalarWhereInput[]
}

export type transport_documentsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.transport_documentsCreateWithoutUsersInput, Prisma.transport_documentsUncheckedCreateWithoutUsersInput> | Prisma.transport_documentsCreateWithoutUsersInput[] | Prisma.transport_documentsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.transport_documentsCreateOrConnectWithoutUsersInput | Prisma.transport_documentsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.transport_documentsCreateManyUsersInputEnvelope
  connect?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
}

export type transport_documentsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.transport_documentsCreateWithoutUsersInput, Prisma.transport_documentsUncheckedCreateWithoutUsersInput> | Prisma.transport_documentsCreateWithoutUsersInput[] | Prisma.transport_documentsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.transport_documentsCreateOrConnectWithoutUsersInput | Prisma.transport_documentsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.transport_documentsCreateManyUsersInputEnvelope
  connect?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
}

export type transport_documentsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.transport_documentsCreateWithoutUsersInput, Prisma.transport_documentsUncheckedCreateWithoutUsersInput> | Prisma.transport_documentsCreateWithoutUsersInput[] | Prisma.transport_documentsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.transport_documentsCreateOrConnectWithoutUsersInput | Prisma.transport_documentsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.transport_documentsUpsertWithWhereUniqueWithoutUsersInput | Prisma.transport_documentsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.transport_documentsCreateManyUsersInputEnvelope
  set?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  disconnect?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  delete?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  connect?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  update?: Prisma.transport_documentsUpdateWithWhereUniqueWithoutUsersInput | Prisma.transport_documentsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.transport_documentsUpdateManyWithWhereWithoutUsersInput | Prisma.transport_documentsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.transport_documentsScalarWhereInput | Prisma.transport_documentsScalarWhereInput[]
}

export type transport_documentsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.transport_documentsCreateWithoutUsersInput, Prisma.transport_documentsUncheckedCreateWithoutUsersInput> | Prisma.transport_documentsCreateWithoutUsersInput[] | Prisma.transport_documentsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.transport_documentsCreateOrConnectWithoutUsersInput | Prisma.transport_documentsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.transport_documentsUpsertWithWhereUniqueWithoutUsersInput | Prisma.transport_documentsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.transport_documentsCreateManyUsersInputEnvelope
  set?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  disconnect?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  delete?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  connect?: Prisma.transport_documentsWhereUniqueInput | Prisma.transport_documentsWhereUniqueInput[]
  update?: Prisma.transport_documentsUpdateWithWhereUniqueWithoutUsersInput | Prisma.transport_documentsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.transport_documentsUpdateManyWithWhereWithoutUsersInput | Prisma.transport_documentsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.transport_documentsScalarWhereInput | Prisma.transport_documentsScalarWhereInput[]
}

export type transport_documentsCreateWithoutTransportsInput = {
  id: string
  nom: string
  type?: string | null
  url: string
  taille?: number | null
  created_at?: Date | string | null
  users?: Prisma.usersCreateNestedOneWithoutTransport_documentsInput
}

export type transport_documentsUncheckedCreateWithoutTransportsInput = {
  id: string
  nom: string
  type?: string | null
  url: string
  taille?: number | null
  uploaded_par?: string | null
  created_at?: Date | string | null
}

export type transport_documentsCreateOrConnectWithoutTransportsInput = {
  where: Prisma.transport_documentsWhereUniqueInput
  create: Prisma.XOR<Prisma.transport_documentsCreateWithoutTransportsInput, Prisma.transport_documentsUncheckedCreateWithoutTransportsInput>
}

export type transport_documentsCreateManyTransportsInputEnvelope = {
  data: Prisma.transport_documentsCreateManyTransportsInput | Prisma.transport_documentsCreateManyTransportsInput[]
  skipDuplicates?: boolean
}

export type transport_documentsUpsertWithWhereUniqueWithoutTransportsInput = {
  where: Prisma.transport_documentsWhereUniqueInput
  update: Prisma.XOR<Prisma.transport_documentsUpdateWithoutTransportsInput, Prisma.transport_documentsUncheckedUpdateWithoutTransportsInput>
  create: Prisma.XOR<Prisma.transport_documentsCreateWithoutTransportsInput, Prisma.transport_documentsUncheckedCreateWithoutTransportsInput>
}

export type transport_documentsUpdateWithWhereUniqueWithoutTransportsInput = {
  where: Prisma.transport_documentsWhereUniqueInput
  data: Prisma.XOR<Prisma.transport_documentsUpdateWithoutTransportsInput, Prisma.transport_documentsUncheckedUpdateWithoutTransportsInput>
}

export type transport_documentsUpdateManyWithWhereWithoutTransportsInput = {
  where: Prisma.transport_documentsScalarWhereInput
  data: Prisma.XOR<Prisma.transport_documentsUpdateManyMutationInput, Prisma.transport_documentsUncheckedUpdateManyWithoutTransportsInput>
}

export type transport_documentsScalarWhereInput = {
  AND?: Prisma.transport_documentsScalarWhereInput | Prisma.transport_documentsScalarWhereInput[]
  OR?: Prisma.transport_documentsScalarWhereInput[]
  NOT?: Prisma.transport_documentsScalarWhereInput | Prisma.transport_documentsScalarWhereInput[]
  id?: Prisma.StringFilter<"transport_documents"> | string
  transport_id?: Prisma.StringFilter<"transport_documents"> | string
  nom?: Prisma.StringFilter<"transport_documents"> | string
  type?: Prisma.StringNullableFilter<"transport_documents"> | string | null
  url?: Prisma.StringFilter<"transport_documents"> | string
  taille?: Prisma.IntNullableFilter<"transport_documents"> | number | null
  uploaded_par?: Prisma.StringNullableFilter<"transport_documents"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"transport_documents"> | Date | string | null
}

export type transport_documentsCreateWithoutUsersInput = {
  id: string
  nom: string
  type?: string | null
  url: string
  taille?: number | null
  created_at?: Date | string | null
  transports: Prisma.transportsCreateNestedOneWithoutTransport_documentsInput
}

export type transport_documentsUncheckedCreateWithoutUsersInput = {
  id: string
  transport_id: string
  nom: string
  type?: string | null
  url: string
  taille?: number | null
  created_at?: Date | string | null
}

export type transport_documentsCreateOrConnectWithoutUsersInput = {
  where: Prisma.transport_documentsWhereUniqueInput
  create: Prisma.XOR<Prisma.transport_documentsCreateWithoutUsersInput, Prisma.transport_documentsUncheckedCreateWithoutUsersInput>
}

export type transport_documentsCreateManyUsersInputEnvelope = {
  data: Prisma.transport_documentsCreateManyUsersInput | Prisma.transport_documentsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type transport_documentsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.transport_documentsWhereUniqueInput
  update: Prisma.XOR<Prisma.transport_documentsUpdateWithoutUsersInput, Prisma.transport_documentsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.transport_documentsCreateWithoutUsersInput, Prisma.transport_documentsUncheckedCreateWithoutUsersInput>
}

export type transport_documentsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.transport_documentsWhereUniqueInput
  data: Prisma.XOR<Prisma.transport_documentsUpdateWithoutUsersInput, Prisma.transport_documentsUncheckedUpdateWithoutUsersInput>
}

export type transport_documentsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.transport_documentsScalarWhereInput
  data: Prisma.XOR<Prisma.transport_documentsUpdateManyMutationInput, Prisma.transport_documentsUncheckedUpdateManyWithoutUsersInput>
}

export type transport_documentsCreateManyTransportsInput = {
  id: string
  nom: string
  type?: string | null
  url: string
  taille?: number | null
  uploaded_par?: string | null
  created_at?: Date | string | null
}

export type transport_documentsUpdateWithoutTransportsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  taille?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneWithoutTransport_documentsNestedInput
}

export type transport_documentsUncheckedUpdateWithoutTransportsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  taille?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploaded_par?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type transport_documentsUncheckedUpdateManyWithoutTransportsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  taille?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploaded_par?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type transport_documentsCreateManyUsersInput = {
  id: string
  transport_id: string
  nom: string
  type?: string | null
  url: string
  taille?: number | null
  created_at?: Date | string | null
}

export type transport_documentsUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  taille?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  transports?: Prisma.transportsUpdateOneRequiredWithoutTransport_documentsNestedInput
}

export type transport_documentsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transport_id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  taille?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type transport_documentsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transport_id?: Prisma.StringFieldUpdateOperationsInput | string
  nom?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  taille?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type transport_documentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transport_id?: boolean
  nom?: boolean
  type?: boolean
  url?: boolean
  taille?: boolean
  uploaded_par?: boolean
  created_at?: boolean
  transports?: boolean | Prisma.transportsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.transport_documents$usersArgs<ExtArgs>
}, ExtArgs["result"]["transport_documents"]>

export type transport_documentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transport_id?: boolean
  nom?: boolean
  type?: boolean
  url?: boolean
  taille?: boolean
  uploaded_par?: boolean
  created_at?: boolean
  transports?: boolean | Prisma.transportsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.transport_documents$usersArgs<ExtArgs>
}, ExtArgs["result"]["transport_documents"]>

export type transport_documentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transport_id?: boolean
  nom?: boolean
  type?: boolean
  url?: boolean
  taille?: boolean
  uploaded_par?: boolean
  created_at?: boolean
  transports?: boolean | Prisma.transportsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.transport_documents$usersArgs<ExtArgs>
}, ExtArgs["result"]["transport_documents"]>

export type transport_documentsSelectScalar = {
  id?: boolean
  transport_id?: boolean
  nom?: boolean
  type?: boolean
  url?: boolean
  taille?: boolean
  uploaded_par?: boolean
  created_at?: boolean
}

export type transport_documentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "transport_id" | "nom" | "type" | "url" | "taille" | "uploaded_par" | "created_at", ExtArgs["result"]["transport_documents"]>
export type transport_documentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transports?: boolean | Prisma.transportsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.transport_documents$usersArgs<ExtArgs>
}
export type transport_documentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transports?: boolean | Prisma.transportsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.transport_documents$usersArgs<ExtArgs>
}
export type transport_documentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transports?: boolean | Prisma.transportsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.transport_documents$usersArgs<ExtArgs>
}

export type $transport_documentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "transport_documents"
  objects: {
    transports: Prisma.$transportsPayload<ExtArgs>
    users: Prisma.$usersPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    transport_id: string
    nom: string
    type: string | null
    url: string
    taille: number | null
    uploaded_par: string | null
    created_at: Date | null
  }, ExtArgs["result"]["transport_documents"]>
  composites: {}
}

export type transport_documentsGetPayload<S extends boolean | null | undefined | transport_documentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$transport_documentsPayload, S>

export type transport_documentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<transport_documentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Transport_documentsCountAggregateInputType | true
  }

export interface transport_documentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['transport_documents'], meta: { name: 'transport_documents' } }
  /**
   * Find zero or one Transport_documents that matches the filter.
   * @param {transport_documentsFindUniqueArgs} args - Arguments to find a Transport_documents
   * @example
   * // Get one Transport_documents
   * const transport_documents = await prisma.transport_documents.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends transport_documentsFindUniqueArgs>(args: Prisma.SelectSubset<T, transport_documentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__transport_documentsClient<runtime.Types.Result.GetResult<Prisma.$transport_documentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Transport_documents that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {transport_documentsFindUniqueOrThrowArgs} args - Arguments to find a Transport_documents
   * @example
   * // Get one Transport_documents
   * const transport_documents = await prisma.transport_documents.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends transport_documentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, transport_documentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__transport_documentsClient<runtime.Types.Result.GetResult<Prisma.$transport_documentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Transport_documents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {transport_documentsFindFirstArgs} args - Arguments to find a Transport_documents
   * @example
   * // Get one Transport_documents
   * const transport_documents = await prisma.transport_documents.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends transport_documentsFindFirstArgs>(args?: Prisma.SelectSubset<T, transport_documentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__transport_documentsClient<runtime.Types.Result.GetResult<Prisma.$transport_documentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Transport_documents that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {transport_documentsFindFirstOrThrowArgs} args - Arguments to find a Transport_documents
   * @example
   * // Get one Transport_documents
   * const transport_documents = await prisma.transport_documents.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends transport_documentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, transport_documentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__transport_documentsClient<runtime.Types.Result.GetResult<Prisma.$transport_documentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Transport_documents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {transport_documentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Transport_documents
   * const transport_documents = await prisma.transport_documents.findMany()
   * 
   * // Get first 10 Transport_documents
   * const transport_documents = await prisma.transport_documents.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const transport_documentsWithIdOnly = await prisma.transport_documents.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends transport_documentsFindManyArgs>(args?: Prisma.SelectSubset<T, transport_documentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$transport_documentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Transport_documents.
   * @param {transport_documentsCreateArgs} args - Arguments to create a Transport_documents.
   * @example
   * // Create one Transport_documents
   * const Transport_documents = await prisma.transport_documents.create({
   *   data: {
   *     // ... data to create a Transport_documents
   *   }
   * })
   * 
   */
  create<T extends transport_documentsCreateArgs>(args: Prisma.SelectSubset<T, transport_documentsCreateArgs<ExtArgs>>): Prisma.Prisma__transport_documentsClient<runtime.Types.Result.GetResult<Prisma.$transport_documentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Transport_documents.
   * @param {transport_documentsCreateManyArgs} args - Arguments to create many Transport_documents.
   * @example
   * // Create many Transport_documents
   * const transport_documents = await prisma.transport_documents.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends transport_documentsCreateManyArgs>(args?: Prisma.SelectSubset<T, transport_documentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Transport_documents and returns the data saved in the database.
   * @param {transport_documentsCreateManyAndReturnArgs} args - Arguments to create many Transport_documents.
   * @example
   * // Create many Transport_documents
   * const transport_documents = await prisma.transport_documents.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Transport_documents and only return the `id`
   * const transport_documentsWithIdOnly = await prisma.transport_documents.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends transport_documentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, transport_documentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$transport_documentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Transport_documents.
   * @param {transport_documentsDeleteArgs} args - Arguments to delete one Transport_documents.
   * @example
   * // Delete one Transport_documents
   * const Transport_documents = await prisma.transport_documents.delete({
   *   where: {
   *     // ... filter to delete one Transport_documents
   *   }
   * })
   * 
   */
  delete<T extends transport_documentsDeleteArgs>(args: Prisma.SelectSubset<T, transport_documentsDeleteArgs<ExtArgs>>): Prisma.Prisma__transport_documentsClient<runtime.Types.Result.GetResult<Prisma.$transport_documentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Transport_documents.
   * @param {transport_documentsUpdateArgs} args - Arguments to update one Transport_documents.
   * @example
   * // Update one Transport_documents
   * const transport_documents = await prisma.transport_documents.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends transport_documentsUpdateArgs>(args: Prisma.SelectSubset<T, transport_documentsUpdateArgs<ExtArgs>>): Prisma.Prisma__transport_documentsClient<runtime.Types.Result.GetResult<Prisma.$transport_documentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Transport_documents.
   * @param {transport_documentsDeleteManyArgs} args - Arguments to filter Transport_documents to delete.
   * @example
   * // Delete a few Transport_documents
   * const { count } = await prisma.transport_documents.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends transport_documentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, transport_documentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Transport_documents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {transport_documentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Transport_documents
   * const transport_documents = await prisma.transport_documents.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends transport_documentsUpdateManyArgs>(args: Prisma.SelectSubset<T, transport_documentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Transport_documents and returns the data updated in the database.
   * @param {transport_documentsUpdateManyAndReturnArgs} args - Arguments to update many Transport_documents.
   * @example
   * // Update many Transport_documents
   * const transport_documents = await prisma.transport_documents.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Transport_documents and only return the `id`
   * const transport_documentsWithIdOnly = await prisma.transport_documents.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends transport_documentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, transport_documentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$transport_documentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Transport_documents.
   * @param {transport_documentsUpsertArgs} args - Arguments to update or create a Transport_documents.
   * @example
   * // Update or create a Transport_documents
   * const transport_documents = await prisma.transport_documents.upsert({
   *   create: {
   *     // ... data to create a Transport_documents
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Transport_documents we want to update
   *   }
   * })
   */
  upsert<T extends transport_documentsUpsertArgs>(args: Prisma.SelectSubset<T, transport_documentsUpsertArgs<ExtArgs>>): Prisma.Prisma__transport_documentsClient<runtime.Types.Result.GetResult<Prisma.$transport_documentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Transport_documents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {transport_documentsCountArgs} args - Arguments to filter Transport_documents to count.
   * @example
   * // Count the number of Transport_documents
   * const count = await prisma.transport_documents.count({
   *   where: {
   *     // ... the filter for the Transport_documents we want to count
   *   }
   * })
  **/
  count<T extends transport_documentsCountArgs>(
    args?: Prisma.Subset<T, transport_documentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Transport_documentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Transport_documents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Transport_documentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Transport_documentsAggregateArgs>(args: Prisma.Subset<T, Transport_documentsAggregateArgs>): Prisma.PrismaPromise<GetTransport_documentsAggregateType<T>>

  /**
   * Group by Transport_documents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {transport_documentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends transport_documentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: transport_documentsGroupByArgs['orderBy'] }
      : { orderBy?: transport_documentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, transport_documentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTransport_documentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the transport_documents model
 */
readonly fields: transport_documentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for transport_documents.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__transport_documentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  transports<T extends Prisma.transportsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.transportsDefaultArgs<ExtArgs>>): Prisma.Prisma__transportsClient<runtime.Types.Result.GetResult<Prisma.$transportsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.transport_documents$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.transport_documents$usersArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the transport_documents model
 */
export interface transport_documentsFieldRefs {
  readonly id: Prisma.FieldRef<"transport_documents", 'String'>
  readonly transport_id: Prisma.FieldRef<"transport_documents", 'String'>
  readonly nom: Prisma.FieldRef<"transport_documents", 'String'>
  readonly type: Prisma.FieldRef<"transport_documents", 'String'>
  readonly url: Prisma.FieldRef<"transport_documents", 'String'>
  readonly taille: Prisma.FieldRef<"transport_documents", 'Int'>
  readonly uploaded_par: Prisma.FieldRef<"transport_documents", 'String'>
  readonly created_at: Prisma.FieldRef<"transport_documents", 'DateTime'>
}
    

// Custom InputTypes
/**
 * transport_documents findUnique
 */
export type transport_documentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the transport_documents
   */
  select?: Prisma.transport_documentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the transport_documents
   */
  omit?: Prisma.transport_documentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.transport_documentsInclude<ExtArgs> | null
  /**
   * Filter, which transport_documents to fetch.
   */
  where: Prisma.transport_documentsWhereUniqueInput
}

/**
 * transport_documents findUniqueOrThrow
 */
export type transport_documentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the transport_documents
   */
  select?: Prisma.transport_documentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the transport_documents
   */
  omit?: Prisma.transport_documentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.transport_documentsInclude<ExtArgs> | null
  /**
   * Filter, which transport_documents to fetch.
   */
  where: Prisma.transport_documentsWhereUniqueInput
}

/**
 * transport_documents findFirst
 */
export type transport_documentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the transport_documents
   */
  select?: Prisma.transport_documentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the transport_documents
   */
  omit?: Prisma.transport_documentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.transport_documentsInclude<ExtArgs> | null
  /**
   * Filter, which transport_documents to fetch.
   */
  where?: Prisma.transport_documentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of transport_documents to fetch.
   */
  orderBy?: Prisma.transport_documentsOrderByWithRelationInput | Prisma.transport_documentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for transport_documents.
   */
  cursor?: Prisma.transport_documentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` transport_documents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` transport_documents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of transport_documents.
   */
  distinct?: Prisma.Transport_documentsScalarFieldEnum | Prisma.Transport_documentsScalarFieldEnum[]
}

/**
 * transport_documents findFirstOrThrow
 */
export type transport_documentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the transport_documents
   */
  select?: Prisma.transport_documentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the transport_documents
   */
  omit?: Prisma.transport_documentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.transport_documentsInclude<ExtArgs> | null
  /**
   * Filter, which transport_documents to fetch.
   */
  where?: Prisma.transport_documentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of transport_documents to fetch.
   */
  orderBy?: Prisma.transport_documentsOrderByWithRelationInput | Prisma.transport_documentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for transport_documents.
   */
  cursor?: Prisma.transport_documentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` transport_documents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` transport_documents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of transport_documents.
   */
  distinct?: Prisma.Transport_documentsScalarFieldEnum | Prisma.Transport_documentsScalarFieldEnum[]
}

/**
 * transport_documents findMany
 */
export type transport_documentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the transport_documents
   */
  select?: Prisma.transport_documentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the transport_documents
   */
  omit?: Prisma.transport_documentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.transport_documentsInclude<ExtArgs> | null
  /**
   * Filter, which transport_documents to fetch.
   */
  where?: Prisma.transport_documentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of transport_documents to fetch.
   */
  orderBy?: Prisma.transport_documentsOrderByWithRelationInput | Prisma.transport_documentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing transport_documents.
   */
  cursor?: Prisma.transport_documentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` transport_documents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` transport_documents.
   */
  skip?: number
  distinct?: Prisma.Transport_documentsScalarFieldEnum | Prisma.Transport_documentsScalarFieldEnum[]
}

/**
 * transport_documents create
 */
export type transport_documentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the transport_documents
   */
  select?: Prisma.transport_documentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the transport_documents
   */
  omit?: Prisma.transport_documentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.transport_documentsInclude<ExtArgs> | null
  /**
   * The data needed to create a transport_documents.
   */
  data: Prisma.XOR<Prisma.transport_documentsCreateInput, Prisma.transport_documentsUncheckedCreateInput>
}

/**
 * transport_documents createMany
 */
export type transport_documentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many transport_documents.
   */
  data: Prisma.transport_documentsCreateManyInput | Prisma.transport_documentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * transport_documents createManyAndReturn
 */
export type transport_documentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the transport_documents
   */
  select?: Prisma.transport_documentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the transport_documents
   */
  omit?: Prisma.transport_documentsOmit<ExtArgs> | null
  /**
   * The data used to create many transport_documents.
   */
  data: Prisma.transport_documentsCreateManyInput | Prisma.transport_documentsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.transport_documentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * transport_documents update
 */
export type transport_documentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the transport_documents
   */
  select?: Prisma.transport_documentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the transport_documents
   */
  omit?: Prisma.transport_documentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.transport_documentsInclude<ExtArgs> | null
  /**
   * The data needed to update a transport_documents.
   */
  data: Prisma.XOR<Prisma.transport_documentsUpdateInput, Prisma.transport_documentsUncheckedUpdateInput>
  /**
   * Choose, which transport_documents to update.
   */
  where: Prisma.transport_documentsWhereUniqueInput
}

/**
 * transport_documents updateMany
 */
export type transport_documentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update transport_documents.
   */
  data: Prisma.XOR<Prisma.transport_documentsUpdateManyMutationInput, Prisma.transport_documentsUncheckedUpdateManyInput>
  /**
   * Filter which transport_documents to update
   */
  where?: Prisma.transport_documentsWhereInput
  /**
   * Limit how many transport_documents to update.
   */
  limit?: number
}

/**
 * transport_documents updateManyAndReturn
 */
export type transport_documentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the transport_documents
   */
  select?: Prisma.transport_documentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the transport_documents
   */
  omit?: Prisma.transport_documentsOmit<ExtArgs> | null
  /**
   * The data used to update transport_documents.
   */
  data: Prisma.XOR<Prisma.transport_documentsUpdateManyMutationInput, Prisma.transport_documentsUncheckedUpdateManyInput>
  /**
   * Filter which transport_documents to update
   */
  where?: Prisma.transport_documentsWhereInput
  /**
   * Limit how many transport_documents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.transport_documentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * transport_documents upsert
 */
export type transport_documentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the transport_documents
   */
  select?: Prisma.transport_documentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the transport_documents
   */
  omit?: Prisma.transport_documentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.transport_documentsInclude<ExtArgs> | null
  /**
   * The filter to search for the transport_documents to update in case it exists.
   */
  where: Prisma.transport_documentsWhereUniqueInput
  /**
   * In case the transport_documents found by the `where` argument doesn't exist, create a new transport_documents with this data.
   */
  create: Prisma.XOR<Prisma.transport_documentsCreateInput, Prisma.transport_documentsUncheckedCreateInput>
  /**
   * In case the transport_documents was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.transport_documentsUpdateInput, Prisma.transport_documentsUncheckedUpdateInput>
}

/**
 * transport_documents delete
 */
export type transport_documentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the transport_documents
   */
  select?: Prisma.transport_documentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the transport_documents
   */
  omit?: Prisma.transport_documentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.transport_documentsInclude<ExtArgs> | null
  /**
   * Filter which transport_documents to delete.
   */
  where: Prisma.transport_documentsWhereUniqueInput
}

/**
 * transport_documents deleteMany
 */
export type transport_documentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which transport_documents to delete
   */
  where?: Prisma.transport_documentsWhereInput
  /**
   * Limit how many transport_documents to delete.
   */
  limit?: number
}

/**
 * transport_documents.users
 */
export type transport_documents$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
}

/**
 * transport_documents without action
 */
export type transport_documentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the transport_documents
   */
  select?: Prisma.transport_documentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the transport_documents
   */
  omit?: Prisma.transport_documentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.transport_documentsInclude<ExtArgs> | null
}
